import { ADMIN_EMAIL, ADMIN_NAME, BRAND_NAME, FOOTER_TEXT, LOGO_URL, SENDER_EMAIL, SENDER_NAME, supabaseAdmin } from "../core/env.ts";
import type { LibraryNotificationContext } from "../core/types.ts";
function asBool(v: unknown, f: boolean) { return typeof v === "boolean" ? v : f; }
export function fallbackLibraryNotificationContext(libraryId?: string | null): LibraryNotificationContext {
  return { library_id: libraryId||null, slug: null, library_name: BRAND_NAME, library_short_name: String(BRAND_NAME||"AnarBib").trim()||"AnarBib", sender_display_name: SENDER_NAME, reply_to_name: ADMIN_NAME||SENDER_NAME, reply_to_email: ADMIN_EMAIL||null, signature_short: ADMIN_NAME||null, footer_local: FOOTER_TEXT, use_library_name_as_sender: true, use_library_logo: true, logo_url: LOGO_URL||null, logo_file_key: null, sender_visible_email: SENDER_EMAIL, reservation_created_enabled: true, reservation_status_enabled: true, reservation_workflow_enabled: true, local_consultation_enabled: true, loan_lifecycle_enabled: true, loan_reminders_enabled: true, loan_overdue_enabled: true, profile_restriction_enabled: true, mid_loan_message_enabled: false, reading_recommendations_enabled: false, admin_copy_reservations_enabled: true, admin_copy_loans_enabled: true, tech_alerts_enabled: true, task_alerts_enabled: true, delivery_mode: "platform_shared", admin_notification_email: ADMIN_EMAIL||null, weekly_report_email: ADMIN_EMAIL||null, severe_alert_email: ADMIN_EMAIL||null, transport_state: null, transport_channel: "platform_shared", last_tested_at: null, channel_active: true };
}
export function normalizeLibraryNotificationContext(input: Record<string, unknown>|null|undefined, libraryId?: string|null): LibraryNotificationContext {
  const b = fallbackLibraryNotificationContext(libraryId); const r = input || {};
  return { ...b, ...r, library_id: String(r.library_id||b.library_id||"").trim()||null, slug: String(r.slug||b.slug||"").trim()||null, library_name: String(r.library_name||b.library_name||"").trim()||b.library_name, library_short_name: String(r.library_short_name||b.library_short_name||"").trim()||b.library_short_name, sender_display_name: String(r.sender_display_name||b.sender_display_name||"").trim()||null, reply_to_name: String(r.reply_to_name||b.reply_to_name||"").trim()||null, reply_to_email: String(r.reply_to_email||b.reply_to_email||"").trim()||null, signature_short: String(r.signature_short||b.signature_short||"").trim()||null, footer_local: String(r.footer_local||b.footer_local||"").trim()||null, use_library_name_as_sender: asBool(r.use_library_name_as_sender,true), use_library_logo: asBool(r.use_library_logo,true), logo_url: String(r.logo_url||b.logo_url||"").trim()||null, logo_file_key: String(r.logo_file_key||b.logo_file_key||"").trim()||null, sender_visible_email: String(r.sender_visible_email||b.sender_visible_email||"").trim()||null, reservation_created_enabled: asBool(r.reservation_created_enabled,true), reservation_status_enabled: asBool(r.reservation_status_enabled,true), reservation_workflow_enabled: asBool(r.reservation_workflow_enabled,true), local_consultation_enabled: asBool(r.local_consultation_enabled,true), loan_lifecycle_enabled: asBool(r.loan_lifecycle_enabled,true), loan_reminders_enabled: asBool(r.loan_reminders_enabled,true), loan_overdue_enabled: asBool(r.loan_overdue_enabled,true), profile_restriction_enabled: asBool(r.profile_restriction_enabled,true), mid_loan_message_enabled: asBool(r.mid_loan_message_enabled,false), reading_recommendations_enabled: asBool(r.reading_recommendations_enabled,false), admin_copy_reservations_enabled: asBool(r.admin_copy_reservations_enabled,true), admin_copy_loans_enabled: asBool(r.admin_copy_loans_enabled,true), tech_alerts_enabled: asBool(r.tech_alerts_enabled,true), task_alerts_enabled: asBool(r.task_alerts_enabled,true), delivery_mode: String(r.delivery_mode||b.delivery_mode||"platform_shared").trim()||"platform_shared", admin_notification_email: String(r.admin_notification_email||b.admin_notification_email||"").trim()||null, weekly_report_email: String(r.weekly_report_email||b.weekly_report_email||"").trim()||null, severe_alert_email: String(r.severe_alert_email||b.severe_alert_email||"").trim()||null, transport_state: String(r.transport_state||b.transport_state||"").trim()||null, transport_channel: String(r.transport_channel||r.delivery_mode||b.transport_channel||"platform_shared").trim()||"platform_shared", last_tested_at: String(r.last_tested_at||b.last_tested_at||"").trim()||null, channel_active: asBool(r.channel_active,true) };
}
export async function resolveLibraryNotificationContext(libraryId?: string|null): Promise<LibraryNotificationContext> {
  const n = String(libraryId||"").trim(); if (!n) return fallbackLibraryNotificationContext(null);
  try { const { data, error } = await supabaseAdmin.from("v_library_notification_context").select("*").eq("library_id", n).maybeSingle(); if (error) throw error; return normalizeLibraryNotificationContext((data||null) as Record<string,unknown>|null, n); }
  catch (e) { console.warn("resolveLibraryNotificationContext fallback:", e); return fallbackLibraryNotificationContext(n); }
}
