// strings.ts — chaînes localisées des e-mails d'onboarding (#111 follow-up mail).
// L'EF notify-library-request rendait tout en pt-BR ; on localise désormais selon
// la langue du·de la destinataire (solicitante : preferred_language ; admins :
// fan-out, chacun·e dans sa langue). Phase 1 : sujet + salutation + intro + sous-titre
// + pied. Les libellés de champs du tableau de détails restent pt-BR (phase 2).
//
// Charte inclusive par locale (cf. anarbib-charte-langage-inclusif-v2) ; el/eo/nl :
// formes neutres. Placeholders : {name}, {library}. Fallback : pt-BR.

export const FALLBACK_LOCALE = "pt-BR";

export const STRINGS: Record<string, Record<string, string>> = {
  "pt-BR": {
    subtitle: "Solicitação institucional · notificação automática",
    greetingNamed: "Olá, {name}!",
    greeting: "Olá!",
    footer: "Em caso de dúvida, responde a este e-mail.",
    "created.subject": "Solicitação recebida",
    "created.intro": "Recebemos a solicitação institucional da biblioteca {library}. A coordenação da rede vai analisá-la.",
    "in_analysis.subject": "Solicitação em análise",
    "in_analysis.intro": "A solicitação da biblioteca {library} está em análise pela coordenação da rede.",
    "more_info.subject": "Precisamos de informações complementares",
    "more_info.intro": "A coordenação precisa de informações complementares sobre a solicitação da biblioteca {library}. Responde a este e-mail.",
    "approved.subject": "Solicitação aprovada",
    "approved.intro": "A solicitação da biblioteca {library} foi aprovada. Bem-vinda à rede!",
    "refused.subject": "Solicitação recusada",
    "refused.intro": "A solicitação da biblioteca {library} não foi aceita nesta etapa.",
    "message.subject": "Nova mensagem da coordenação",
    "message.intro": "A coordenação da rede enviou uma mensagem sobre a solicitação da biblioteca {library}.",
    "invitation_proposed.subject": "Convite para uma conversa",
    "invitation_proposed.intro": "A coordenação propõe uma conversa sobre a solicitação da biblioteca {library}.",
    "invitation_response.subject": "Resposta ao teu convite",
    "invitation_response.intro": "A coordenação respondeu ao convite de conversa sobre a solicitação da biblioteca {library}.",
    "admin_created.subject": "Nova solicitação institucional",
    "admin_created.intro": "Uma nova solicitação institucional foi registrada: {library}. Consulta o painel de rede.",
    "admin_update.subject": "Atualização de solicitação institucional",
    "admin_update.intro": "A solicitação da biblioteca {library} foi atualizada no painel de rede.",
    "admin_message.subject": "Mensagem de uma biblioteca solicitante",
    "admin_message.intro": "A biblioteca {library} respondeu na sua solicitação. Consulta o painel de rede.",
    "admin_invitation.subject": "Pedido de conversa de uma solicitante",
    "admin_invitation.intro": "A biblioteca {library} pede uma conversa com a coordenação da rede.",
  },
  fr: {
    subtitle: "Demande institutionnelle · notification automatique",
    greetingNamed: "Bonjour {name},",
    greeting: "Bonjour,",
    footer: "En cas de doute, répondez à cet e-mail.",
    "created.subject": "Demande reçue",
    "created.intro": "Nous avons reçu la demande institutionnelle de la bibliothèque {library}. La coordination du réseau va l'étudier.",
    "in_analysis.subject": "Demande en cours d'examen",
    "in_analysis.intro": "La demande de la bibliothèque {library} est en cours d'examen par la coordination du réseau.",
    "more_info.subject": "Informations complémentaires nécessaires",
    "more_info.intro": "La coordination a besoin d'informations complémentaires sur la demande de la bibliothèque {library}. Répondez à cet e-mail.",
    "approved.subject": "Demande approuvée",
    "approved.intro": "La demande de la bibliothèque {library} est approuvée. Bienvenue dans le réseau !",
    "refused.subject": "Demande refusée",
    "refused.intro": "La demande de la bibliothèque {library} n'a pas été retenue à cette étape.",
    "message.subject": "Nouveau message de la coordination",
    "message.intro": "La coordination du réseau a envoyé un message au sujet de la demande de la bibliothèque {library}.",
    "invitation_proposed.subject": "Invitation à un échange",
    "invitation_proposed.intro": "La coordination propose un échange au sujet de la demande de la bibliothèque {library}.",
    "invitation_response.subject": "Réponse à votre invitation",
    "invitation_response.intro": "La coordination a répondu à l'invitation à échanger au sujet de la demande de la bibliothèque {library}.",
    "admin_created.subject": "Nouvelle demande institutionnelle",
    "admin_created.intro": "Une nouvelle demande institutionnelle a été enregistrée : {library}. Consultez le panneau réseau.",
    "admin_update.subject": "Mise à jour d'une demande institutionnelle",
    "admin_update.intro": "La demande de la bibliothèque {library} a été mise à jour dans le panneau réseau.",
    "admin_message.subject": "Message d'une bibliothèque solicitante",
    "admin_message.intro": "La bibliothèque {library} a répondu sur sa demande. Consultez le panneau réseau.",
    "admin_invitation.subject": "Demande d'échange d'une solicitante",
    "admin_invitation.intro": "La bibliothèque {library} demande un échange avec la coordination du réseau.",
  },
  es: {
    subtitle: "Solicitud institucional · notificación automática",
    greetingNamed: "Hola, {name}:",
    greeting: "Hola:",
    footer: "Si tienes dudas, responde a este correo.",
    "created.subject": "Solicitud recibida",
    "created.intro": "Hemos recibido la solicitud institucional de la biblioteca {library}. La coordinación de la red la analizará.",
    "in_analysis.subject": "Solicitud en análisis",
    "in_analysis.intro": "La solicitud de la biblioteca {library} está siendo analizada por la coordinación de la red.",
    "more_info.subject": "Necesitamos información complementaria",
    "more_info.intro": "La coordinación necesita información complementaria sobre la solicitud de la biblioteca {library}. Responde a este correo.",
    "approved.subject": "Solicitud aprobada",
    "approved.intro": "La solicitud de la biblioteca {library} fue aprobada. ¡Bienvenida a la red!",
    "refused.subject": "Solicitud rechazada",
    "refused.intro": "La solicitud de la biblioteca {library} no fue aceptada en esta etapa.",
    "message.subject": "Nuevo mensaje de la coordinación",
    "message.intro": "La coordinación de la red envió un mensaje sobre la solicitud de la biblioteca {library}.",
    "invitation_proposed.subject": "Invitación a una conversación",
    "invitation_proposed.intro": "La coordinación propone una conversación sobre la solicitud de la biblioteca {library}.",
    "invitation_response.subject": "Respuesta a tu invitación",
    "invitation_response.intro": "La coordinación respondió a la invitación a conversar sobre la solicitud de la biblioteca {library}.",
    "admin_created.subject": "Nueva solicitud institucional",
    "admin_created.intro": "Se registró una nueva solicitud institucional: {library}. Consulta el panel de red.",
    "admin_update.subject": "Actualización de solicitud institucional",
    "admin_update.intro": "La solicitud de la biblioteca {library} se actualizó en el panel de red.",
    "admin_message.subject": "Mensaje de una biblioteca solicitante",
    "admin_message.intro": "La biblioteca {library} respondió en su solicitud. Consulta el panel de red.",
    "admin_invitation.subject": "Solicitud de conversación de una solicitante",
    "admin_invitation.intro": "La biblioteca {library} pide una conversación con la coordinación de la red.",
  },
  en: {
    subtitle: "Institutional request · automatic notification",
    greetingNamed: "Hello {name},",
    greeting: "Hello,",
    footer: "If in doubt, just reply to this email.",
    "created.subject": "Request received",
    "created.intro": "We received the institutional request from the {library} library. The network coordination will review it.",
    "in_analysis.subject": "Request under review",
    "in_analysis.intro": "The {library} library's request is being reviewed by the network coordination.",
    "more_info.subject": "We need additional information",
    "more_info.intro": "The coordination needs additional information about the {library} library's request. Please reply to this email.",
    "approved.subject": "Request approved",
    "approved.intro": "The {library} library's request has been approved. Welcome to the network!",
    "refused.subject": "Request declined",
    "refused.intro": "The {library} library's request was not accepted at this stage.",
    "message.subject": "New message from the coordination",
    "message.intro": "The network coordination sent a message about the {library} library's request.",
    "invitation_proposed.subject": "Invitation to a conversation",
    "invitation_proposed.intro": "The coordination proposes a conversation about the {library} library's request.",
    "invitation_response.subject": "Reply to your invitation",
    "invitation_response.intro": "The coordination replied to the invitation to talk about the {library} library's request.",
    "admin_created.subject": "New institutional request",
    "admin_created.intro": "A new institutional request was registered: {library}. Check the network panel.",
    "admin_update.subject": "Institutional request updated",
    "admin_update.intro": "The {library} library's request was updated in the network panel.",
    "admin_message.subject": "Message from an applicant library",
    "admin_message.intro": "The {library} library replied on its request. Check the network panel.",
    "admin_invitation.subject": "Conversation request from an applicant",
    "admin_invitation.intro": "The {library} library is requesting a conversation with the network coordination.",
  },
  it: {
    subtitle: "Richiesta istituzionale · notifica automatica",
    greetingNamed: "Ciao {name},",
    greeting: "Ciao,",
    footer: "In caso di dubbi, rispondi a questa e-mail.",
    "created.subject": "Richiesta ricevuta",
    "created.intro": "Abbiamo ricevuto la richiesta istituzionale della biblioteca {library}. La coordinazione della rete la esaminerà.",
    "in_analysis.subject": "Richiesta in esame",
    "in_analysis.intro": "La richiesta della biblioteca {library} è in esame da parte della coordinazione della rete.",
    "more_info.subject": "Servono informazioni complementari",
    "more_info.intro": "La coordinazione ha bisogno di informazioni complementari sulla richiesta della biblioteca {library}. Rispondi a questa e-mail.",
    "approved.subject": "Richiesta approvata",
    "approved.intro": "La richiesta della biblioteca {library} è stata approvata. Benvenuta nella rete!",
    "refused.subject": "Richiesta rifiutata",
    "refused.intro": "La richiesta della biblioteca {library} non è stata accolta in questa fase.",
    "message.subject": "Nuovo messaggio dalla coordinazione",
    "message.intro": "La coordinazione della rete ha inviato un messaggio sulla richiesta della biblioteca {library}.",
    "invitation_proposed.subject": "Invito a uno scambio",
    "invitation_proposed.intro": "La coordinazione propone uno scambio sulla richiesta della biblioteca {library}.",
    "invitation_response.subject": "Risposta al tuo invito",
    "invitation_response.intro": "La coordinazione ha risposto all'invito a parlare della richiesta della biblioteca {library}.",
    "admin_created.subject": "Nuova richiesta istituzionale",
    "admin_created.intro": "È stata registrata una nuova richiesta istituzionale: {library}. Consulta il pannello di rete.",
    "admin_update.subject": "Aggiornamento di una richiesta istituzionale",
    "admin_update.intro": "La richiesta della biblioteca {library} è stata aggiornata nel pannello di rete.",
    "admin_message.subject": "Messaggio di una biblioteca richiedente",
    "admin_message.intro": "La biblioteca {library} ha risposto sulla sua richiesta. Consulta il pannello di rete.",
    "admin_invitation.subject": "Richiesta di scambio da una richiedente",
    "admin_invitation.intro": "La biblioteca {library} chiede uno scambio con la coordinazione della rete.",
  },
  de: {
    subtitle: "Institutioneller Antrag · automatische Benachrichtigung",
    greetingNamed: "Hallo {name},",
    greeting: "Hallo,",
    footer: "Bei Fragen antworte einfach auf diese E-Mail.",
    "created.subject": "Antrag eingegangen",
    "created.intro": "Wir haben den institutionellen Antrag der Bibliothek {library} erhalten. Die Netzwerkkoordination wird ihn prüfen.",
    "in_analysis.subject": "Antrag in Prüfung",
    "in_analysis.intro": "Der Antrag der Bibliothek {library} wird von der Netzwerkkoordination geprüft.",
    "more_info.subject": "Wir benötigen ergänzende Informationen",
    "more_info.intro": "Die Koordination benötigt ergänzende Informationen zum Antrag der Bibliothek {library}. Bitte antworte auf diese E-Mail.",
    "approved.subject": "Antrag genehmigt",
    "approved.intro": "Der Antrag der Bibliothek {library} wurde genehmigt. Willkommen im Netzwerk!",
    "refused.subject": "Antrag abgelehnt",
    "refused.intro": "Der Antrag der Bibliothek {library} wurde in dieser Phase nicht angenommen.",
    "message.subject": "Neue Nachricht der Koordination",
    "message.intro": "Die Netzwerkkoordination hat eine Nachricht zum Antrag der Bibliothek {library} gesendet.",
    "invitation_proposed.subject": "Einladung zu einem Gespräch",
    "invitation_proposed.intro": "Die Koordination schlägt ein Gespräch zum Antrag der Bibliothek {library} vor.",
    "invitation_response.subject": "Antwort auf deine Einladung",
    "invitation_response.intro": "Die Koordination hat auf die Gesprächseinladung zum Antrag der Bibliothek {library} geantwortet.",
    "admin_created.subject": "Neuer institutioneller Antrag",
    "admin_created.intro": "Ein neuer institutioneller Antrag wurde registriert: {library}. Sieh im Netzwerk-Panel nach.",
    "admin_update.subject": "Aktualisierung eines institutionellen Antrags",
    "admin_update.intro": "Der Antrag der Bibliothek {library} wurde im Netzwerk-Panel aktualisiert.",
    "admin_message.subject": "Nachricht einer antragstellenden Bibliothek",
    "admin_message.intro": "Die Bibliothek {library} hat auf ihren Antrag geantwortet. Sieh im Netzwerk-Panel nach.",
    "admin_invitation.subject": "Gesprächsanfrage einer Antragstellerin",
    "admin_invitation.intro": "Die Bibliothek {library} bittet um ein Gespräch mit der Netzwerkkoordination.",
  },
  ca: {
    subtitle: "Sol·licitud institucional · notificació automàtica",
    greetingNamed: "Hola, {name}:",
    greeting: "Hola:",
    footer: "Si tens dubtes, respon a aquest correu.",
    "created.subject": "Sol·licitud rebuda",
    "created.intro": "Hem rebut la sol·licitud institucional de la biblioteca {library}. La coordinació de la xarxa l'analitzarà.",
    "in_analysis.subject": "Sol·licitud en anàlisi",
    "in_analysis.intro": "La sol·licitud de la biblioteca {library} està sent analitzada per la coordinació de la xarxa.",
    "more_info.subject": "Necessitem informació complementària",
    "more_info.intro": "La coordinació necessita informació complementària sobre la sol·licitud de la biblioteca {library}. Respon a aquest correu.",
    "approved.subject": "Sol·licitud aprovada",
    "approved.intro": "La sol·licitud de la biblioteca {library} ha estat aprovada. Benvinguda a la xarxa!",
    "refused.subject": "Sol·licitud rebutjada",
    "refused.intro": "La sol·licitud de la biblioteca {library} no ha estat acceptada en aquesta etapa.",
    "message.subject": "Nou missatge de la coordinació",
    "message.intro": "La coordinació de la xarxa ha enviat un missatge sobre la sol·licitud de la biblioteca {library}.",
    "invitation_proposed.subject": "Invitació a una conversa",
    "invitation_proposed.intro": "La coordinació proposa una conversa sobre la sol·licitud de la biblioteca {library}.",
    "invitation_response.subject": "Resposta a la teva invitació",
    "invitation_response.intro": "La coordinació ha respost a la invitació a conversar sobre la sol·licitud de la biblioteca {library}.",
    "admin_created.subject": "Nova sol·licitud institucional",
    "admin_created.intro": "S'ha registrat una nova sol·licitud institucional: {library}. Consulta el tauler de xarxa.",
    "admin_update.subject": "Actualització d'una sol·licitud institucional",
    "admin_update.intro": "La sol·licitud de la biblioteca {library} s'ha actualitzat al tauler de xarxa.",
    "admin_message.subject": "Missatge d'una biblioteca sol·licitant",
    "admin_message.intro": "La biblioteca {library} ha respost a la seva sol·licitud. Consulta el tauler de xarxa.",
    "admin_invitation.subject": "Petició de conversa d'una sol·licitant",
    "admin_invitation.intro": "La biblioteca {library} demana una conversa amb la coordinació de la xarxa.",
  },
  eo: {
    subtitle: "Institucia peto · aŭtomata sciigo",
    greetingNamed: "Saluton, {name}!",
    greeting: "Saluton!",
    footer: "Se vi havas dubon, respondu al ĉi tiu retmesaĝo.",
    "created.subject": "Peto ricevita",
    "created.intro": "Ni ricevis la institucian peton de la biblioteko {library}. La reta kunordigado pritaksos ĝin.",
    "in_analysis.subject": "Peto pritaksata",
    "in_analysis.intro": "La peto de la biblioteko {library} estas pritaksata de la reta kunordigado.",
    "more_info.subject": "Ni bezonas pliajn informojn",
    "more_info.intro": "La kunordigado bezonas pliajn informojn pri la peto de la biblioteko {library}. Bonvolu respondi al ĉi tiu retmesaĝo.",
    "approved.subject": "Peto aprobita",
    "approved.intro": "La peto de la biblioteko {library} estis aprobita. Bonvenon en la reto!",
    "refused.subject": "Peto rifuzita",
    "refused.intro": "La peto de la biblioteko {library} ne estis akceptita en ĉi tiu etapo.",
    "message.subject": "Nova mesaĝo de la kunordigado",
    "message.intro": "La reta kunordigado sendis mesaĝon pri la peto de la biblioteko {library}.",
    "invitation_proposed.subject": "Invito al interparolo",
    "invitation_proposed.intro": "La kunordigado proponas interparolon pri la peto de la biblioteko {library}.",
    "invitation_response.subject": "Respondo al via invito",
    "invitation_response.intro": "La kunordigado respondis al la invito interparoli pri la peto de la biblioteko {library}.",
    "admin_created.subject": "Nova institucia peto",
    "admin_created.intro": "Nova institucia peto estis registrita: {library}. Konsultu la retan panelon.",
    "admin_update.subject": "Ĝisdatigo de institucia peto",
    "admin_update.intro": "La peto de la biblioteko {library} estis ĝisdatigita en la reta panelo.",
    "admin_message.subject": "Mesaĝo de petanta biblioteko",
    "admin_message.intro": "La biblioteko {library} respondis pri sia peto. Konsultu la retan panelon.",
    "admin_invitation.subject": "Peto de interparolo de petanto",
    "admin_invitation.intro": "La biblioteko {library} petas interparolon kun la reta kunordigado.",
  },
  nl: {
    subtitle: "Institutionele aanvraag · automatische melding",
    greetingNamed: "Hallo {name},",
    greeting: "Hallo,",
    footer: "Bij twijfel kun je gewoon op deze e-mail antwoorden.",
    "created.subject": "Aanvraag ontvangen",
    "created.intro": "We hebben de institutionele aanvraag van bibliotheek {library} ontvangen. De netwerkcoördinatie zal ze bekijken.",
    "in_analysis.subject": "Aanvraag in behandeling",
    "in_analysis.intro": "De aanvraag van bibliotheek {library} wordt beoordeeld door de netwerkcoördinatie.",
    "more_info.subject": "We hebben aanvullende informatie nodig",
    "more_info.intro": "De coördinatie heeft aanvullende informatie nodig over de aanvraag van bibliotheek {library}. Antwoord op deze e-mail.",
    "approved.subject": "Aanvraag goedgekeurd",
    "approved.intro": "De aanvraag van bibliotheek {library} is goedgekeurd. Welkom in het netwerk!",
    "refused.subject": "Aanvraag afgewezen",
    "refused.intro": "De aanvraag van bibliotheek {library} is in dit stadium niet aanvaard.",
    "message.subject": "Nieuw bericht van de coördinatie",
    "message.intro": "De netwerkcoördinatie heeft een bericht gestuurd over de aanvraag van bibliotheek {library}.",
    "invitation_proposed.subject": "Uitnodiging voor een gesprek",
    "invitation_proposed.intro": "De coördinatie stelt een gesprek voor over de aanvraag van bibliotheek {library}.",
    "invitation_response.subject": "Antwoord op je uitnodiging",
    "invitation_response.intro": "De coördinatie heeft geantwoord op de uitnodiging om te praten over de aanvraag van bibliotheek {library}.",
    "admin_created.subject": "Nieuwe institutionele aanvraag",
    "admin_created.intro": "Er is een nieuwe institutionele aanvraag geregistreerd: {library}. Bekijk het netwerkpaneel.",
    "admin_update.subject": "Bijwerking van een institutionele aanvraag",
    "admin_update.intro": "De aanvraag van bibliotheek {library} is bijgewerkt in het netwerkpaneel.",
    "admin_message.subject": "Bericht van een aanvragende bibliotheek",
    "admin_message.intro": "Bibliotheek {library} heeft op haar aanvraag geantwoord. Bekijk het netwerkpaneel.",
    "admin_invitation.subject": "Gespreksverzoek van een aanvrager",
    "admin_invitation.intro": "Bibliotheek {library} vraagt een gesprek met de netwerkcoördinatie.",
  },
  el: {
    subtitle: "Θεσμικό αίτημα · αυτόματη ειδοποίηση",
    greetingNamed: "Γεια σου {name},",
    greeting: "Γεια σου,",
    footer: "Αν έχεις απορίες, απάντησε σε αυτό το email.",
    "created.subject": "Το αίτημα ελήφθη",
    "created.intro": "Λάβαμε το θεσμικό αίτημα της βιβλιοθήκης {library}. Ο συντονισμός του δικτύου θα το εξετάσει.",
    "in_analysis.subject": "Αίτημα υπό εξέταση",
    "in_analysis.intro": "Το αίτημα της βιβλιοθήκης {library} εξετάζεται από τον συντονισμό του δικτύου.",
    "more_info.subject": "Χρειαζόμαστε συμπληρωματικές πληροφορίες",
    "more_info.intro": "Ο συντονισμός χρειάζεται συμπληρωματικές πληροφορίες για το αίτημα της βιβλιοθήκης {library}. Απάντησε σε αυτό το email.",
    "approved.subject": "Το αίτημα εγκρίθηκε",
    "approved.intro": "Το αίτημα της βιβλιοθήκης {library} εγκρίθηκε. Καλώς ήρθες στο δίκτυο!",
    "refused.subject": "Το αίτημα απορρίφθηκε",
    "refused.intro": "Το αίτημα της βιβλιοθήκης {library} δεν έγινε δεκτό σε αυτό το στάδιο.",
    "message.subject": "Νέο μήνυμα από τον συντονισμό",
    "message.intro": "Ο συντονισμός του δικτύου έστειλε μήνυμα σχετικά με το αίτημα της βιβλιοθήκης {library}.",
    "invitation_proposed.subject": "Πρόσκληση για συνομιλία",
    "invitation_proposed.intro": "Ο συντονισμός προτείνει μια συνομιλία σχετικά με το αίτημα της βιβλιοθήκης {library}.",
    "invitation_response.subject": "Απάντηση στην πρόσκλησή σου",
    "invitation_response.intro": "Ο συντονισμός απάντησε στην πρόσκληση για συνομιλία σχετικά με το αίτημα της βιβλιοθήκης {library}.",
    "admin_created.subject": "Νέο θεσμικό αίτημα",
    "admin_created.intro": "Καταχωρήθηκε νέο θεσμικό αίτημα: {library}. Δες τον πίνακα δικτύου.",
    "admin_update.subject": "Ενημέρωση θεσμικού αιτήματος",
    "admin_update.intro": "Το αίτημα της βιβλιοθήκης {library} ενημερώθηκε στον πίνακα δικτύου.",
    "admin_message.subject": "Μήνυμα από αιτούσα βιβλιοθήκη",
    "admin_message.intro": "Η βιβλιοθήκη {library} απάντησε στο αίτημά της. Δες τον πίνακα δικτύου.",
    "admin_invitation.subject": "Αίτημα συνομιλίας από αιτούσα",
    "admin_invitation.intro": "Η βιβλιοθήκη {library} ζητά συνομιλία με τον συντονισμό του δικτύου.",
  },
};

// Résout la chaîne pour une locale (fallback pt-BR), avec interpolation {var}.
export function tr(locale: string, key: string, vars: Record<string, string> = {}): string {
  const table = STRINGS[locale] || STRINGS[FALLBACK_LOCALE];
  let s = table[key] ?? STRINGS[FALLBACK_LOCALE][key] ?? key;
  for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, v);
  return s;
}

// Normalise une langue de profil (ex. 'pt-BR', 'fr', 'en-US') vers une locale connue.
export function normalizeLocale(lang: string | null | undefined): string {
  const l = String(lang || "").trim();
  if (!l) return FALLBACK_LOCALE;
  if (STRINGS[l]) return l;
  const base = l.split("-")[0];
  if (STRINGS[base]) return base;
  return FALLBACK_LOCALE;
}
