// strings.ts — chaînes localisées du récapitulatif hebdomadaire des actions
// inter-bibliothèques.
//
// Ce n'est pas une notification de service : c'est un instrument de
// TRANSPARENCE. Les administrateur·rices réseau disposent de droits élevés sur
// toutes les bibliothèques ; ce récapitulatif fait que ce pouvoir ne s'exerce
// pas en silence. Le ton doit donc être factuel et sans dramatisation — on
// rend compte, on n'accuse pas.
//
// Deux destinataires, deux cadrages :
//   * coordination d'une bibliothèque → « voici ce qui a été fait chez vous » ;
//   * administration réseau → « voici ce que le réseau a fait cette semaine ».
//
// Placeholders : {library}, {start}, {end}, {count}. Repli : pt-BR.

export const FALLBACK_LOCALE = "pt-BR";

export const STRINGS: Record<string, Record<string, string>> = {
  "pt-BR": {
    subtitle: "Transparência da rede · resumo automático",
    greeting: "Olá!",
    footer: "Este resumo é enviado toda semana para que nenhuma ação da rede passe despercebida. Em caso de dúvida, responde a este e-mail.",
    "library.subject": "Ações da rede na biblioteca {library} ({start} a {end})",
    "library.title": "O que a rede fez na sua biblioteca",
    "library.intro": "Entre {start} e {end}, {count} ação(ões) foram realizadas na biblioteca {library} por pessoas da administração da rede. Segue o detalhe, para conhecimento.",
    "network.subject": "Ações inter-bibliotecas da semana ({start} a {end})",
    "network.title": "Ações inter-bibliotecas da semana",
    "network.intro": "Entre {start} e {end}, {count} ação(ões) foram realizadas por pessoas da administração da rede em bibliotecas das quais elas não fazem parte.",
    "col.when": "Quando",
    "col.who": "Quem",
    "col.what": "Ação",
    "col.where": "Biblioteca",
    "col.target": "Objeto",
    critical: "crítica",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Promoção ao papel de coordenação",
    "action.team_promote_to_librarian": "Promoção ao papel de bibliotecária·o",
    "action.team_request_remove_member": "Pedido de retirada de uma pessoa da equipe",
    "action.team_suspend_member": "Suspensão de uma pessoa da equipe",
    "action.update_library": "Alteração da ficha da biblioteca",
    "action.update_library_membership_rules": "Alteração das regras de adesão",
    "action.update_library_retention_policies": "Alteração dos prazos de conservação",
    "action.update_library_service_state": "Alteração do estado de serviço",
    "target.library": "Biblioteca",
    "target.library_membership_rule": "Regra de adesão",
    "target.library_retention_policy": "Prazo de conservação",
    "target.library_service_state": "Estado de serviço",
    "target.library_team_invitation": "Convite para a equipe",
    "target.user_library_membership": "Vínculo de uma pessoa com a biblioteca",
    "stage.proposed": "proposta, {count} ratificação(ões) necessária(s) — nada feito ainda",
    "stage.proposed.sansCompte": "proposta — nada feito ainda",
    "action.reassign_book_to_library": "Reatribuição de uma obra a esta biblioteca",
    "action.reassign_book_from_to_library": "Transferência de uma obra de outra biblioteca para esta",
    "target.book": "Obra",
  },
  fr: {
    subtitle: "Transparence du réseau · récapitulatif automatique",
    greeting: "Salut !",
    footer: "Ce récapitulatif est envoyé chaque semaine pour qu'aucune action du réseau ne passe inaperçue. Une question ? Réponds à ce message.",
    "library.subject": "Actions du réseau dans la bibliothèque {library} (du {start} au {end})",
    "library.title": "Ce que le réseau a fait dans votre bibliothèque",
    "library.intro": "Entre le {start} et le {end}, {count} action(s) ont été menées dans la bibliothèque {library} par des personnes de l'administration du réseau. Voici le détail, pour information.",
    "network.subject": "Actions inter-bibliothèques de la semaine (du {start} au {end})",
    "network.title": "Actions inter-bibliothèques de la semaine",
    "network.intro": "Entre le {start} et le {end}, {count} action(s) ont été menées par des personnes de l'administration du réseau dans des bibliothèques dont elles ne font pas partie.",
    "col.when": "Quand",
    "col.who": "Qui",
    "col.what": "Action",
    "col.where": "Bibliothèque",
    "col.target": "Objet",
    critical: "critique",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Passage au rôle de coordination",
    "action.team_promote_to_librarian": "Passage au rôle de bibliothécaire",
    "action.team_request_remove_member": "Demande de retrait d'une personne de l'équipe",
    "action.team_suspend_member": "Suspension d'une personne de l'équipe",
    "action.update_library": "Modification de la fiche de la bibliothèque",
    "action.update_library_membership_rules": "Modification des règles d'adhésion",
    "action.update_library_retention_policies": "Modification des durées de conservation",
    "action.update_library_service_state": "Modification de l'état de service",
    "target.library": "Bibliothèque",
    "target.library_membership_rule": "Règle d'adhésion",
    "target.library_retention_policy": "Durée de conservation",
    "target.library_service_state": "État de service",
    "target.library_team_invitation": "Invitation dans l'équipe",
    "target.user_library_membership": "Rattachement d'une personne à la bibliothèque",
    "stage.proposed": "proposition, {count} ratification(s) requise(s) — rien n'est encore fait",
    "stage.proposed.sansCompte": "proposition — rien n'est encore fait",
    "action.reassign_book_to_library": "Réattribution d'un ouvrage à cette bibliothèque",
    "action.reassign_book_from_to_library": "Transfert d'un ouvrage d'une autre bibliothèque vers celle-ci",
    "target.book": "Ouvrage",
  },
  es: {
    subtitle: "Transparencia de la red · resumen automático",
    greeting: "¡Hola!",
    footer: "Este resumen se envía cada semana para que ninguna acción de la red pase desapercibida. ¿Alguna duda? Responde a este mensaje.",
    "library.subject": "Acciones de la red en la biblioteca {library} (del {start} al {end})",
    "library.title": "Lo que la red hizo en tu biblioteca",
    "library.intro": "Entre el {start} y el {end}, se realizaron {count} acción(es) en la biblioteca {library} por parte de personas de la administración de la red. Aquí está el detalle, para tu información.",
    "network.subject": "Acciones entre bibliotecas de la semana (del {start} al {end})",
    "network.title": "Acciones entre bibliotecas de la semana",
    "network.intro": "Entre el {start} y el {end}, se realizaron {count} acción(es) por parte de personas de la administración de la red en bibliotecas de las que no forman parte.",
    "col.when": "Cuándo",
    "col.who": "Quién",
    "col.what": "Acción",
    "col.where": "Biblioteca",
    "col.target": "Objeto",
    critical: "crítica",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Paso al rol de coordinación",
    "action.team_promote_to_librarian": "Paso al rol de bibliotecaria·o",
    "action.team_request_remove_member": "Solicitud de retirada de una persona del equipo",
    "action.team_suspend_member": "Suspensión de una persona del equipo",
    "action.update_library": "Modificación de la ficha de la biblioteca",
    "action.update_library_membership_rules": "Modificación de las reglas de adhesión",
    "action.update_library_retention_policies": "Modificación de los plazos de conservación",
    "action.update_library_service_state": "Modificación del estado de servicio",
    "target.library": "Biblioteca",
    "target.library_membership_rule": "Regla de adhesión",
    "target.library_retention_policy": "Plazo de conservación",
    "target.library_service_state": "Estado de servicio",
    "target.library_team_invitation": "Invitación al equipo",
    "target.user_library_membership": "Vínculo de una persona con la biblioteca",
    "stage.proposed": "propuesta, {count} ratificación(es) necesaria(s) — nada hecho todavía",
    "stage.proposed.sansCompte": "propuesta — nada hecho todavía",
    "action.reassign_book_to_library": "Reasignación de una obra a esta biblioteca",
    "action.reassign_book_from_to_library": "Traslado de una obra de otra biblioteca a esta",
    "target.book": "Obra",
  },
  en: {
    subtitle: "Network transparency · automatic summary",
    greeting: "Hello!",
    footer: "This summary is sent every week so that no network action goes unnoticed. Any questions? Just reply to this message.",
    "library.subject": "Network actions in the {library} library ({start} to {end})",
    "library.title": "What the network did in your library",
    "library.intro": "Between {start} and {end}, {count} action(s) were carried out in the {library} library by people from the network administration. Here is the detail, for your information.",
    "network.subject": "Cross-library actions this week ({start} to {end})",
    "network.title": "Cross-library actions this week",
    "network.intro": "Between {start} and {end}, {count} action(s) were carried out by people from the network administration in libraries they are not part of.",
    "col.when": "When",
    "col.who": "Who",
    "col.what": "Action",
    "col.where": "Library",
    "col.target": "Object",
    critical: "critical",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Moved to the coordination role",
    "action.team_promote_to_librarian": "Moved to the librarian role",
    "action.team_request_remove_member": "Request to remove someone from the team",
    "action.team_suspend_member": "Suspension of someone in the team",
    "action.update_library": "Change to the library's record",
    "action.update_library_membership_rules": "Change to the membership rules",
    "action.update_library_retention_policies": "Change to the retention periods",
    "action.update_library_service_state": "Change to the service state",
    "target.library": "Library",
    "target.library_membership_rule": "Membership rule",
    "target.library_retention_policy": "Retention period",
    "target.library_service_state": "Service state",
    "target.library_team_invitation": "Team invitation",
    "target.user_library_membership": "Someone's attachment to the library",
    "stage.proposed": "proposal, {count} ratification(s) required — nothing done yet",
    "stage.proposed.sansCompte": "proposal — nothing done yet",
    "action.reassign_book_to_library": "Reassignment of a work to this library",
    "action.reassign_book_from_to_library": "Transfer of a work from another library to this one",
    "target.book": "Work",
  },
  it: {
    subtitle: "Trasparenza della rete · riepilogo automatico",
    greeting: "Ciao!",
    footer: "Questo riepilogo è inviato ogni settimana perché nessuna azione della rete passi inosservata. Domande? Rispondi a questo messaggio.",
    "library.subject": "Azioni della rete nella biblioteca {library} (dal {start} al {end})",
    "library.title": "Ciò che la rete ha fatto nella vostra biblioteca",
    "library.intro": "Tra il {start} e il {end}, {count} azione/i sono state svolte nella biblioteca {library} da persone dell'amministrazione della rete. Ecco il dettaglio, per conoscenza.",
    "network.subject": "Azioni fra biblioteche della settimana (dal {start} al {end})",
    "network.title": "Azioni fra biblioteche della settimana",
    "network.intro": "Tra il {start} e il {end}, {count} azione/i sono state svolte da persone dell'amministrazione della rete in biblioteche di cui non fanno parte.",
    "col.when": "Quando",
    "col.who": "Chi",
    "col.what": "Azione",
    "col.where": "Biblioteca",
    "col.target": "Oggetto",
    critical: "critica",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Passaggio al ruolo di coordinamento",
    "action.team_promote_to_librarian": "Passaggio al ruolo di bibliotecaria·o",
    "action.team_request_remove_member": "Richiesta di rimozione di una persona dal gruppo",
    "action.team_suspend_member": "Sospensione di una persona del gruppo",
    "action.update_library": "Modifica della scheda della biblioteca",
    "action.update_library_membership_rules": "Modifica delle regole di adesione",
    "action.update_library_retention_policies": "Modifica dei termini di conservazione",
    "action.update_library_service_state": "Modifica dello stato di servizio",
    "target.library": "Biblioteca",
    "target.library_membership_rule": "Regola di adesione",
    "target.library_retention_policy": "Termine di conservazione",
    "target.library_service_state": "Stato di servizio",
    "target.library_team_invitation": "Invito nel gruppo",
    "target.user_library_membership": "Legame di una persona con la biblioteca",
    "stage.proposed": "proposta, {count} ratifica/he necessaria/e — nulla è ancora fatto",
    "stage.proposed.sansCompte": "proposta — nulla è ancora fatto",
    "action.reassign_book_to_library": "Riassegnazione di un'opera a questa biblioteca",
    "action.reassign_book_from_to_library": "Trasferimento di un'opera da un'altra biblioteca a questa",
    "target.book": "Opera",
  },
  de: {
    subtitle: "Transparenz des Netzwerks · automatische Zusammenfassung",
    greeting: "Hallo!",
    footer: "Diese Zusammenfassung wird wöchentlich verschickt, damit keine Handlung des Netzwerks unbemerkt bleibt. Fragen? Antworte einfach auf diese Nachricht.",
    "library.subject": "Handlungen des Netzwerks in der Bibliothek {library} ({start} bis {end})",
    "library.title": "Was das Netzwerk in eurer Bibliothek getan hat",
    "library.intro": "Zwischen {start} und {end} wurden {count} Handlung(en) in der Bibliothek {library} von Personen der Netzwerkverwaltung durchgeführt. Hier die Einzelheiten, zur Kenntnisnahme.",
    "network.subject": "Bibliotheksübergreifende Handlungen der Woche ({start} bis {end})",
    "network.title": "Bibliotheksübergreifende Handlungen der Woche",
    "network.intro": "Zwischen {start} und {end} wurden {count} Handlung(en) von Personen der Netzwerkverwaltung in Bibliotheken durchgeführt, denen sie nicht angehören.",
    "col.when": "Wann",
    "col.who": "Wer",
    "col.what": "Handlung",
    "col.where": "Bibliothek",
    "col.target": "Gegenstand",
    critical: "kritisch",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Wechsel in die Koordinationsrolle",
    "action.team_promote_to_librarian": "Wechsel in die Bibliothekar·innenrolle",
    "action.team_request_remove_member": "Antrag auf Entfernung einer Person aus dem Team",
    "action.team_suspend_member": "Aussetzung einer Person im Team",
    "action.update_library": "Änderung am Eintrag der Bibliothek",
    "action.update_library_membership_rules": "Änderung der Beitrittsregeln",
    "action.update_library_retention_policies": "Änderung der Aufbewahrungsfristen",
    "action.update_library_service_state": "Änderung des Betriebszustands",
    "target.library": "Bibliothek",
    "target.library_membership_rule": "Beitrittsregel",
    "target.library_retention_policy": "Aufbewahrungsfrist",
    "target.library_service_state": "Betriebszustand",
    "target.library_team_invitation": "Einladung ins Team",
    "target.user_library_membership": "Zugehörigkeit einer Person zur Bibliothek",
    "stage.proposed": "Vorschlag, {count} Bestätigung(en) nötig — noch nichts geschehen",
    "stage.proposed.sansCompte": "Vorschlag — noch nichts geschehen",
    "action.reassign_book_to_library": "Zuordnung eines Werks zu dieser Bibliothek",
    "action.reassign_book_from_to_library": "Übertragung eines Werks aus einer anderen Bibliothek hierher",
    "target.book": "Werk",
  },
  ca: {
    subtitle: "Transparència de la xarxa · resum automàtic",
    greeting: "Hola!",
    footer: "Aquest resum s'envia cada setmana perquè cap acció de la xarxa passi desapercebuda. Cap dubte? Respon a aquest missatge.",
    "library.subject": "Accions de la xarxa a la biblioteca {library} (del {start} al {end})",
    "library.title": "El que la xarxa ha fet a la vostra biblioteca",
    "library.intro": "Entre el {start} i el {end}, s'han dut a terme {count} acció(ns) a la biblioteca {library} per part de persones de l'administració de la xarxa. Aquí teniu el detall, a títol informatiu.",
    "network.subject": "Accions entre biblioteques de la setmana (del {start} al {end})",
    "network.title": "Accions entre biblioteques de la setmana",
    "network.intro": "Entre el {start} i el {end}, s'han dut a terme {count} acció(ns) per part de persones de l'administració de la xarxa en biblioteques de les quals no formen part.",
    "col.when": "Quan",
    "col.who": "Qui",
    "col.what": "Acció",
    "col.where": "Biblioteca",
    "col.target": "Objecte",
    critical: "crítica",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Pas al rol de coordinació",
    "action.team_promote_to_librarian": "Pas al rol de bibliotecària·ari",
    "action.team_request_remove_member": "Petició de retirada d'una persona de l'equip",
    "action.team_suspend_member": "Suspensió d'una persona de l'equip",
    "action.update_library": "Modificació de la fitxa de la biblioteca",
    "action.update_library_membership_rules": "Modificació de les regles d'adhesió",
    "action.update_library_retention_policies": "Modificació dels terminis de conservació",
    "action.update_library_service_state": "Modificació de l'estat de servei",
    "target.library": "Biblioteca",
    "target.library_membership_rule": "Regla d'adhesió",
    "target.library_retention_policy": "Termini de conservació",
    "target.library_service_state": "Estat de servei",
    "target.library_team_invitation": "Invitació a l'equip",
    "target.user_library_membership": "Vincle d'una persona amb la biblioteca",
    "stage.proposed": "proposta, {count} ratificació(ns) necessària(es) — encara no s'ha fet res",
    "stage.proposed.sansCompte": "proposta — encara no s'ha fet res",
    "action.reassign_book_to_library": "Reassignació d'una obra a aquesta biblioteca",
    "action.reassign_book_from_to_library": "Trasllat d'una obra d'una altra biblioteca cap a aquesta",
    "target.book": "Obra",
  },
  eo: {
    subtitle: "Travidebleco de la reto · aŭtomata resumo",
    greeting: "Saluton!",
    footer: "Ĉi tiu resumo estas sendata ĉiusemajne por ke neniu ago de la reto pasu nerimarkite. Demando? Respondu al ĉi tiu mesaĝo.",
    "library.subject": "Agoj de la reto en la biblioteko {library} (de {start} ĝis {end})",
    "library.title": "Kion la reto faris en via biblioteko",
    "library.intro": "Inter {start} kaj {end}, {count} ago(j) estis faritaj en la biblioteko {library} de personoj de la reta administrado. Jen la detalo, por scio.",
    "network.subject": "Interbibliotekaj agoj de la semajno (de {start} ĝis {end})",
    "network.title": "Interbibliotekaj agoj de la semajno",
    "network.intro": "Inter {start} kaj {end}, {count} ago(j) estis faritaj de personoj de la reta administrado en bibliotekoj al kiuj ili ne apartenas.",
    "col.when": "Kiam",
    "col.who": "Kiu",
    "col.what": "Ago",
    "col.where": "Biblioteko",
    "col.target": "Objekto",
    critical: "kritika",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Transiro al la kunordiga rolo",
    "action.team_promote_to_librarian": "Transiro al la bibliotekista rolo",
    "action.team_request_remove_member": "Peto forigi personon el la teamo",
    "action.team_suspend_member": "Suspendo de persono en la teamo",
    "action.update_library": "Ŝanĝo de la biblioteka slipo",
    "action.update_library_membership_rules": "Ŝanĝo de la aliĝreguloj",
    "action.update_library_retention_policies": "Ŝanĝo de la konservaj daŭroj",
    "action.update_library_service_state": "Ŝanĝo de la serva stato",
    "target.library": "Biblioteko",
    "target.library_membership_rule": "Aliĝregulo",
    "target.library_retention_policy": "Konserva daŭro",
    "target.library_service_state": "Serva stato",
    "target.library_team_invitation": "Invito en la teamon",
    "target.user_library_membership": "Ligo de persono al la biblioteko",
    "stage.proposed": "propono, {count} ratifiko(j) necesa(j) — nenio ankoraŭ farita",
    "stage.proposed.sansCompte": "propono — nenio ankoraŭ farita",
    "action.reassign_book_to_library": "Reasigno de verko al ĉi tiu biblioteko",
    "action.reassign_book_from_to_library": "Translokigo de verko el alia biblioteko al ĉi tiu",
    "target.book": "Verko",
  },
  nl: {
    subtitle: "Transparantie van het netwerk · automatische samenvatting",
    greeting: "Hallo!",
    footer: "Deze samenvatting wordt elke week verstuurd zodat geen enkele actie van het netwerk onopgemerkt blijft. Vragen? Antwoord gewoon op dit bericht.",
    "library.subject": "Acties van het netwerk in bibliotheek {library} ({start} tot {end})",
    "library.title": "Wat het netwerk in jullie bibliotheek heeft gedaan",
    "library.intro": "Tussen {start} en {end} zijn er {count} actie(s) uitgevoerd in bibliotheek {library} door mensen van het netwerkbeheer. Hier zijn de details, ter informatie.",
    "network.subject": "Acties tussen bibliotheken van de week ({start} tot {end})",
    "network.title": "Acties tussen bibliotheken van de week",
    "network.intro": "Tussen {start} en {end} zijn er {count} actie(s) uitgevoerd door mensen van het netwerkbeheer in bibliotheken waar zij geen deel van uitmaken.",
    "col.when": "Wanneer",
    "col.who": "Wie",
    "col.what": "Actie",
    "col.where": "Bibliotheek",
    "col.target": "Voorwerp",
    critical: "kritiek",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Overgang naar de coördinatierol",
    "action.team_promote_to_librarian": "Overgang naar de bibliothecarisrol",
    "action.team_request_remove_member": "Verzoek om iemand uit het team te verwijderen",
    "action.team_suspend_member": "Schorsing van iemand in het team",
    "action.update_library": "Wijziging van de fiche van de bibliotheek",
    "action.update_library_membership_rules": "Wijziging van de toetredingsregels",
    "action.update_library_retention_policies": "Wijziging van de bewaartermijnen",
    "action.update_library_service_state": "Wijziging van de dienstverleningsstatus",
    "target.library": "Bibliotheek",
    "target.library_membership_rule": "Toetredingsregel",
    "target.library_retention_policy": "Bewaartermijn",
    "target.library_service_state": "Dienstverleningsstatus",
    "target.library_team_invitation": "Uitnodiging voor het team",
    "target.user_library_membership": "Band van iemand met de bibliotheek",
    "stage.proposed": "voorstel, {count} bekrachtiging(en) nodig — nog niets gebeurd",
    "stage.proposed.sansCompte": "voorstel — nog niets gebeurd",
    "action.reassign_book_to_library": "Toewijzing van een werk aan deze bibliotheek",
    "action.reassign_book_from_to_library": "Overdracht van een werk van een andere bibliotheek naar deze",
    "target.book": "Werk",
  },
  el: {
    subtitle: "Διαφάνεια του δικτύου · αυτόματη σύνοψη",
    greeting: "Γεια σου!",
    footer: "Αυτή η σύνοψη στέλνεται κάθε εβδομάδα ώστε καμία ενέργεια του δικτύου να μην περνά απαρατήρητη. Απορίες; Απάντησε σε αυτό το μήνυμα.",
    "library.subject": "Ενέργειες του δικτύου στη βιβλιοθήκη {library} ({start} έως {end})",
    "library.title": "Τι έκανε το δίκτυο στη βιβλιοθήκη σας",
    "library.intro": "Μεταξύ {start} και {end}, πραγματοποιήθηκαν {count} ενέργεια/ες στη βιβλιοθήκη {library} από άτομα της διοίκησης του δικτύου. Ακολουθεί η λεπτομέρεια, προς ενημέρωση.",
    "network.subject": "Διαβιβλιοθηκονομικές ενέργειες της εβδομάδας ({start} έως {end})",
    "network.title": "Διαβιβλιοθηκονομικές ενέργειες της εβδομάδας",
    "network.intro": "Μεταξύ {start} και {end}, πραγματοποιήθηκαν {count} ενέργεια/ες από άτομα της διοίκησης του δικτύου σε βιβλιοθήκες στις οποίες δεν ανήκουν.",
    "col.when": "Πότε",
    "col.who": "Ποιος/α",
    "col.what": "Ενέργεια",
    "col.where": "Βιβλιοθήκη",
    "col.target": "Αντικείμενο",
    critical: "κρίσιμη",
    // Libellés humains des actions et des objets, ajoutés le 31/08/2026 :
    // le récapitulatif affichait les identifiants de code tels quels.
    "action.team_promote_to_coordenador": "Μετάβαση στον ρόλο του συντονισμού",
    "action.team_promote_to_librarian": "Μετάβαση στον ρόλο της βιβλιοθηκονόμου",
    "action.team_request_remove_member": "Αίτημα απομάκρυνσης ατόμου από την ομάδα",
    "action.team_suspend_member": "Αναστολή ατόμου της ομάδας",
    "action.update_library": "Τροποποίηση της καρτέλας της βιβλιοθήκης",
    "action.update_library_membership_rules": "Τροποποίηση των κανόνων ένταξης",
    "action.update_library_retention_policies": "Τροποποίηση των χρόνων διατήρησης",
    "action.update_library_service_state": "Τροποποίηση της κατάστασης λειτουργίας",
    "target.library": "Βιβλιοθήκη",
    "target.library_membership_rule": "Κανόνας ένταξης",
    "target.library_retention_policy": "Χρόνος διατήρησης",
    "target.library_service_state": "Κατάσταση λειτουργίας",
    "target.library_team_invitation": "Πρόσκληση στην ομάδα",
    "target.user_library_membership": "Σύνδεση ατόμου με τη βιβλιοθήκη",
    "stage.proposed": "πρόταση, {count} επικύρωση(εις) απαιτούνται — τίποτα δεν έγινε ακόμη",
    "stage.proposed.sansCompte": "πρόταση — τίποτα δεν έγινε ακόμη",
    "action.reassign_book_to_library": "Ανακατανομή έργου σε αυτή τη βιβλιοθήκη",
    "action.reassign_book_from_to_library": "Μεταφορά έργου από άλλη βιβλιοθήκη σε αυτή",
    "target.book": "Έργο",
  },
};

export function tr(locale: string, key: string, vars: Record<string, string> = {}): string {
  const table = STRINGS[locale] || STRINGS[FALLBACK_LOCALE];
  let s = table[key] ?? STRINGS[FALLBACK_LOCALE][key] ?? key;
  for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, v);
  return s;
}

export function normalizeLocale(lang: string | null | undefined): string {
  const l = String(lang || "").trim();
  if (!l) return FALLBACK_LOCALE;
  if (STRINGS[l]) return l;
  const base = l.split("-")[0];
  if (STRINGS[base]) return base;
  return FALLBACK_LOCALE;
}
