import type { NotifyPayload } from "../core/types.ts";
import { getPayloadValue } from "./payload.ts";
const WF_LABELS:Record<string,string>={solicitada:"Reserva recebida",em_preparacao:"Livro em preparação",retirada_a_combinar:"Retirada a combinar",retirada_agendada:"Retirada agendada","re-retirada_agendada":"Retirada reagendada",pronta_para_retirada:"Livro pronto para retirada",retirada_efetivada:"Retirada efetuada",cancelada_leitor:"Cancelada pelo leitor",cancelada_biblioteca:"Cancelada pela biblioteca",nao_retirada:"Retirada não realizada",liberada_para_circulacao:"Item devolvido à circulação",expirada:"Reserva expirada"};
export function workflowStageLabel(s:unknown) { const v=String(s||"").trim(); return WF_LABELS[v]||v; }
export function pickupReplyLabel(s:unknown) { const v=String(s||"").trim(); if (v==="confirmado_leitor") return "Horário confirmado pelo leitor"; if (v==="recusado_leitor") return "Leitor não pode nesse horário"; return ""; }
const WE_MAP:Record<string,string>={reserva_retirada_a_combinar:"retirada_a_combinar",retirada_a_combinar:"retirada_a_combinar",reserva_retirada_agendada:"retirada_agendada",retirada_agendada:"retirada_agendada",reserva_retirada_reagendada:"retirada_reagendada",retirada_reagendada:"retirada_reagendada",reserva_pronta_para_retirada:"pronta_para_retirada",pronta_para_retirada:"pronta_para_retirada",reserva_nao_retirada:"retirada_no_show",retirada_nao_realizada:"retirada_no_show",retirada_no_show:"retirada_no_show",reserva_liberada_para_circulacao:"liberada_para_circulacao",liberada_para_circulacao:"liberada_para_circulacao"};
export function normalizeReservaWorkflowEvent(e:unknown) { return WE_MAP[String(e||"").trim()]||""; }
export function normalizeReservaPickupReplyEvent(e:unknown) { const s=String(e||"").trim(); if (s==="reserva_leitor_confirma_horario"||s==="retirada_confirmada_leitor") return "retirada_confirmada_leitor"; if (s==="reserva_leitor_recusa_horario"||s==="retirada_recusada_leitor") return "retirada_recusada_leitor"; return ""; }
const SC_MAP:Record<string,string>={reserva_v2_cancelada_staff:"reserva_cancelada_biblioteca",reserva_cancelada_biblioteca:"reserva_cancelada_biblioteca",reserva_v2_cancelada_reader:"reserva_cancelada_leitor",reserva_cancelada_leitor:"reserva_cancelada_leitor",reserva_expirada:"reserva_expirada",expirada:"reserva_expirada",reserva_convertida_em_emprestimo:"reserva_convertida_em_emprestimo",convertida_em_emprestimo:"reserva_convertida_em_emprestimo"};
export function normalizeReservaStatusChangeEvent(e:unknown) { return SC_MAP[String(e||"").trim()]||String(e||"").trim(); }
const SF_MAP:Record<string,string>={retirada_a_combinar:"retirada_a_combinar",retirada_agendada:"retirada_agendada",retirada_reagendada:"re-retirada_agendada",pronta_para_retirada:"pronta_para_retirada",retirada_no_show:"nao_retirada",liberada_para_circulacao:"liberada_para_circulacao"};
export function workflowStageFromEvent(e:string) { return SF_MAP[normalizeReservaWorkflowEvent(e)]||""; }
export function actorRoleFromPayload(p?:NotifyPayload|null) { const r=String(getPayloadValue(p,"actor_role")||p?.actor_role||"").trim().toLowerCase(); if (["biblioteca","staff","librarian","admin"].includes(r)) return "biblioteca" as const; if (["leitor","reader","usuario","usuário","user"].includes(r)) return "leitor" as const; return null; }
export function actionKindFromPayload(p?:NotifyPayload|null) { const r=String(getPayloadValue(p,"action_kind")||"").trim().toLowerCase(); if (r==="reagendamento") return "reagendamento" as const; if (r==="agendamento_inicial") return "agendamento_inicial" as const; return null; }
