-- ════════════════════════════════════════════════════════════════════════════
-- FUITE corrigée : la MV catalogue RÉSEAU était lisible par anon
-- Auteur  : Xavier + Claude
-- Session : Catalogação work completion
-- Date    : 2026-06-10 (UTC)
--
-- FUITE : public.mv_books_catalog_list_network_v1 (catalogue réseau, ~2675 lignes
-- dont des livres visibility_level='network', ex. BTL) était SELECTable par le rôle
-- `anon` (ACL anon=arwdDxtm). Via PostgREST, un GET /rest/v1/mv_books_catalog_list_network_v1
-- anonyme renvoyait TOUT le catalogue réseau au public — contournant la RPC/vue
-- anonyme qui, elle, ne lit que la MV PUBLIQUE.
--
-- MODÈLE de visibilité (confirmé) :
--   • catalogue PUBLIC  → tout le monde : api.catalog_list_anon_v1 (security_invoker)
--                         lit mv_books_catalog_list_v1 → anon GARDE son accès.
--   • catalogue RÉSEAU  → authentifié·es : api.catalog_list_session_v1 (security_invoker)
--                         lit mv_books_catalog_list_network_v1 → authenticated GARDE son accès.
-- anon n'a AUCUN besoin légitime de la MV réseau (sa vue lit la MV publique).
--
-- FIX : révoquer tous les droits de `anon` sur la MV réseau. authenticated +
-- service_role + owner conservés (sinon casse le catalogue connecté). Idempotent.
-- ════════════════════════════════════════════════════════════════════════════

REVOKE ALL ON public.mv_books_catalog_list_network_v1 FROM anon;
