-- =============================================================================
-- H20 — L'identifiant d'origine d'une notice est gardé PAR bibliothèque
-- (aller-retour PMB, backlog H20 ; décidé le 27/09/2026 : table plutôt que
-- colonne de détention, faux identifiants du lot 63 effacés avant publication)
--
--  * public.book_external_ids (book_id, library_id, scheme, value) : le numéro
--    que la source d'une bibliothèque donne à une notice — même rattachée à une
--    notice qu'une autre bibliothèque a cataloguée ; unique par
--    (bibliothèque, schéma, valeur) ; lu par le staff de la bibliothèque ;
--  * posé à la publication d'un brouillon importé et des brouillons importés
--    qu'il a absorbés (publish_book_draft), d'un exemplaire rapproché
--    (publish_exemplar_draft), à l'absorption d'un brouillon importé par une
--    fiche existante (api.merge_draft_into_book) ; suit la notice gardée d'une
--    fusion (fn_fusion_notices, sous merge_book) ; un run ne se supprime pas tant qu'un exemplaire
--    rapproché l'attend (fn_import_delete_run) ;
--  * ce qui n'est pas un identifiant (numéro de ligne de staging, numéro de
--    fascicule, clé que portent plusieurs lignes d'un run) est jugé par
--    ingest.fn_h20_identifiant_d_origine et effacé des brouillons en cours, ici
--    et à chaque promotion ; les notices déjà publiées depuis un import sont
--    reprises.
--
-- Fonctions recréées depuis leur définition de production (md5 contrôlé) :
-- ingest.fn_create_book_drafts_from_import_rows, publish_book_draft,
-- publish_exemplar_draft, fn_fusion_notices, api.merge_draft_into_book,
-- fn_import_delete_run.
-- =============================================================================

-- ── 1. La table : l'identifiant d'origine, PAR bibliothèque ────────────────
-- books est partagée par le réseau : books.source_record_id ne peut dire que
-- l'origine de la notice partagée. Ici, chaque bibliothèque garde le numéro
-- que SA source (le PMB qu'elle a quitté ou qui reste sa base vivante) donne
-- à la notice — même quand l'import l'a rattachée à une notice qu'une autre
-- bibliothèque avait cataloguée. Schéma « import:<source> » : deux sources
-- d'une même bibliothèque peuvent réemployer les mêmes numéros.
CREATE TABLE IF NOT EXISTS public.book_external_ids (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id     bigint NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
  library_id  uuid   NOT NULL REFERENCES public.libraries(id) ON DELETE CASCADE,
  scheme      text   NOT NULL CONSTRAINT book_external_ids_scheme_check CHECK (scheme ~ '^[a-z][a-z0-9_]*(:[0-9a-z_-]+)?$'),
  value       text   NOT NULL CONSTRAINT book_external_ids_value_check CHECK (btrim(value) <> '' AND value = btrim(value)),
  source_id   bigint REFERENCES ingest.partner_catalog_sources(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT book_external_ids_par_bibliotheque UNIQUE (library_id, scheme, value)
);
CREATE INDEX IF NOT EXISTS book_external_ids_book_id_idx   ON public.book_external_ids (book_id);
CREATE INDEX IF NOT EXISTS book_external_ids_source_id_idx ON public.book_external_ids (source_id);
COMMENT ON TABLE public.book_external_ids IS
  'H20 (27/09/2026) : identifiant d''origine d''une notice PAR bibliotheque (numero de notice PMB, 001) ; '
  'scheme = import:<partner_catalog_sources.id>. Pose a la publication d''un brouillon importe, d''un '
  'exemplaire rapproche ou a l''absorption d''un brouillon importe ; suit la notice dans une fusion '
  '(merge_book) ; lu par le reimport (H21) et l''export (H24).';

ALTER TABLE public.book_external_ids ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.book_external_ids FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.book_external_ids TO authenticated;
GRANT ALL ON public.book_external_ids TO service_role;
-- Lecture : le staff de la bibliothèque, l'administration. Écriture : les
-- seules fonctions DEFINER de publication et de fusion.
DROP POLICY IF EXISTS book_external_ids_select_staff ON public.book_external_ids;
CREATE POLICY book_external_ids_select_staff ON public.book_external_ids
  FOR SELECT TO authenticated
  USING ((SELECT public.fn_caller_is_network_admin())
         OR library_id = ANY ((SELECT public.fn_caller_staff_library_ids())::uuid[]));

-- ── 2. Poser l'identifiant (fonctions de publication) ──────────────────────
-- La PREMIÈRE notice qui reçoit une clé la garde : une clé qu'une seconde
-- notice réclame ne lui est pas donnée (revue du 28/09 : une clé qui passait
-- de notice en notice désignait la dernière publiée). Une fusion de notices
-- déplace la clé elle-même (merge_book) ; la suppression d'une notice la
-- libère (cascade).
CREATE OR REPLACE FUNCTION ingest.fn_record_book_external_id(p_book_id bigint, p_library_id uuid, p_source_id bigint, p_value text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'ingest', 'pg_temp'
AS $function$
  insert into public.book_external_ids (book_id, library_id, scheme, value, source_id)
  select p_book_id, p_library_id, 'import:' || p_source_id, btrim(p_value), p_source_id
   where p_book_id is not null and p_library_id is not null and p_source_id is not null
     and nullif(btrim(coalesce(p_value, '')), '') is not null
  on conflict (library_id, scheme, value) do nothing;
$function$;
REVOKE EXECUTE ON FUNCTION ingest.fn_record_book_external_id(bigint, uuid, bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION ingest.fn_record_book_external_id(bigint, uuid, bigint, text) TO service_role;

-- ── 3. Ce qui est un identifiant d'origine, et ce qui n'en est pas un ──────
-- Le source_record_id d'un brouillon importé, s'il désigne VRAIMENT la notice
-- dans sa source ; sinon NULL. Ce qui n'en est pas un (mesuré en production
-- le 27-28/09) :
--  * le numéro de la LIGNE de staging, que l'import y mettait faute de 001
--    (1 631 brouillons du lot 63) — sauf si la ligne portait réellement cette
--    clé ;
--  * le numéro d'un FASCICULE : la colonne « numero » d'un CSV de périodiques
--    (colonne « periodico » remplie ; run 29 du lot 63) ;
--  * une clé que portent plusieurs LIGNES d'un même run : elle ne désigne pas
--    une notice (36 brouillons du run 29 pour 18 valeurs). Les brouillons
--    d'une même ligne (reprise, nouvelle promotion) ne comptent pas.
-- STABLE : dans un UPDATE, chaque ligne est jugée sur l'état d'avant.
CREATE OR REPLACE FUNCTION ingest.fn_h20_identifiant_d_origine(p_draft_id bigint)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'ingest', 'pg_temp'
AS $function$
  select case
    when nullif(btrim(coalesce(d.source_record_id, '')), '') is null then null
    when d.source_record_id = d.marc_json->'ingest'->>'staging_row_id'
         and not exists (select 1 from ingest.partner_catalog_staging_rows sr
                          where sr.id = case when d.source_record_id ~ '^[0-9]{1,18}$'
                                             then d.source_record_id::bigint end
                            and btrim(sr.external_key) = btrim(d.source_record_id)) then null
    when d.marc_json->'ingest'->>'detected_format' in ('csv', 'tsv')
         and btrim(d.source_record_id) = btrim(d.marc_json->'ingest'->'raw_payload'->>'numero')
         and nullif(btrim(d.marc_json->'ingest'->'raw_payload'->>'periodico'), '') is not null then null
    when exists (select 1 from public.book_drafts d2
                  where d2.id <> d.id and d2.marc_json ? 'ingest'
                    and d2.marc_json->'ingest'->>'run_id' = d.marc_json->'ingest'->>'run_id'
                    and d2.marc_json->'ingest'->>'staging_row_id' is distinct from d.marc_json->'ingest'->>'staging_row_id'
                    and btrim(d2.source_record_id) = btrim(d.source_record_id)) then null
    else btrim(d.source_record_id)
  end
  from public.book_drafts d
  where d.id = p_draft_id and d.marc_json ? 'ingest';
$function$;
REVOKE EXECUTE ON FUNCTION ingest.fn_h20_identifiant_d_origine(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION ingest.fn_h20_identifiant_d_origine(bigint) TO service_role;

-- ── 4. Les faux identifiants d'origine ─────────────────────────────────────
-- Effacés des brouillons non publiés : ici pour l'existant (lot 63), et par
-- l'import à chaque promotion (p_run_id), avant qu'une publication ne les
-- recopie dans books.source_record_id.
CREATE OR REPLACE FUNCTION ingest.fn_h20_effacer_faux_identifiants(p_run_id bigint DEFAULT NULL)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'ingest', 'pg_temp'
AS $function$
DECLARE
  v_n integer;
BEGIN
  -- Le déclencheur sync_book_native_provenance_bridge recopie source_record_id
  -- dans marc_json.anarbib_provenance, et l'y REPREND quand la colonne devient
  -- nulle : le miroir s'efface avec elle. Les cibles sont jugées d'abord,
  -- toutes sur le même état (une clé répétée s'efface sur chaque ligne).
  WITH cibles AS MATERIALIZED (
    SELECT d.id FROM public.book_drafts d
     WHERE d.marc_json ? 'ingest'
       AND d.status <> 'published'
       AND d.source_record_id IS NOT NULL
       AND (p_run_id IS NULL OR d.marc_json->'ingest'->>'run_id' = p_run_id::text)
       AND ingest.fn_h20_identifiant_d_origine(d.id) IS NULL
  )
  UPDATE public.book_drafts d
     SET source_record_id = NULL,
         marc_json = d.marc_json #- '{anarbib_provenance,source_record_id}'
   WHERE d.id IN (SELECT id FROM cibles);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;
REVOKE EXECUTE ON FUNCTION ingest.fn_h20_effacer_faux_identifiants(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION ingest.fn_h20_effacer_faux_identifiants(bigint) TO service_role;

-- ── 5. Reprise : les notices déjà publiées depuis un import ────────────────
-- Leur identifiant d'origine, à la bibliothèque du brouillon, sur la notice
-- publiée. Seuls les brouillons de CRÉATION : un brouillon de reprise d'une
-- autre bibliothèque recopie le marc_json de la notice et ne lui donnerait pas
-- le numéro de SA source. (Brouillons importés absorbés par une fusion : aucun
-- en production le 28/09 ; les fusions à venir posent le numéro elles-mêmes.)
CREATE OR REPLACE FUNCTION ingest.fn_h20_reprise_identifiants()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'ingest', 'pg_temp'
AS $function$
DECLARE
  v_n integer;
BEGIN
  INSERT INTO public.book_external_ids (book_id, library_id, scheme, value, source_id)
  SELECT DISTINCT ON (l.lib, r.source_id, v.valeur)
         d.published_book_id, l.lib, 'import:' || r.source_id, v.valeur, r.source_id
    FROM public.book_drafts d
    CROSS JOIN LATERAL (SELECT coalesce(d.owner_library_id,
                                        private.fn_book_draft_creator_library(d.id, d.created_by)) AS lib) l
    CROSS JOIN LATERAL (SELECT ingest.fn_h20_identifiant_d_origine(d.id) AS valeur) v
    JOIN ingest.partner_catalog_import_runs r
      ON r.id = (d.marc_json->'ingest'->>'run_id')::bigint
   WHERE d.status = 'published' AND d.action = 'create' AND d.published_book_id IS NOT NULL
     AND d.marc_json ? 'ingest'
     AND l.lib IS NOT NULL
     AND v.valeur IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = d.published_book_id)
   ORDER BY l.lib, r.source_id, v.valeur, d.updated_at DESC, d.id DESC
  ON CONFLICT (library_id, scheme, value) DO NOTHING;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;
REVOKE EXECUTE ON FUNCTION ingest.fn_h20_reprise_identifiants() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION ingest.fn_h20_reprise_identifiants() TO service_role;

-- ── 6. Les fonctions recréées ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION ingest.fn_create_book_drafts_from_import_rows(p_run_id bigint, p_row_ids bigint[] DEFAULT NULL::bigint[], p_batch_name text DEFAULT NULL::text, p_batch_notes text DEFAULT NULL::text, p_created_by uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'ingest', 'public', 'auth'
AS $function$
declare
  v_actor uuid;
  v_partner_name text;
  v_relation_status text;
  v_original_filename text;
  v_detected_format text;
  v_batch_id bigint;
  v_batch_name text;
  v_batch_notes text;
  v_created_count integer := 0;
  v_requested_count integer := 0;
  v_draft_id bigint;
  v_refresh jsonb;
  v_collection_hint text;
  v_local_classification_hint text;
  v_provenance_note text;
  rec record;
begin
  v_actor := coalesce(p_created_by, auth.uid());

  select s.partner_name, s.relation_status, r.original_filename, r.detected_format
    into v_partner_name, v_relation_status, v_original_filename, v_detected_format
  from ingest.partner_catalog_import_runs r
  join ingest.partner_catalog_sources s on s.id = r.source_id
  where r.id = p_run_id;

  if not found then
    raise exception 'import_run % introuvable', p_run_id;
  end if;

  if coalesce(array_length(p_row_ids, 1), 0) > 0 then
    select count(*)::integer
      into v_requested_count
    from ingest.partner_catalog_staging_rows sr
    where sr.run_id = p_run_id
      and sr.id = any(p_row_ids)
      and sr.created_book_draft_id is null
      and sr.created_exemplar_draft_id is null   -- H19 : déjà rapprochée
      and (
        (sr.match_status = 'new_record' and sr.editorial_decision = 'accept_new')
        or
        (sr.match_status in ('matched_book', 'matched_draft', 'possible_duplicate', 'manual_decision')
         and sr.editorial_decision = 'accept_duplicate')
      );
  else
    select count(*)::integer
      into v_requested_count
    from ingest.partner_catalog_staging_rows sr
    where sr.run_id = p_run_id
      and sr.created_book_draft_id is null
      and sr.created_exemplar_draft_id is null   -- H19 : déjà rapprochée
      and sr.selected_for_draft = true
      and sr.review_status = 'approved'
      and (
        (sr.match_status = 'new_record' and sr.editorial_decision = 'accept_new')
        or
        (sr.match_status in ('matched_book', 'matched_draft', 'possible_duplicate', 'manual_decision')
         and sr.editorial_decision = 'accept_duplicate')
      );
  end if;

  if v_requested_count = 0 then
    raise exception 'Aucune ligne autorisée à convertir pour le run %', p_run_id;
  end if;

  v_batch_name := coalesce(
    nullif(trim(p_batch_name), ''),
    format(
      'Import parceiro #%s — %s — %s',
      p_run_id,
      left(coalesce(v_partner_name, 'parceiro sem nome'), 80),
      to_char(now() at time zone 'UTC', 'YYYY-MM-DD HH24:MI UTC')
    )
  );

  v_batch_notes := coalesce(
    nullif(trim(p_batch_notes), ''),
    format(
      'Lote criado a partir do import run %s (%s, formato %s).',
      p_run_id,
      coalesce(v_original_filename, 'arquivo sem nome'),
      coalesce(v_detected_format, 'unknown')
    )
  );

  -- B30 : le lot naît avec sa bibliothèque — celle que fn_import_promote
  -- tamponne ensuite sur ses notices : le run pour un catalogue propre, la
  -- destination pour un dépôt compagnon ou un entrepôt OAI (nulle tant qu'elle
  -- est inconnue : le lot est alors à l'administration).
  insert into public.catalog_batches (name, notes, created_by, library_id)
  values (v_batch_name, v_batch_notes, v_actor,
          (select case when s.source_kind in ('partner_deposit', 'oai_pmh') then s.destination_library_id
                       else r.library_id end
             from ingest.partner_catalog_import_runs r
             left join ingest.partner_catalog_sources s on s.id = r.source_id
            where r.id = p_run_id))
  returning id into v_batch_id;

  for rec in
    select sr.*, r.original_filename, r.detected_format, s.partner_name, s.relation_status, s.source_kind
    from ingest.partner_catalog_staging_rows sr
    join ingest.partner_catalog_import_runs r on r.id = sr.run_id
    join ingest.partner_catalog_sources s on s.id = r.source_id
    where sr.run_id = p_run_id
      and sr.created_book_draft_id is null
      and sr.created_exemplar_draft_id is null   -- H19 : déjà rapprochée
      and not exists (
        select 1 from ingest.partner_catalog_row_to_draft rd where rd.staging_row_id = sr.id
      )
      and (
        (coalesce(array_length(p_row_ids, 1), 0) > 0 and sr.id = any(p_row_ids))
        or
        (coalesce(array_length(p_row_ids, 1), 0) = 0 and sr.selected_for_draft = true and sr.review_status = 'approved')
      )
      and (
        (sr.match_status = 'new_record' and sr.editorial_decision = 'accept_new')
        or
        (sr.match_status in ('matched_book', 'matched_draft', 'possible_duplicate', 'manual_decision')
         and sr.editorial_decision = 'accept_duplicate')
      )
    order by sr.row_no, sr.id
  loop
    v_collection_hint := ingest.fn_partner_catalog_extract_collection_hint(rec.normalized_payload, rec.raw_payload);
    v_local_classification_hint := ingest.fn_partner_catalog_extract_local_classification_hint(rec.normalized_payload, rec.raw_payload);

    v_provenance_note := format(
      'Importado de catálogo parceiro "%s" (%s, run %s, linha %s, formato bruto %s, relação %s, decisão %s).',
      rec.partner_name,
      coalesce(rec.original_filename, 'arquivo sem nome'),
      rec.run_id,
      rec.row_no,
      coalesce(rec.detected_format, 'unknown'),
      coalesce(rec.relation_status, 'sem_status'),
      coalesce(rec.editorial_decision, 'pending')
    );

    if v_local_classification_hint is not null then
      v_provenance_note := v_provenance_note || format(' Sinal local da parceira preservado: %s.', v_local_classification_hint);
    end if;

    insert into public.book_drafts (
      batch_id, action, status, titulo, subtitulo, autor, edicao,
      local_publicacao, editora, ano, isbn, issn, idioma, tipo_material,
      cdd, colecao, marc_json, created_by, updated_by, acquisition_mode,
      partner_source, source_record_id, import_format, import_method,
      provenance_note, mutualization_status, source_label, notas
    ) values (
      v_batch_id,
      'create',
      'draft',
      nullif(trim(rec.title), ''),
      nullif(trim(rec.subtitle), ''),
      coalesce(nullif(trim(rec.responsibility_statement), ''), ingest.fn_format_partner_authors(rec.authors)),
      nullif(trim(rec.edition_statement), ''),
      nullif(trim(rec.place_of_publication), ''),
      nullif(trim(rec.publisher), ''),
      nullif(trim(rec.publication_year), ''),
      nullif(trim(rec.isbn), ''),
      nullif(trim(rec.issn), ''),
      nullif(trim(rec.language), ''),
      -- tipo_material : MAP du type brut (RIS/BibTeX) vers le vocabulaire valide.
      case lower(coalesce(nullif(trim(rec.item_type), ''), 'book'))
        when 'book' then 'livro'
        when 'livro' then 'livro'
        when 'jour' then 'periodico'
        when 'mgzn' then 'periodico'
        when 'news' then 'periodico'
        when 'newspaper' then 'periodico'
        when 'periodico' then 'periodico'
        when 'chap' then 'artigo'
        when 'inbook' then 'artigo'
        when 'article' then 'artigo'
        when 'artigo' then 'artigo'
        when 'thes' then 'tese'
        when 'tese' then 'tese'
        when 'rprt' then 'relatorio'
        when 'relatorio' then 'relatorio'
        when 'pamp' then 'tract'
        when 'tract' then 'tract'
        when 'zine' then 'zine'
        when 'elec' then 'recurso_digital'
        when 'sound' then 'audio'
        when 'audio' then 'audio'
        when 'video' then 'audiovisual'
        when 'mpct' then 'audiovisual'
        when 'audiovisual' then 'audiovisual'
        else 'livro'
      end,
      null,
      case
        when v_collection_hint is null then null
        when lower(coalesce(rec.item_type, '')) ~ '(periodic|journal|article|boletim|periodico|periódico|jour)' then null
        when lower(regexp_replace(coalesce(v_collection_hint, ''), '\s+', ' ', 'g')) = lower(regexp_replace(coalesce(rec.title, ''), '\s+', ' ', 'g')) then null
        else v_collection_hint
      end,
      coalesce(rec.normalized_payload, '{}'::jsonb)
        || jsonb_build_object(
             'ingest',
             jsonb_build_object(
               'run_id', rec.run_id,
               'source_id', (select r2.source_id from ingest.partner_catalog_import_runs r2 where r2.id = rec.run_id),   -- H20
               'staging_row_id', rec.id,
               'row_no', rec.row_no,
               'source_file_id', rec.source_file_id,
               'partner_name', rec.partner_name,
               'relation_status', rec.relation_status,
               'original_filename', rec.original_filename,
               'detected_format', rec.detected_format,
               'raw_payload', coalesce(rec.raw_payload, '{}'::jsonb),
               'authors', coalesce(rec.authors, '[]'::jsonb),
               'subjects', coalesce(rec.subjects, '[]'::jsonb),
               'editorial_decision', rec.editorial_decision,
               'editorial_note', rec.editorial_note,
               'derived_collection_hint', v_collection_hint,
               'derived_local_classification_hint', v_local_classification_hint
             )
           ),
      v_actor,
      v_actor,
      null,
      'other_partner',                               -- partner_source : code valide (FK source_partner_code). Nom precis dans provenance_note/source_label.
      -- H20 : l'identifiant d'origine du fichier (001), ou rien — jamais le
      -- numéro de la ligne de staging, qui passait pour un numéro de PMB.
      nullif(trim(rec.external_key), ''),
      null,                                          -- import_format : NULL (evite FK source_format_code)
      null,                                          -- import_method : NULL (evite FK import_method_code)
      v_provenance_note,
      null,
      coalesce(rec.original_filename, rec.partner_name),
      concat_ws(
        ' ',
        case
          when rec.subjects is not null
           and jsonb_typeof(rec.subjects) = 'array'
           and jsonb_array_length(rec.subjects) > 0
          then 'Assuntos importados: '
               || array_to_string(array(select jsonb_array_elements_text(rec.subjects)), '; ')
          else null
        end,
        case
          when v_local_classification_hint is not null
          then format('Classificação / cote local preservada da parceira: %s.', v_local_classification_hint)
          else null
        end
      )
    ) returning id into v_draft_id;

    insert into ingest.partner_catalog_row_to_draft (staging_row_id, run_id, draft_id, batch_id, created_by)
    values (rec.id, rec.run_id, v_draft_id, v_batch_id, v_actor);

    update ingest.partner_catalog_staging_rows
       set created_book_draft_id = v_draft_id,
           review_status = 'draft_created',
           selected_for_draft = false
     where id = rec.id;

    v_created_count := v_created_count + 1;
  end loop;

  if v_created_count = 0 then
    delete from public.catalog_batches where id = v_batch_id;
    raise exception 'Aucun rascunho créé pour le run %', p_run_id;
  end if;

  -- H20 (revue du 28/09) : une clé que plusieurs lignes du run portent, ou le
  -- numéro d'un fascicule, n'est pas un identifiant d'origine : effacée des
  -- brouillons du run avant qu'une publication ne la recopie.
  perform ingest.fn_h20_effacer_faux_identifiants(p_run_id);

  v_refresh := ingest.fn_refresh_partner_catalog_run_counters(p_run_id);

  return jsonb_build_object(
    'run_id', p_run_id,
    'batch_id', v_batch_id,
    'batch_name', v_batch_name,
    'requested_rows', v_requested_count,
    'created_drafts', v_created_count,
    'run', v_refresh
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.publish_book_draft(p_draft_id bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_draft public.book_drafts%rowtype;
  v_book_id bigint;
  v_isbn_norm text;
  v_existing_book_id bigint;
  v_holding_id bigint;
  v_library_id uuid;
  v_circ_policy text;
  v_auto_tombo text;                         -- #tombo-serie (17/06)
  v_copies int;                              -- #copies (17/08) : nb d'exemplaires initiaux
  v_i int;
  v_linked int := 0;                         -- H19 : exemplaires importés rattachés
  v_x record;
  v_valid_types text[] := ARRAY[
    'livro','periodico','tract','cartaz','audio','audiovisual',
    'recurso_digital','dossie','tese','artigo','relatorio','zine'
  ];
begin
  -- B30 : le staff de catalogage ACTIF, ou l'administration du réseau — les
  -- lots sans bibliothèque ne sont qu'à elle ; la garde #79 ne demandait pas
  -- d'adhésion active et fermait la porte à l'administration sans adhésion.
  IF NOT (public.fn_caller_is_network_admin()
          OR EXISTS (SELECT 1 FROM public.user_library_memberships m
                      WHERE m.user_id = auth.uid() AND m.status = 'active'
                        AND m.role = ANY (ARRAY['librarian'::text, 'coordenador'::text]))) THEN
    RAISE EXCEPTION 'Acesso restrito ao staff de catalogacao.' USING HINT = 'error.catalog.staff_only';
  END IF;
  select * into v_draft from public.book_drafts where id = p_draft_id;
  if not found then
    raise exception 'rascunho_nao_encontrado' using hint = 'error.publish.draft_not_found';
  end if;
  -- B29 (CAT-E18) : on ne publie que les brouillons de ses bibliothèques
  -- (celle du brouillon, sinon celle de son créateur), ou comme administration.
  -- Avant tout autre contrôle : aucun ne renseigne sur le brouillon d'autrui.
  if not coalesce(public.fn_caller_can_edit_book_draft(p_draft_id), false) then
    raise exception 'Ce rascunho est rattache a une bibliotheque dont vous n''etes pas membre.' using hint = 'error.publish.other_library';
  end if;
  if v_draft.status = 'cancelled' then
    raise exception 'rascunho_descartado' using hint = 'error.publish.draft_cancelled';
  end if;

  -- 05/09/2026 : un lot ne d'un import ne se publie qu'apres une revision
  -- approuvee par l'administration du reseau (catalog_batch_reviews).
  -- publish_catalog_batch passe ici pour chaque brouillon : la garde le couvre.
  if v_draft.batch_id is not null
     and public.fn_batch_is_imported(v_draft.batch_id)
     and public.fn_batch_review_status(v_draft.batch_id) is distinct from 'approved' then
    raise exception 'lote_importado_sem_revisao' using hint = 'error.publish.review_required';
  end if;

  if v_draft.titulo is null or btrim(v_draft.titulo) = '' then
    raise exception 'titulo_obrigatorio' using hint = 'error.publish.titulo_required';
  end if;
  if v_draft.bib_ref is null or btrim(v_draft.bib_ref) = '' then
    raise exception 'bib_ref_obrigatoria' using hint = 'error.publish.bib_ref_required';
  end if;
  if v_draft.tipo_material is null or btrim(v_draft.tipo_material) = '' then
    raise exception 'tipo_material_obrigatorio' using hint = 'error.publish.tipo_material_required';
  end if;
  if lower(v_draft.tipo_material) <> ALL(v_valid_types) then
    raise exception 'tipo_material_invalido' using hint = 'error.publish.tipo_material_invalid';
  end if;

  select b.id into v_existing_book_id
    from public.books b
   where b.bib_ref = v_draft.bib_ref
     and (v_draft.published_book_id is null or b.id <> v_draft.published_book_id)
   limit 1;
  if v_existing_book_id is not null then
    raise exception 'bib_ref_duplicado: %', v_existing_book_id
      using errcode = 'P0001',
            hint = format('Ja existe uma ficha publicada com a mesma referencia bibliografica %s (ficha %s). Altere a bib_ref ou verifique a ficha existente.', v_draft.bib_ref, v_existing_book_id);
  end if;
  v_existing_book_id := null;

  if v_draft.published_book_id is null then
    v_isbn_norm := regexp_replace(upper(coalesce(v_draft.isbn, '')), '[^0-9X]', '', 'g');
    if v_isbn_norm <> '' then
      select b.id into v_existing_book_id
        from public.books b
       where regexp_replace(upper(coalesce(b.isbn, '')), '[^0-9X]', '', 'g') = v_isbn_norm
         -- Volumes (27/09/2026) : l'ISBN d'un ensemble est porté par chacun de
         -- ses volumes (BTL-TL-000447 et BTL-TL-000448 : volumes 2 et 3 de « La
         -- C.N.T. y la Revolución Española », même ISBN). Deux notices qui portent
         -- des numéros de volume DIFFÉRENTS ne sont pas des doublons : refuser la
         -- seconde poussait, par le message ci-dessous, à enregistrer le volume 4
         -- comme un exemplaire du volume 2. Même volume, ou volume absent d'un
         -- côté : doublon, comme avant.
         and not (nullif(btrim(coalesce(v_draft.volume, '')), '') is not null
                  and nullif(btrim(coalesce(b.volume, '')), '') is not null
                  and lower(btrim(b.volume)) <> lower(btrim(v_draft.volume)))
       limit 1;
      if v_existing_book_id is not null then
        raise exception 'isbn_duplicado: %', v_existing_book_id
          using errcode = 'P0001',
                hint = format('Ja existe uma ficha publicada com o mesmo ISBN (ficha %s). Revise o ISBN ou adicione um exemplar a ficha existente.', v_existing_book_id);
      end if;
    end if;

    insert into public.books (
      work_id,
      cdd, autor, titulo, ano, editora, bib_ref, loanable,
      subtitulo, edicao, local_publicacao, isbn, issn, idioma, paginas,
      notas, tipo_material, cover_object_path, cover_source, cover_license, marc_json, catalog_source,
      created_by, updated_by, updated_at, last_cataloged_at,
      serial_id,                             -- #périodiques P7 (27/08)
      titulo_periodico, volume, numero, fasciculo, data_edicao,
      periodicidade, colecao, acquisition_mode, acquisition_date,
      owner_library, holder_library, partner_source, source_record_id,
      source_record_url, import_format, import_method, provenance_note,
      mutualization_status, source_label,
      tract_campaign, emitter_org, approximate_date, diffusion_place,
      recto_verso, physical_format, print_technique, physical_state,
      audio_duration, audio_support, audio_format, audio_language,
      audio_participants, audio_recording_type,
      audiovisual_duration, audiovisual_support, audiovisual_language,
      audiovisual_director, audiovisual_participants, audiovisual_subtitles,
      audiovisual_access_note,
      digital_native_url, digital_native_access, digital_native_restriction,
      digital_native_usage, digital_native_file_note,
      dossier_scope, dossier_period, dossier_organizations, dossier_context,
      distribuidora, gravadora, tese_university, tese_advisor,
      artigo_source, artigo_volume, artigo_issue, artigo_pages,
      relatorio_org, relatorio_recipient, relatorio_internal_notes,
      zine_print_run, zine_technique, zine_format,
      subjects
    )
    values (
      v_draft.work_id,                       -- #œuvre (17/08) : NULL -> fn_books_ensure_work crée une œuvre neuve
      v_draft.cdd, v_draft.autor, v_draft.titulo, v_draft.ano,
      v_draft.editora, v_draft.bib_ref, coalesce(v_draft.loanable, true),
      v_draft.subtitulo, v_draft.edicao, v_draft.local_publicacao,
      v_draft.isbn, v_draft.issn, v_draft.idioma, v_draft.paginas,
      v_draft.notas, v_draft.tipo_material, v_draft.cover_object_path,
      v_draft.cover_source, v_draft.cover_license,  -- capas (27/09) : provenance et licence de l'image
      coalesce(v_draft.marc_json, '{}'::jsonb), 'catalogacao',
      coalesce(v_draft.created_by, auth.uid()),
      coalesce(v_draft.updated_by, auth.uid()), now(), now(),
      v_draft.serial_id,                     -- #périodiques P7 (27/08)
      v_draft.titulo_periodico, v_draft.volume, v_draft.numero,
      v_draft.fasciculo, v_draft.data_edicao, v_draft.periodicidade,
      v_draft.colecao, v_draft.acquisition_mode, v_draft.acquisition_date,
      v_draft.owner_library, v_draft.holder_library, v_draft.partner_source,
      v_draft.source_record_id, v_draft.source_record_url,
      v_draft.import_format, v_draft.import_method, v_draft.provenance_note,
      v_draft.mutualization_status, v_draft.source_label,
      v_draft.tract_campaign, v_draft.emitter_org, v_draft.approximate_date,
      v_draft.diffusion_place, v_draft.recto_verso, v_draft.physical_format,
      v_draft.print_technique, v_draft.physical_state,
      v_draft.audio_duration, v_draft.audio_support, v_draft.audio_format,
      v_draft.audio_language, v_draft.audio_participants,
      v_draft.audio_recording_type,
      v_draft.audiovisual_duration, v_draft.audiovisual_support,
      v_draft.audiovisual_language, v_draft.audiovisual_director,
      v_draft.audiovisual_participants, v_draft.audiovisual_subtitles,
      v_draft.audiovisual_access_note,
      v_draft.digital_native_url, v_draft.digital_native_access,
      v_draft.digital_native_restriction, v_draft.digital_native_usage,
      v_draft.digital_native_file_note,
      v_draft.dossier_scope, v_draft.dossier_period,
      v_draft.dossier_organizations, v_draft.dossier_context,
      v_draft.distribuidora, v_draft.gravadora, v_draft.tese_university, v_draft.tese_advisor,
      v_draft.artigo_source, v_draft.artigo_volume, v_draft.artigo_issue,
      v_draft.artigo_pages, v_draft.relatorio_org, v_draft.relatorio_recipient,
      v_draft.relatorio_internal_notes,
      v_draft.zine_print_run, v_draft.zine_technique, v_draft.zine_format,
      v_draft.subjects
    )
    returning id into v_book_id;

    -- #biblio-choisie (17/08, elargi le 29/08/2026). La regle voulue : choisir
    -- explicitement la bibliotheque de destination est reserve a l'admin reseau.
    -- Elle etait posee sur initial_copies_library_id SEULEMENT, alors que
    -- owner_library_id est lu AVANT lui, decide donc en premier, et se modifie
    -- librement par toute personne qui catalogue (policy ALL sans portee de
    -- bibliotheque, UPDATE sur les 103 colonnes). La regle etait donc appliquee
    -- sur un champ et ouverte sur celui qui a la priorite.
    v_library_id := v_draft.owner_library_id;

    -- Publier dans le catalogue d'une bibliotheque, c'est y creer un holding et
    -- un exemplaire avec un tombo pris dans SA serie : on ne le fait pas au nom
    -- d'un collectif dont on n'est pas membre.
    if v_library_id is not null
       and not public.fn_caller_is_network_admin()
       and not exists (
         select 1 from public.user_library_memberships ulm
          where ulm.user_id = auth.uid()
            and ulm.status = 'active'
            and ulm.role = any (array['librarian'::text, 'coordenador'::text])
            and ulm.library_id = v_library_id
       ) then
      raise exception
        'Ce rascunho est rattache a une bibliotheque dont vous n''etes pas membre (%).', v_library_id
        using hint = 'error.publish.other_library';
    end if;

    -- La regle de resolution vit desormais dans UNE fonction, appelee ici et
    -- par la vue qui l'affiche a l'ecran. Deux copies d'une meme regle
    -- derivent : ce depot en a paye assez pour ne pas recommencer.
    -- B30 (revue) : une notice IMPORTÉE sans bibliothèque (dépôt d'une compagne
    -- non admise, destination inconnue) ne se publie pas : le repli ci-dessous
    -- la mettrait dans la bibliothèque de qui publie — ou nulle part, pour une
    -- administration sans adhésion. Sa bibliothèque vient du lot (« Changer la
    -- bibliothèque du lot »), ou d'un choix explicite de l'administration.
    if v_library_id is null
       and not (v_draft.initial_copies_library_id is not null and public.fn_caller_is_network_admin())
       -- importée : le lien d'import, ou la trace que la promotion laisse dans
       -- marc_json (le lien part avec une suppression définitive ou avec le run ;
       -- le rejeu du journal ne le recrée pas, la trace reste)
       and (exists (select 1 from ingest.partner_catalog_row_to_draft m where m.draft_id = p_draft_id)
            or coalesce(v_draft.marc_json, '{}'::jsonb) ? 'ingest')
       -- avec des exemplaires importés, le refus H19 ci-dessous dit mieux ce qui manque
       and not exists (select 1 from public.exemplar_drafts x
                        where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')) then
      raise exception 'noticia_importada_sem_biblioteca' using hint = 'error.publish.record_without_library';
    end if;
    if v_library_id is null then
      v_library_id := public.fn_book_draft_destination_library(p_draft_id);
    end if;

    -- L'override admin reste le seul chemin pour cibler une autre bibliotheque.
    -- H19 (27/09/2026, revue) : une notice qui porte des exemplaires importés
    -- les publie là où ils ont été attribués (tampon, réattribution du lot) ;
    -- le choix « exemplaires initiaux » de l'écran ne les sépare pas d'elle.
    if v_draft.initial_copies_library_id is not null and public.fn_caller_is_network_admin()
       and not exists (select 1 from public.exemplar_drafts x
                        where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')) then
      v_library_id := v_draft.initial_copies_library_id;
    end if;

    -- H19 : les exemplaires importés vont dans la bibliothèque qui leur a été
    -- DONNÉE (tampon à la promotion, ou réattribution par l'administration),
    -- jamais dans celle que le repli ci-dessus déduit de qui publie : c'est
    -- ainsi que le fonds d'une compagne non admise partirait chez qui clique
    -- (vu au banc le 26/09, suite import_exemplaires T6). Sans bibliothèque :
    -- refus ; bibliothèque différente de celle de la notice : refus.
    if exists (select 1 from public.exemplar_drafts x
                where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')
                  and x.target_library_id is null) then
      raise exception 'exemplares_importados_sem_biblioteca'
        using hint = 'error.publish.items_without_library';
    end if;
    if exists (select 1 from public.exemplar_drafts x
                where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')
                  and x.target_library_id is distinct from v_library_id) then
      raise exception 'exemplares_importados_de_outra_biblioteca'
        using hint = 'error.publish.items_library_mismatch';
    end if;

    if v_library_id is not null then
      v_circ_policy := case when coalesce(v_draft.loanable, true) then 'emprestavel' else 'consulta' end;
      insert into public.book_holdings (book_id, library_id)
      values (v_book_id, v_library_id)
      on conflict (book_id, library_id) do update set updated_at = now()
      returning id into v_holding_id;

      -- #copies (17/08) : N exemplaires (défaut 1, borné 1..50). fn_next_tombo,
      -- appelée en boucle dans la même transaction, voit ses propres INSERT et
      -- renvoie des tombos séquentiels distincts (+ verrou d'avis par préfixe).
      -- H19 : les exemplaires du fichier importé REMPLACENT l'exemplaire
      -- automatique (sinon N importés + 1 automatique). Ils sont publiés plus
      -- bas, une fois la notice marquée publiée.
      select count(*) into v_linked
        from public.exemplar_drafts x
       where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready');
      v_copies := case when v_linked > 0 then 0
                       else greatest(1, least(coalesce(v_draft.initial_copies, 1), 50)) end;
      for v_i in 1..v_copies loop
        begin
          v_auto_tombo := public.fn_next_tombo(v_library_id);
        exception when others then
          -- Pas de tombo_pattern : repli sur bib_ref, suffixé pour éviter la
          -- collision d'unicité globale au-delà du 1er exemplaire.
          v_auto_tombo := case when v_i = 1 then v_draft.bib_ref
                               else v_draft.bib_ref || '-' || v_i::text end;
        end;
        if v_auto_tombo is null or btrim(v_auto_tombo) = '' then
          v_auto_tombo := case when v_i = 1 then v_draft.bib_ref
                               else v_draft.bib_ref || '-' || v_i::text end;
        end if;
        insert into public.exemplares (bib_ref, tombo, library_id, holding_id, circulation_policy, visibility)
        values (v_draft.bib_ref, v_auto_tombo, v_library_id, v_holding_id, v_circ_policy, 'public');
      end loop;

      perform public.fn_v2_recompute_holdings_availability(p_holding_ids := ARRAY[v_holding_id]);
    end if;

  else
    -- H19 : les exemplaires importés ne se rattachent qu'à une notice CRÉÉE
    -- par la publication (l'import ne produit que des brouillons 'create').
    if exists (select 1 from public.exemplar_drafts x
                where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')) then
      raise exception 'exemplares_importados_em_atualizacao'
        using hint = 'error.publish.items_on_update';
    end if;
    update public.books
    set
      work_id = coalesce(v_draft.work_id, work_id),
      cdd = v_draft.cdd, autor = v_draft.autor, titulo = v_draft.titulo,
      ano = v_draft.ano, editora = v_draft.editora, bib_ref = v_draft.bib_ref,
      loanable = coalesce(v_draft.loanable, true),
      subtitulo = v_draft.subtitulo, edicao = v_draft.edicao,
      local_publicacao = v_draft.local_publicacao,
      isbn = v_draft.isbn, issn = v_draft.issn, idioma = v_draft.idioma,
      paginas = v_draft.paginas, notas = v_draft.notas,
      tipo_material = v_draft.tipo_material,
      cover_object_path = v_draft.cover_object_path,
      -- Capas (27/09/2026) : provenance et licence vont PAR PAIRE et suivent
      -- l'IMAGE. Un brouillon qui porte une provenance impose la sienne,
      -- licence comprise même nulle (Open Library et Inventaire écrivent au
      -- MÊME chemin books/<clé>/front.jpg : re-choisir une candidate ne doit
      -- pas garder la licence de l'autre). Un brouillon qui n'en porte pas
      -- (reprise d'avant cette migration) garde celles de la notice si l'image
      -- est la même — les écrire à NULL effacerait une attribution connue,
      -- comme serial_id le 27/08 — et n'hérite de rien pour une autre image.
      -- Dans un SET, la colonne nue désigne l'ANCIENNE valeur de la ligne.
      cover_source = case when v_draft.cover_source is not null then v_draft.cover_source
                          when v_draft.cover_object_path is not distinct from cover_object_path then cover_source
                          end,
      cover_license = case when v_draft.cover_source is not null then v_draft.cover_license
                           when v_draft.cover_object_path is not distinct from cover_object_path then cover_license
                           end,
      marc_json = coalesce(v_draft.marc_json, '{}'::jsonb),
      updated_by = coalesce(v_draft.updated_by, auth.uid()),
      updated_at = now(), last_cataloged_at = now(),
      -- #périodiques P7b (27/08) : coalesce, comme work_id juste au-dessus.
      -- Un brouillon antérieur à la colonne porte NULL ; l'écrire tel quel
      -- EFFAÇAIT le rattachement à chaque republication, en silence.
      serial_id = coalesce(v_draft.serial_id, serial_id),
      titulo_periodico = v_draft.titulo_periodico,
      volume = v_draft.volume, numero = v_draft.numero,
      fasciculo = v_draft.fasciculo, data_edicao = v_draft.data_edicao,
      periodicidade = v_draft.periodicidade, colecao = v_draft.colecao,
      acquisition_mode = v_draft.acquisition_mode,
      acquisition_date = v_draft.acquisition_date,
      owner_library = v_draft.owner_library, holder_library = v_draft.holder_library,
      partner_source = v_draft.partner_source,
      source_record_id = v_draft.source_record_id,
      source_record_url = v_draft.source_record_url,
      import_format = v_draft.import_format, import_method = v_draft.import_method,
      provenance_note = v_draft.provenance_note,
      mutualization_status = v_draft.mutualization_status,
      source_label = v_draft.source_label,
      tract_campaign = v_draft.tract_campaign, emitter_org = v_draft.emitter_org,
      approximate_date = v_draft.approximate_date,
      diffusion_place = v_draft.diffusion_place, recto_verso = v_draft.recto_verso,
      physical_format = v_draft.physical_format,
      print_technique = v_draft.print_technique,
      physical_state = v_draft.physical_state,
      audio_duration = v_draft.audio_duration, audio_support = v_draft.audio_support,
      audio_format = v_draft.audio_format, audio_language = v_draft.audio_language,
      audio_participants = v_draft.audio_participants,
      audio_recording_type = v_draft.audio_recording_type,
      audiovisual_duration = v_draft.audiovisual_duration,
      audiovisual_support = v_draft.audiovisual_support,
      audiovisual_language = v_draft.audiovisual_language,
      audiovisual_director = v_draft.audiovisual_director,
      audiovisual_participants = v_draft.audiovisual_participants,
      audiovisual_subtitles = v_draft.audiovisual_subtitles,
      audiovisual_access_note = v_draft.audiovisual_access_note,
      digital_native_url = v_draft.digital_native_url,
      digital_native_access = v_draft.digital_native_access,
      digital_native_restriction = v_draft.digital_native_restriction,
      digital_native_usage = v_draft.digital_native_usage,
      digital_native_file_note = v_draft.digital_native_file_note,
      dossier_scope = v_draft.dossier_scope, dossier_period = v_draft.dossier_period,
      dossier_organizations = v_draft.dossier_organizations,
      dossier_context = v_draft.dossier_context,
      distribuidora = v_draft.distribuidora, gravadora = v_draft.gravadora,
      tese_university = v_draft.tese_university, tese_advisor = v_draft.tese_advisor,
      artigo_source = v_draft.artigo_source, artigo_volume = v_draft.artigo_volume,
      artigo_issue = v_draft.artigo_issue, artigo_pages = v_draft.artigo_pages,
      relatorio_org = v_draft.relatorio_org,
      relatorio_recipient = v_draft.relatorio_recipient,
      relatorio_internal_notes = v_draft.relatorio_internal_notes,
      zine_print_run = v_draft.zine_print_run,
      zine_technique = v_draft.zine_technique, zine_format = v_draft.zine_format,
      subjects = v_draft.subjects
    where id = v_draft.published_book_id
    returning id into v_book_id;
  end if;

  update public.book_drafts
  set published_book_id = v_book_id, status = 'published',
      updated_by = coalesce(v_draft.updated_by, auth.uid()), updated_at = now()
  where id = p_draft_id;

  -- H19 : publier les exemplaires importés rattachés, dans la détention qui
  -- vient d'être posée ; chacun reçoit un tombo du schéma de SA bibliothèque
  -- (IMP-21 a) et garde son code d'origine.
  if v_linked > 0 then
    update public.exemplar_drafts x
       set target_library_id = v_library_id,
           target_holding_id = v_holding_id,
           target_bib_ref    = v_draft.bib_ref,
           updated_at        = now()
     where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready');
    for v_x in
      select x.id from public.exemplar_drafts x
       where x.book_draft_id = p_draft_id and x.status in ('draft', 'ready')
       order by x.id
    loop
      perform public.publish_exemplar_draft(v_x.id);
    end loop;
    perform public.fn_v2_recompute_holdings_availability(p_holding_ids := ARRAY[v_holding_id]);
  end if;

  -- H20 (27/09/2026) : une notice importée garde, À LA BIBLIOTHÈQUE où elle
  -- vient d'être publiée, le numéro que lui donnait sa source (001 de PMB) —
  -- books.source_record_id ne dit que l'origine de la notice partagée.
  -- Revue du 28/09 : ce qu'est un identifiant d'origine se juge en un seul
  -- lieu (ingest.fn_h20_identifiant_d_origine) ; les brouillons importés que
  -- celui-ci a absorbés (fusion de brouillons, en chaîne) gardent aussi le leur.
  if v_library_id is not null then
    if v_draft.marc_json ? 'ingest' then
      perform ingest.fn_record_book_external_id(
        v_book_id, v_library_id, coalesce((v_draft.marc_json->'ingest'->>'source_id')::bigint,
               (select r.source_id from ingest.partner_catalog_import_runs r
                 where r.id = (v_draft.marc_json->'ingest'->>'run_id')::bigint)),
        ingest.fn_h20_identifiant_d_origine(p_draft_id));
    end if;
    perform ingest.fn_record_book_external_id(
              v_book_id, v_library_id, coalesce((l.marc_json->'ingest'->>'source_id')::bigint,
               (select r.source_id from ingest.partner_catalog_import_runs r
                 where r.id = (l.marc_json->'ingest'->>'run_id')::bigint)),
              ingest.fn_h20_identifiant_d_origine(l.id))
       from public.book_drafts l
      where l.id in (with recursive absorbes(id) as (
                        select ml.duplicate_id from public.merge_log ml
                         where ml.entity_type = 'book_draft' and ml.details->>'scenario' = 'draft_into_draft'
                           and ml.canonical_id = p_draft_id
                        union
                        select ml.duplicate_id from public.merge_log ml
                          join absorbes a on ml.canonical_id = a.id
                         where ml.entity_type = 'book_draft' and ml.details->>'scenario' = 'draft_into_draft')
                      select id from absorbes)
        and l.status = 'cancelled' and l.marc_json ? 'ingest';
  end if;

  perform public.publish_book_draft_digital_resources(p_draft_id, v_book_id);

  return v_book_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.publish_exemplar_draft(p_draft_id bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_draft public.exemplar_drafts%rowtype;
  v_exemplar_id bigint;
  v_library_id uuid;
  v_bridge record;
  v_resolved_holding_id bigint := null;
  v_resolved_bib_ref text := null;
  v_holding record;
  v_seed_policy text;
  v_final_tombo text;
  v_constraint text;          -- H19
  v_record_status text;       -- H19
  v_existing_library uuid;    -- H19 : l'exemplaire déjà publié (republication)
  v_existing_tombo text;      -- H19
  v_existing_code text;       -- H19
  v_item_code text;           -- H19 : code d'origine qu'aura l'exemplaire
begin
  -- B30 : le staff de catalogage ACTIF, ou l'administration du réseau — les
  -- lots sans bibliothèque ne sont qu'à elle ; la garde #79 ne demandait pas
  -- d'adhésion active et fermait la porte à l'administration sans adhésion.
  IF NOT (public.fn_caller_is_network_admin()
          OR EXISTS (SELECT 1 FROM public.user_library_memberships m
                      WHERE m.user_id = auth.uid() AND m.status = 'active'
                        AND m.role = ANY (ARRAY['librarian'::text, 'coordenador'::text]))) THEN
    RAISE EXCEPTION 'Acesso restrito ao staff de catalogacao.' USING HINT = 'error.catalog.staff_only';
  END IF;
  -- B29 (CAT-E18) : l'exemplaire appartient à sa bibliothèque (cible, sinon
  -- celle de sa notice, sinon celle de son créateur). AVANT la synchronisation
  -- de sa détention, qui écrit dans le brouillon.
  if exists (select 1 from public.exemplar_drafts x where x.id = p_draft_id)
     and not coalesce(public.fn_caller_can_edit_exemplar_draft(p_draft_id), false) then
    raise exception 'Ce rascunho est rattache a une bibliotheque dont vous n''etes pas membre.' using hint = 'error.publish.other_library';
  end if;
  perform public.sync_exemplar_draft_holdings_bridge(p_draft_id);

  select * into v_draft from public.exemplar_drafts where id = p_draft_id;
  if not found then
    raise exception 'Rascunho de exemplar não encontrado: %', p_draft_id;
  end if;
  if v_draft.status = 'cancelled' then
    raise exception 'Este rascunho de exemplar foi descartado.';
  end if;

  -- H19 (26/09/2026, IMP-21) : un exemplaire importé est rattaché à SON
  -- brouillon de notice. Il ne se publie pas avant elle (publish_book_draft le
  -- publie elle-même, dans la détention qu'elle vient de poser : la garde de
  -- révision du lot s'applique ainsi par transitivité).
  if v_draft.book_draft_id is not null then
    select bd.status into v_record_status from public.book_drafts bd where bd.id = v_draft.book_draft_id;
    if v_record_status is distinct from 'published' then
      raise exception 'exemplar_importado_antes_da_ficha' using hint = 'error.publish.item_before_record';
    end if;
    -- Restauré seul depuis la corbeille APRÈS la publication de sa notice, il
    -- n'a pas reçu la référence de la fiche (publish_book_draft n'aligne que
    -- les vivants) : il la prend ici (troisième revue, 27/09).
    if nullif(btrim(coalesce(v_draft.target_bib_ref, '')), '') is null then
      select b.bib_ref into v_draft.target_bib_ref
        from public.book_drafts bd join public.books b on b.id = bd.published_book_id
       where bd.id = v_draft.book_draft_id;
    end if;
  end if;
  -- Un exemplaire venu d'un import (promotion OU rapprochement) ne se publie
  -- jamais sans bibliothèque : le repli sur la bibliothèque principale de qui
  -- publie enverrait le fonds d'une compagne chez qui clique.
  if (v_draft.book_draft_id is not null or v_draft.import_staging_row_id is not null)
     and v_draft.target_library_id is null then
    raise exception 'exemplar_importado_sem_biblioteca' using hint = 'error.publish.item_without_library';
  end if;

  v_library_id := v_draft.target_library_id;

  if v_draft.target_holding_id is not null then
    select h.id, h.library_id,
           coalesce(nullif(trim(h.local_bib_ref), ''), b.bib_ref) as reference_code
      into v_holding
      from public.book_holdings h
      left join public.books b on b.id = h.book_id
     where h.id = v_draft.target_holding_id
     limit 1;
    if found then
      if v_library_id is not null and v_holding.library_id is distinct from v_library_id then
        raise exception 'O holding % pertence a outra biblioteca do que a biblioteca-alvo do rascunho.', v_draft.target_holding_id
          USING ERRCODE = '23514', HINT = 'error.catalog.holding_library_mismatch';
      end if;
      v_resolved_holding_id := v_holding.id;
      v_library_id := v_holding.library_id;
      v_resolved_bib_ref := v_holding.reference_code;
    end if;
  end if;

  if v_library_id is null and v_draft.published_exemplar_id is not null then
    select e.library_id into v_library_id
      from public.exemplares e where e.id = v_draft.published_exemplar_id;
  end if;

  if v_library_id is null then   -- B29
    v_library_id := private.fn_exemplar_draft_fallback_library(v_draft.book_draft_id, v_draft.import_staging_row_id, v_draft.created_by);
  end if;

  if v_library_id is null then
    select ulm.library_id into v_library_id
      from public.user_library_memberships ulm
     where ulm.user_id = auth.uid()
       and ulm.status = 'active'
       and ulm.role = any (array['librarian'::text, 'coordenador'::text])   -- H19
     order by ulm.is_primary desc nulls last, ulm.library_id
     limit 1;
  end if;

  if v_library_id is null then
    raise exception 'Nenhuma biblioteca ativa/principal encontrada para o usuário atual.';
  end if;

  -- H19 (27/09/2026, revue) : publier un exemplaire, c'est écrire dans le
  -- fonds d'une bibliothèque. La garde de tête ne demandait qu'un rôle de
  -- catalogage QUELQUE PART ; seule fn_next_tombo vérifiait l'appartenance,
  -- et un brouillon qui portait déjà son tombo la sautait. Même règle que
  -- fn_next_tombo et publish_book_draft : staff de la bibliothèque visée — et,
  -- pour une republication, de celle qui détient l'exemplaire aujourd'hui —
  -- ou administration du réseau. Placée AVANT le test du code d'origine : il
  -- ne renseigne pas sur le fonds d'une autre bibliothèque.
  if v_draft.published_exemplar_id is not null then
    select e.library_id, e.tombo, e.source_item_code into v_existing_library, v_existing_tombo, v_existing_code
      from public.exemplares e where e.id = v_draft.published_exemplar_id;
  end if;
  if auth.uid() is not null and not public.fn_caller_is_network_admin()
     and (not public.user_has_library_staff_role(auth.uid(), v_library_id)
          or (v_existing_library is not null
              and not public.user_has_library_staff_role(auth.uid(), v_existing_library))) then
    raise exception 'Ce rascunho est rattache a une bibliotheque dont vous n''etes pas membre (%).', v_library_id
      using hint = 'error.publish.other_library';
  end if;

  if v_resolved_holding_id is null then
    select * into v_bridge
      from public.resolve_library_holding_bridge(v_library_id, v_draft.target_bib_ref)
     limit 1;
    if found then
      v_resolved_holding_id := v_bridge.holding_id;
      v_resolved_bib_ref := coalesce(v_bridge.local_bib_ref, v_bridge.resolved_bib_ref);
    else
      v_resolved_bib_ref := nullif(trim(v_draft.target_bib_ref), '');
    end if;
  end if;

  select case when b.loanable then 'ambos' else 'consulta' end
    into v_seed_policy
    from public.book_holdings h
    join public.books b on b.id = h.book_id
   where h.id = v_resolved_holding_id;
  v_seed_policy := coalesce(v_seed_policy, 'consulta');

  -- Chantier 14 : tombo final. Si le brouillon n'en porte pas, on génère le
  -- prochain libre via fn_next_tombo (v_library_id garanti non-null ici).
  v_final_tombo := nullif(btrim(coalesce(v_draft.tombo, '')), '');
  -- H19 : republier un exemplaire déjà publié, dans la MÊME bibliothèque, garde
  -- son tombo (celui de l'étiquette collée) ; un brouillon importé n'en porte
  -- pas, et fn_next_tombo en aurait tiré un neuf à chaque passage. Un
  -- changement de bibliothèque (#cross-lib-reassign) renumérote, comme avant.
  if v_final_tombo is null and v_draft.published_exemplar_id is not null
     and v_existing_library is not distinct from v_library_id then
    v_final_tombo := nullif(btrim(coalesce(v_existing_tombo, '')), '');
  end if;
  if v_final_tombo is null then
    v_final_tombo := public.fn_next_tombo(v_library_id);
  end if;

  -- H19 : le code d'origine (code-barres PMB…) est unique PAR bibliothèque.
  -- Collision dite, jamais contournée : l'index partiel lèverait sinon une
  -- violation d'unicité que le repli du tombo ci-dessous prendrait pour la sienne.
  -- Le code contrôlé est celui qu'aura l'exemplaire : celui du brouillon, sinon
  -- celui qu'il porte déjà (un exemplaire importé réattribué à une autre
  -- bibliothèque l'emporte avec lui : 23505 brut sinon).
  v_item_code := coalesce(nullif(btrim(coalesce(v_draft.source_item_code, '')), ''), v_existing_code);
  if v_item_code is not null
     and exists (select 1 from public.exemplares e
                  where e.library_id = v_library_id
                    and e.source_item_code = v_item_code
                    and e.id is distinct from v_draft.published_exemplar_id) then
    raise exception 'codigo_de_origem_ja_usado: %', v_item_code
      using hint = 'error.publish.source_item_code_taken';
  end if;

  if v_draft.published_exemplar_id is null then
    -- #fix-tombo-stale (15/08/2026) : le tombo figé dans le brouillon peut être
    -- devenu obsolète (mutirão, double-clic, préfixe partagé). Sur collision
    -- d'unicité (forcément le tombo — seul index unique hors PK), on régénère un
    -- tombo libre et on réessaie une fois. fn_next_tombo est global-safe.
    begin
      insert into public.exemplares (
        bib_ref, tombo, shelf_location,
        label_title_override, label_author_override, label_cdd_override, label_note,
        notes, library_id, holding_id,
        circulation_policy, visibility,
        acquisition_mode, acquisition_date, provenance_note, source_library, source_item_code,
        created_at, updated_at
      ) values (
        coalesce(v_resolved_bib_ref, v_draft.target_bib_ref),
        v_final_tombo, v_draft.shelf_location,
        v_draft.label_title_override, v_draft.label_author_override, v_draft.label_cdd_override, v_draft.label_note,
        v_draft.notes, v_library_id, v_resolved_holding_id,
        coalesce(v_draft.circulation_policy, v_seed_policy),
        coalesce(v_draft.visibility, 'public'),
        v_draft.acquisition_mode, v_draft.acquisition_date, v_draft.provenance_note, v_draft.source_library, v_draft.source_item_code,
        now(), now()
      )
      returning id into v_exemplar_id;
    exception when unique_violation then
      -- H19 : ne réessayer que sur une collision de TOMBO ; toute autre
      -- violation d'unicité remonte telle quelle.
      get stacked diagnostics v_constraint = constraint_name;
      if v_constraint is distinct from 'exemplares_unique_tombo' then
        raise;
      end if;
      v_final_tombo := public.fn_next_tombo(v_library_id);
      insert into public.exemplares (
        bib_ref, tombo, shelf_location,
        label_title_override, label_author_override, label_cdd_override, label_note,
        notes, library_id, holding_id,
        circulation_policy, visibility,
        acquisition_mode, acquisition_date, provenance_note, source_library, source_item_code,
        created_at, updated_at
      ) values (
        coalesce(v_resolved_bib_ref, v_draft.target_bib_ref),
        v_final_tombo, v_draft.shelf_location,
        v_draft.label_title_override, v_draft.label_author_override, v_draft.label_cdd_override, v_draft.label_note,
        v_draft.notes, v_library_id, v_resolved_holding_id,
        coalesce(v_draft.circulation_policy, v_seed_policy),
        coalesce(v_draft.visibility, 'public'),
        v_draft.acquisition_mode, v_draft.acquisition_date, v_draft.provenance_note, v_draft.source_library, v_draft.source_item_code,
        now(), now()
      )
      returning id into v_exemplar_id;
    end;
  else
    update public.exemplares
       set bib_ref = coalesce(v_resolved_bib_ref, v_draft.target_bib_ref),
           tombo = coalesce(v_final_tombo, public.exemplares.tombo),
           shelf_location = v_draft.shelf_location,
           label_title_override = v_draft.label_title_override,
           label_author_override = v_draft.label_author_override,
           label_cdd_override = v_draft.label_cdd_override,
           label_note = v_draft.label_note,
           notes = v_draft.notes,
           library_id = coalesce(v_library_id, public.exemplares.library_id),
           holding_id = coalesce(v_resolved_holding_id, public.exemplares.holding_id),
           circulation_policy = coalesce(v_draft.circulation_policy, public.exemplares.circulation_policy),
           visibility = coalesce(v_draft.visibility, public.exemplares.visibility),
           acquisition_mode = coalesce(v_draft.acquisition_mode, public.exemplares.acquisition_mode),
           acquisition_date = coalesce(v_draft.acquisition_date, public.exemplares.acquisition_date),
           provenance_note  = coalesce(v_draft.provenance_note,  public.exemplares.provenance_note),
           source_library   = coalesce(v_draft.source_library,   public.exemplares.source_library),
           source_item_code = coalesce(v_draft.source_item_code, public.exemplares.source_item_code),
           updated_at = now()
     where id = v_draft.published_exemplar_id
    returning id into v_exemplar_id;
  end if;

  update public.exemplar_drafts
     set published_exemplar_id = v_exemplar_id,
         tombo = v_final_tombo,     -- H19 : le tombo réellement posé (republication, formulaire)
         target_library_id = coalesce(v_library_id, target_library_id),
         target_holding_id = coalesce(v_resolved_holding_id, target_holding_id),
         target_bib_ref = coalesce(v_resolved_bib_ref, target_bib_ref),
         status = 'published',
         label_status = 'ready',
         updated_by = coalesce(v_draft.updated_by, auth.uid()),
         updated_at = now()
   where id = p_draft_id;

  -- H20 (27/09/2026) : un exemplaire RAPPROCHÉ (sa ligne d'import désignait une
  -- notice déjà au catalogue) : le numéro que la source donnait à cette
  -- notice, à la bibliothèque de l'exemplaire, sur la notice existante. La
  -- ligne d'import reste tant que l'exemplaire attend (fn_import_delete_run).
  if v_draft.import_staging_row_id is not null and v_draft.book_draft_id is null then
    perform ingest.fn_record_book_external_id(
      coalesce((select h.book_id from public.exemplares e
                  join public.book_holdings h on h.id = e.holding_id
                 where e.id = v_exemplar_id),
               (select b.id from public.books b
                 where b.bib_ref = coalesce(v_resolved_bib_ref, v_draft.target_bib_ref) limit 1)),
      v_library_id,
      (select r.source_id from ingest.partner_catalog_staging_rows sr
         join ingest.partner_catalog_import_runs r on r.id = sr.run_id
        where sr.id = v_draft.import_staging_row_id),
      (select sr.external_key from ingest.partner_catalog_staging_rows sr
        where sr.id = v_draft.import_staging_row_id));
  end if;

  return v_exemplar_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_fusion_notices(p_canonical_id bigint, p_duplicate_id bigint, p_champs text[] DEFAULT '{}'::text[], p_reprendre_vides boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_catalog'
AS $function$
declare
  v_c         public.books%rowtype;   -- la notice gardée, AVANT la fusion
  v_d         public.books%rowtype;   -- le doublon
  v_snap      jsonb;
  v_col       text;
  v_n         int;
  v_choisis   text[] := '{}';
  v_repris    text[] := '{}';
  v_sujets    int := 0;
  v_contrib   int := 0;
  v_ecartes   int := 0;
  v_ouverts   bigint[];
  dh          record;
  v_ch        bigint;
  v_ref_avant text;
  v_ref_apres text;
begin
  IF NOT public.fn_is_dedup_arbiter() THEN
    RAISE EXCEPTION 'Arbitragem reservada à coordenação.'
      USING ERRCODE = '42501', HINT = 'error.catalog.arbiter_only';
  END IF;

  -- Garde de rattachement (2026-08-20, durcie le 2026-08-21) : fusionner deux
  -- notices qui appartiennent à d'autres bibliothèques que la sienne engage des
  -- collectifs dont on n'est pas membre.
  IF NOT EXISTS (SELECT 1 FROM public.network_administrators na
                  WHERE na.user_id = auth.uid() AND na.status = 'active')
     AND EXISTS (SELECT 1 FROM public.book_holdings h
                 WHERE h.book_id IN (p_canonical_id, p_duplicate_id))
     AND NOT EXISTS (
       SELECT 1
       FROM public.book_holdings h
       JOIN public.user_library_memberships m
         ON m.library_id = h.library_id
        AND m.user_id = auth.uid()
        AND m.status = 'active'
        AND m.role = 'coordenador'
       WHERE h.book_id IN (p_canonical_id, p_duplicate_id)
     ) THEN
    RAISE EXCEPTION 'Fusao restrita a coordenacao de uma das bibliotecas detentoras (ou a administracao da rede).'
      USING ERRCODE = '42501', HINT = 'error.catalog.merge_not_related';
  END IF;

  IF p_canonical_id = p_duplicate_id THEN
    RAISE EXCEPTION 'Canonico e duplicado identicos.';
  END IF;
  SELECT * INTO v_d FROM public.books WHERE id = p_duplicate_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Duplicado % inexistente.', p_duplicate_id;
  END IF;
  SELECT * INTO v_c FROM public.books WHERE id = p_canonical_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Canonico % inexistente.', p_canonical_id;
  END IF;

  -- 0. Le doublon, gardé ENTIER, avant tout changement.
  v_snap := jsonb_build_object(
    'duplicate_titulo', v_d.titulo,
    'notice', to_jsonb(v_d),
    'sujets', (select coalesce(jsonb_agg(to_jsonb(s) order by s.ord), '[]'::jsonb)
                 from public.book_subjects s where s.book_id = p_duplicate_id),
    'contributeurs', (select coalesce(jsonb_agg(to_jsonb(x) order by x.position), '[]'::jsonb)
                        from public.book_contributors x where x.book_id = p_duplicate_id),
    'contexte_catalogage', (select to_jsonb(x) from public.book_catalog_context x where x.book_id = p_duplicate_id),
    'fonds', (select coalesce(jsonb_agg(to_jsonb(h)), '[]'::jsonb)
                from public.book_holdings h where h.book_id = p_duplicate_id),
    'exemplaires', (select coalesce(jsonb_agg(to_jsonb(e)), '[]'::jsonb)
                      from public.exemplares e join public.book_holdings h on h.id = e.holding_id
                     where h.book_id = p_duplicate_id),
    'brouillons', (select coalesce(jsonb_agg(jsonb_build_object('id', d.id, 'status', d.status, 'action', d.action)), '[]'::jsonb)
                     from public.book_drafts d where d.published_book_id = p_duplicate_id),
    'couverture_proposee', (select to_jsonb(cp) from public.cover_proposals cp where cp.book_id = p_duplicate_id));

  -- 1. Les champs CHOISIS (assistant) : la valeur du doublon remplace. La
  --    validation (champ inconnu, non reprenable) est faite par l'appelant.
  for v_col in select distinct c from unnest(coalesce(p_champs, '{}'::text[])) c
                where nullif(btrim(c), '') is not null
  loop
    execute format('update public.books g set %1$I = d.%1$I from public.books d where g.id = $1 and d.id = $2', v_col)
      using p_canonical_id, p_duplicate_id;
    v_choisis := v_choisis || v_col;
  end loop;

  -- 2. Les champs VIDES de la notice gardée (merge_book) : ceux du doublon.
  --    Jamais par-dessus une valeur : la notice gardée décide. Un titre de
  --    périodique (serial_id) ne se pose que sur un fascicule ou un article.
  if p_reprendre_vides then
    for v_col in
      select c.column_name from information_schema.columns c
       where c.table_schema = 'public' and c.table_name = 'books' and c.is_generated = 'NEVER'
         and c.column_name <> all (public.fn_dedup_non_transferable_fields())
         and c.column_name <> all (v_choisis)
         and (c.column_name <> 'serial_id' or v_c.tipo_material in ('periodico', 'artigo'))
       order by c.ordinal_position
    loop
      execute format(
        'update public.books g set %1$I = d.%1$I from public.books d
          where g.id = $1 and d.id = $2
            and nullif(btrim(coalesce(g.%1$I::text, '''')), '''') is null
            and nullif(btrim(coalesce(d.%1$I::text, '''')), '''') is not null', v_col)
        using p_canonical_id, p_duplicate_id;
      get diagnostics v_n = row_count;
      if v_n > 0 then v_repris := v_repris || v_col; end if;
    end loop;
  end if;

  -- 3. Les brouillons OUVERTS de la notice gardée reçoivent ce qu'elle vient de
  --    recevoir, là où ils n'ont rien changé (valeur vide, ou encore celle de
  --    la notice avant la fusion) : publiés ensuite, ils l'auraient effacé.
  select array_agg(d.id) into v_ouverts
    from public.book_drafts d
   where d.published_book_id = p_canonical_id and d.status not in ('published', 'cancelled');
  if v_ouverts is not null then
    for v_col in
      select c from unnest(v_choisis || v_repris) c
       where exists (select 1 from information_schema.columns b
                       join information_schema.columns bd
                         on bd.table_schema = 'public' and bd.table_name = 'book_drafts'
                        and bd.column_name = b.column_name and bd.data_type = b.data_type
                      where b.table_schema = 'public' and b.table_name = 'books' and b.column_name = c)
    loop
      execute format(
        'update public.book_drafts bd set %1$I = g.%1$I
           from public.books g
          where g.id = $1 and bd.id = any ($2)
            and (nullif(btrim(coalesce(bd.%1$I::text, '''')), '''') is null
                 or bd.%1$I::text is not distinct from $3)
            and (%2$L <> ''serial_id'' or bd.tipo_material in (''periodico'', ''artigo''))', v_col, v_col)
        using p_canonical_id, v_ouverts, (to_jsonb(v_c) ->> v_col);
    end loop;
  end if;

  -- 4. Sujets et contributeur·rices du doublon qui manquent — à la notice
  --    gardée, et à ses brouillons ouverts (leur publication les remplace).
  insert into public.book_subjects (book_id, subject_id, ord)
  select p_canonical_id, s.subject_id,
         coalesce((select max(t.ord) from public.book_subjects t where t.book_id = p_canonical_id), 0)
           + row_number() over (order by s.ord, s.subject_id)
    from public.book_subjects s
   where s.book_id = p_duplicate_id
     and not exists (select 1 from public.book_subjects t
                      where t.book_id = p_canonical_id and t.subject_id = s.subject_id);
  get diagnostics v_sujets = row_count;

  insert into public.book_contributors (book_id, author_id, position, name, role, is_primary)
  select p_canonical_id, x.author_id,
         coalesce((select max(t.position) from public.book_contributors t where t.book_id = p_canonical_id), 0)
           + row_number() over (order by x.position, x.id),
         x.name, x.role, false
    from public.book_contributors x
   where x.book_id = p_duplicate_id
     and not exists (select 1 from public.book_contributors t
                      where t.book_id = p_canonical_id
                        and coalesce(t.role, '') = coalesce(x.role, '')
                        and ((t.author_id is not null and t.author_id = x.author_id)
                             or public.fn_normalize_name(t.name) = public.fn_normalize_name(x.name)));
  get diagnostics v_contrib = row_count;

  if v_ouverts is not null then
    insert into public.book_draft_subjects (book_draft_id, subject_id, ord)
    select bd, s.subject_id,
           coalesce((select max(t.ord) from public.book_draft_subjects t where t.book_draft_id = bd), 0)
             + row_number() over (partition by bd order by s.ord, s.subject_id)
      from unnest(v_ouverts) bd
      cross join public.book_subjects s
     where s.book_id = p_duplicate_id
       and not exists (select 1 from public.book_draft_subjects t
                        where t.book_draft_id = bd and t.subject_id = s.subject_id);

    -- Un brouillon sans contributeur·rices ne touche pas ceux de la notice à la
    -- publication (fn_sync_book_contributors_on_publish) : on ne lui en ajoute pas.
    insert into public.book_draft_contributors (draft_id, author_id, position, name, role, is_primary)
    select bd, x.author_id,
           coalesce((select max(t.position) from public.book_draft_contributors t where t.draft_id = bd), 0)
             + row_number() over (partition by bd order by x.position, x.id),
           x.name, x.role, false
      from unnest(v_ouverts) bd
      cross join public.book_contributors x
     where x.book_id = p_duplicate_id
       and exists (select 1 from public.book_draft_contributors t0 where t0.draft_id = bd)
       and not exists (select 1 from public.book_draft_contributors t
                        where t.draft_id = bd
                          and coalesce(t.role, '') = coalesce(x.role, '')
                          and ((t.author_id is not null and t.author_id = x.author_id)
                               or public.fn_normalize_name(t.name) = public.fn_normalize_name(x.name)));
  end if;

  -- 5. Brouillons du doublon : l'ouvert est écarté (rattaché puis publié, il
  --    écraserait la notice gardée) ; tous suivent la notice gardée.
  update public.book_drafts set status = 'cancelled'
   where published_book_id = p_duplicate_id and status not in ('published', 'cancelled');
  get diagnostics v_ecartes = row_count;
  update public.book_drafts set published_book_id = p_canonical_id where published_book_id = p_duplicate_id;

  -- 6. Fonds et exemplaires. Un fonds du doublon dans une bibliothèque où la
  --    notice gardée en a déjà un : ses exemplaires et ses lignes rejoignent
  --    celui-ci (sa référence locale et ses notes aussi, si le fonds gardé n'en
  --    a pas), et il disparaît. Sinon il passe sous la notice gardée. Dans les
  --    deux cas la référence des exemplaires suit par déclencheur (fonds
  --    modifié) ; celle des lignes déplacées suit ici.
  for dh in select * from public.book_holdings where book_id = p_duplicate_id loop
    v_ref_avant := coalesce(nullif(btrim(dh.local_bib_ref), ''), v_d.bib_ref);
    select id into v_ch from public.book_holdings
     where book_id = p_canonical_id and library_id = dh.library_id order by id limit 1;
    if v_ch is not null then
      update public.exemplares set holding_id = v_ch where holding_id = dh.id;
      update public.exemplar_drafts            set target_holding_id = v_ch where target_holding_id = dh.id;
      update public.emprestimo_itens_v2        set holding_id = v_ch where holding_id = dh.id;
      update public.reserva_linhas_v2          set holding_id = v_ch where holding_id = dh.id;
      update public.interlibrary_loan_items_v2 set holding_id = v_ch where holding_id = dh.id;
      update public.consulta_linhas_v2         set holding_id = v_ch where holding_id = dh.id;
      delete from public.book_holdings where id = dh.id;
      -- (après la suppression : la référence locale est unique par bibliothèque)
      update public.book_holdings h
         set local_bib_ref = coalesce(nullif(btrim(h.local_bib_ref), ''), nullif(btrim(dh.local_bib_ref), '')),
             notes         = coalesce(nullif(btrim(h.notes), ''), dh.notes)
       where h.id = v_ch
         and ((nullif(btrim(h.local_bib_ref), '') is null and nullif(btrim(dh.local_bib_ref), '') is not null)
              or (nullif(btrim(h.notes), '') is null and nullif(btrim(dh.notes), '') is not null));
      select coalesce(nullif(btrim(h.local_bib_ref), ''), g.bib_ref) into v_ref_apres
        from public.book_holdings h join public.books g on g.id = h.book_id where h.id = v_ch;
      update public.emprestimo_itens_v2        set bib_ref = v_ref_apres where holding_id = v_ch and bib_ref = v_ref_avant;
      update public.reserva_linhas_v2          set bib_ref = v_ref_apres where holding_id = v_ch and bib_ref = v_ref_avant;
      update public.interlibrary_loan_items_v2 set bib_ref = v_ref_apres where holding_id = v_ch and bib_ref = v_ref_avant;
      update public.consulta_linhas_v2         set bib_ref = v_ref_apres where holding_id = v_ch and bib_ref = v_ref_avant;
    else
      -- Le déclencheur du fonds aligne exemplaires et lignes sur la nouvelle notice.
      update public.book_holdings set book_id = p_canonical_id where id = dh.id;
    end if;
    v_ch := null;
  end loop;
  -- Les exemplaires encore à créer qui visaient le doublon par sa référence.
  update public.exemplar_drafts set target_bib_ref = v_c.bib_ref
   where target_bib_ref = v_d.bib_ref and status in ('draft', 'ready')
     and v_d.bib_ref is not null and v_c.bib_ref is not null;

  -- 7. Tout ce qui désigne encore le doublon suit la notice gardée.
  update public.emprestimo_itens_v2        set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.reserva_linhas_v2          set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.interlibrary_loan_items_v2 set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.consulta_linhas_v2         set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.digital_assets             set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.ill_digital_shares         set book_id = p_canonical_id where book_id = p_duplicate_id;
  update public.work_titles                set source_book_id = p_canonical_id where source_book_id = p_duplicate_id;
  update ingest.partner_catalog_staging_rows set proposed_book_id = p_canonical_id where proposed_book_id = p_duplicate_id;
  update public.audio_tracks a
     set book_id = p_canonical_id,
         position = a.position + coalesce((select max(t.position) from public.audio_tracks t where t.book_id = p_canonical_id), 0)
   where a.book_id = p_duplicate_id;
  delete from public.user_wishlist w
   where w.book_id = p_duplicate_id
     and exists (select 1 from public.user_wishlist w2 where w2.user_id = w.user_id and w2.book_id = p_canonical_id);
  update public.user_wishlist set book_id = p_canonical_id where book_id = p_duplicate_id;
  -- Une par notice : celle du doublon ne vaut que si la notice gardée n'en a pas.
  update public.cover_proposals set book_id = p_canonical_id
   where book_id = p_duplicate_id
     and not exists (select 1 from public.cover_proposals where book_id = p_canonical_id);
  update public.book_catalog_context set book_id = p_canonical_id
   where book_id = p_duplicate_id
     and not exists (select 1 from public.book_catalog_context where book_id = p_canonical_id);

  -- H20 (revue du 28/09/2026) : les identifiants d'origine du doublon (le
  -- numéro que la source de chaque bibliothèque lui donnait) passent à la
  -- notice gardée ; la suppression ci-dessous les emportait en cascade. Pas de
  -- conflit possible : la clé unique (bibliothèque, schéma, valeur) ne
  -- contient pas la notice.
  update public.book_external_ids set book_id = p_canonical_id, updated_at = now()
   where book_id = p_duplicate_id;

  -- 8. La trace : le doublon entier, et ce que la fusion a repris.
  insert into public.merge_log (entity_type, canonical_id, duplicate_id, details, merged_by)
  values ('book', p_canonical_id, p_duplicate_id,
          v_snap || jsonb_build_object(
            'champs_choisis', to_jsonb(v_choisis), 'champs_repris', to_jsonb(v_repris),
            'sujets_repris', v_sujets, 'contributeurs_repris', v_contrib,
            'brouillons_ecartes', v_ecartes),
          auth.uid());

  -- 9. Supprimer le doublon (cascade : ce qui n'a pas été repris, et qui est
  --    dans merge_log), recalculer la disponibilité.
  delete from public.books where id = p_duplicate_id;
  perform public.fn_v2_recompute_holdings_availability(null, array[p_canonical_id]);

  return jsonb_build_object(
    'champs_choisis', to_jsonb(v_choisis), 'champs_repris', to_jsonb(v_repris),
    'sujets_repris', v_sujets, 'contributeurs_repris', v_contrib, 'brouillons_ecartes', v_ecartes);
end;
$function$;

CREATE OR REPLACE FUNCTION api.merge_draft_into_book(p_draft_id bigint, p_book_id bigint, p_fields jsonb DEFAULT '{}'::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_draft         public.book_drafts%rowtype;
  v_book_bib_ref  text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.user_library_memberships m
    WHERE m.user_id = auth.uid()
      AND m.role = ANY (ARRAY['librarian'::text, 'coordenador'::text])
  ) THEN
    RAISE EXCEPTION 'Acesso restrito ao staff de catalogacao.'
      USING HINT = 'error.merge.staff_only';
  END IF;

  SELECT * INTO v_draft FROM public.book_drafts WHERE id = p_draft_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Rascunho % inexistente.', p_draft_id
      USING HINT = 'error.merge.draft_not_found';
  END IF;
  -- B29 (CAT-E18) : on n'absorbe que ses propres brouillons — avant le
  -- contrôle de statut, qui renseignerait sur celui d'autrui.
  IF NOT coalesce(public.fn_caller_can_edit_book_draft(p_draft_id), false) THEN
    RAISE EXCEPTION 'Rascunho de outra biblioteca.' USING HINT = 'error.catalog.draft_other_library';
  END IF;
  IF v_draft.status NOT IN ('draft', 'ready') THEN
    RAISE EXCEPTION 'Rascunho % nao esta na fila (status=%).', p_draft_id, v_draft.status
      USING HINT = 'error.merge.draft_not_in_queue';
  END IF;

  SELECT bib_ref INTO v_book_bib_ref FROM public.books WHERE id = p_book_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Livro % inexistente.', p_book_id
      USING HINT = 'error.merge.book_not_found';
  END IF;

  UPDATE public.books SET
    titulo    = COALESCE(p_fields->>'titulo',    titulo),
    subtitulo = COALESCE(p_fields->>'subtitulo', subtitulo),
    autor     = COALESCE(p_fields->>'autor',     autor),
    isbn      = COALESCE(p_fields->>'isbn',      isbn),
    ano       = COALESCE(p_fields->>'ano',       ano),
    editora   = COALESCE(p_fields->>'editora',   editora),
    cdd       = COALESCE(p_fields->>'cdd',       cdd),
    colecao   = COALESCE(p_fields->>'colecao',   colecao),
    idioma    = COALESCE(p_fields->>'idioma',    idioma),
    updated_by = auth.uid(), updated_at = now(), last_cataloged_at = now()
  WHERE id = p_book_id;

  -- H19 (27/09/2026) : les exemplaires importés du brouillon absorbé vont sur
  -- la fiche existante, comme ceux d'un rapprochement : sans notice
  -- (book_draft_id nul), avec la référence de la fiche ; leur bibliothèque et
  -- leur ligne importée restent (publish_exemplar_draft exige alors une
  -- bibliothèque, et d'en être staff). Sans cela l'écart du brouillon les
  -- emportait avec lui.
  UPDATE public.exemplar_drafts SET
    book_draft_id = NULL, target_bib_ref = v_book_bib_ref, target_holding_id = NULL, updated_at = now()
  WHERE book_draft_id = p_draft_id AND status IN ('draft', 'ready');

  UPDATE public.book_drafts SET
    published_book_id = p_book_id,
    bib_ref           = COALESCE(bib_ref, v_book_bib_ref),
    action            = 'update',
    status            = 'cancelled',
    updated_by = auth.uid(), updated_at = now()
  WHERE id = p_draft_id;

  -- H20 (revue du 28/09/2026) : un brouillon importé absorbé par une fiche
  -- existante (celle d'une autre bibliothèque, souvent) lui laisse le numéro
  -- que sa source lui donnait, à la bibliothèque du brouillon.
  IF coalesce(v_draft.marc_json, '{}'::jsonb) ? 'ingest' THEN
    PERFORM ingest.fn_record_book_external_id(
      p_book_id, public.fn_book_draft_library(p_draft_id),
      coalesce((v_draft.marc_json->'ingest'->>'source_id')::bigint,
               (SELECT r.source_id FROM ingest.partner_catalog_import_runs r
                 WHERE r.id = (v_draft.marc_json->'ingest'->>'run_id')::bigint)),
      ingest.fn_h20_identifiant_d_origine(p_draft_id));
  END IF;

  INSERT INTO public.merge_log (entity_type, canonical_id, duplicate_id, details, merged_by)
  VALUES ('book_draft', p_book_id, p_draft_id,
          jsonb_build_object('scenario', 'draft_into_book',
                             'fields', COALESCE(p_fields, '{}'::jsonb)),
          auth.uid());

  RETURN p_book_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_import_delete_run(p_run_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'ingest', 'auth'
AS $function$
DECLARE
  v_actor public.my_access%rowtype;
  v_run   ingest.partner_catalog_import_runs%rowtype;
  v_lots  bigint[];
  v_actifs bigint;
  v_noms  text;
BEGIN
  SELECT * INTO v_actor FROM public.my_access LIMIT 1;
  IF v_actor.library_id IS NULL OR NOT coalesce(v_actor.can_access_painel, false) THEN
    RAISE EXCEPTION 'Acesso bibliotecario obrigatorio.';
  END IF;
  IF v_actor.role IS DISTINCT FROM 'coordenador' AND NOT public.fn_caller_is_network_admin() THEN
    RAISE EXCEPTION 'Acesso restrito ao coordenador da biblioteca.';
  END IF;

  SELECT * INTO v_run FROM ingest.partner_catalog_import_runs WHERE id = p_run_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Run % introuvable', p_run_id;
  END IF;
  IF v_run.library_id IS DISTINCT FROM v_actor.library_id
     AND NOT public.fn_caller_is_network_admin() THEN
    RAISE EXCEPTION 'Run % introuvable', p_run_id;
  END IF;

  -- Le lot de catalogage ne CASCADE pas : il est dans public, le run dans
  -- ingest. Tant qu'il retient du travail vivant, on refuse plutot que de le
  -- laisser sans provenance. La corbeille du lot, elle, ne bloque pas.
  SELECT array_agg(DISTINCT m.batch_id) INTO v_lots
    FROM ingest.partner_catalog_row_to_draft m
   WHERE m.run_id = p_run_id AND m.batch_id IS NOT NULL;

  IF v_lots IS NOT NULL AND array_length(v_lots, 1) > 0 THEN
    SELECT (SELECT count(*) FROM public.book_drafts     d
             WHERE d.batch_id = ANY(v_lots) AND d.status <> 'cancelled')
         + (SELECT count(*) FROM public.author_drafts   d
             WHERE d.batch_id = ANY(v_lots) AND d.status <> 'cancelled')
         + (SELECT count(*) FROM public.exemplar_drafts d
             WHERE d.batch_id = ANY(v_lots) AND d.status <> 'cancelled')
      INTO v_actifs;

    IF v_actifs > 0 THEN
      SELECT string_agg(b.name, ' ; ' ORDER BY b.id) INTO v_noms
        FROM public.catalog_batches b WHERE b.id = ANY(v_lots);
      RAISE EXCEPTION
        'Run % : le lot de catalogage « % » retient encore % brouillon(s) actif(s). Traiter le lot avant de supprimer le run.',
        p_run_id, coalesce(v_noms, '?'), v_actifs
        USING HINT = 'error.import.run_has_drafts';
    END IF;
  END IF;

  -- H20 (revue du 28/09/2026) : un exemplaire RAPPROCHÉ (hors des lots
  -- ci-dessus : il n'a pas de notice importée) lit, à sa publication, le numéro
  -- d'origine sur sa ligne d'import. Tant qu'il attend, le run reste.
  SELECT count(*) INTO v_actifs
    FROM public.exemplar_drafts x
    JOIN ingest.partner_catalog_staging_rows sr ON sr.id = x.import_staging_row_id
   WHERE sr.run_id = p_run_id AND x.status IN ('draft', 'ready');
  IF v_actifs > 0 THEN
    RAISE EXCEPTION
      'Run % : % exemplaire(s) rapproché(s) attendent encore leur publication. Les publier ou les écarter avant de supprimer le run.',
      p_run_id, v_actifs
      USING HINT = 'error.import.run_has_drafts';
  END IF;

  -- Objet storage : la suppression DIRECTE de storage.objects est interdite par
  -- Supabase ('Direct deletion from storage tables is not allowed') -> best-effort,
  -- on ignore l'echec (fichier eventuellement orphelin, non bloquant).
  IF v_run.bucket_id IS NOT NULL AND v_run.storage_path IS NOT NULL THEN
    BEGIN
      DELETE FROM storage.objects
       WHERE bucket_id = v_run.bucket_id AND name = v_run.storage_path;
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;
  END IF;

  -- Le run -> CASCADE sur import_files / staging_rows / row_to_draft / dispatch_log
  DELETE FROM ingest.partner_catalog_import_runs WHERE id = p_run_id;

  RETURN jsonb_build_object('ok', true, 'deleted_run', p_run_id);
END;
$function$;

-- ── 7. L'existant ──────────────────────────────────────────────────────────
-- updated_at n'est pas touché : effacer un faux identifiant n'est pas un geste
-- de catalogage.
ALTER TABLE public.book_drafts DISABLE TRIGGER trg_book_drafts_touch_updated_at;
DO $h20$
DECLARE v_effaces integer; v_repris integer;
BEGIN
  v_effaces := ingest.fn_h20_effacer_faux_identifiants();
  v_repris  := ingest.fn_h20_reprise_identifiants();
  RAISE NOTICE 'H20 : % faux identifiant(s) d''origine effacé(s), % identifiant(s) repris sur des notices publiées.', v_effaces, v_repris;
END
$h20$;
ALTER TABLE public.book_drafts ENABLE TRIGGER trg_book_drafts_touch_updated_at;
