-- 20260617020229_opac_author_variant_forms_wikidata.sql
-- OPAC / fiche auteur — peuple authors.variant_forms (formes du nom) pour 9
-- auteur·rices identifié·es par wikidata_id mais sans variant_forms.
-- Source : API Wikidata (labels + alias), langues retenues : ar, ca, de, el, en, eo, es, fa, fr, he, it, ja, ko, ku, nl, pl, pt, ru, tr, uk, zh.
-- Généré par scripts/enrich-variant-forms-wikidata.cjs (le 2026-06-16).
-- Garde-fou : n'écrit QUE si variant_forms est encore vide (idempotent, ne
-- réécrit pas un enrichissement manuel ultérieur).
--
-- Session : Catalogue longue traîne (recherche + fiche auteur)

update authors set variant_forms = '{"ar":["إبراهام غولن"],"ca":["Abraham Guillén"],"de":["Abraham Guillén"],"en":["Abraham Guillén"],"eo":["Abraham Guillén"],"es":["Abraham Guillén"],"fr":["Abraham Guillén"],"it":["Abraham Guillén"],"nl":["Abraham Guillén"],"pl":["Abraham Guillén"],"pt":["Abraham Guillén","Abraham Guillén Sanz"],"ru":["Авраам Гильен","Гильен, Авраам"]}'::jsonb
  where id = 11 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Abraham GUILLÉN (Q205381)
update authors set variant_forms = '{"ar":["أفونسو شميت"],"ca":["Afonso Schmidt"],"de":["Afonso Schmidt"],"en":["Afonso Schmidt","Affonso Schmidt"],"es":["Afonso Schmidt"],"fr":["Afonso Schmidt"],"nl":["Afonso Schmidt"],"pt":["Afonso Schmidt","Afonso Frederico Schmidt"],"ru":["Афонсу Шмидт","Шмидт, Афонсу"],"tr":["Afonso Schmidt"]}'::jsonb
  where id = 10022 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Afonso SCHMIDT (Q4689387)
update authors set variant_forms = '{"ar":["ليو تولستوي","الكونت ليو نيكولاييفيتش تولستوي"],"ca":["Lev Tolstoi"],"de":["Lew Nikolajewitsch Tolstoi","Lev Nikolaevič Tolstoj","Leo Tolstoi","Lew Tolstoi","Lew Nikolajewitsch Graf Tolstoi"],"el":["Λέων Τολστόι","Λεφ Νικολάιεβιτς Τολστόι"],"en":["Leo Tolstoy","Count Lev Nikolayevich Tolstoy","Lev Nikolayevich Tolstoĭ","Leo Tolstoi","Tolstoĭ, Lev Nikolaevich, graf","Tolstoy, Leo, graf"],"eo":["Lev Tolstoj","Tolstojo","Leono Tolstojo","Leono, Grafo Tolstojo"],"es":["León Tolstói","Tolstoy","Tolstói","Lev Tolstói","Lev Nikoláyevich Tolstói"],"fa":["لئو تولستوی"],"fr":["Léon Tolstoï","Tolstoï, Léon","Leo Tolstoy","Leo Tolstoï","Lev Tolstoï","Tolstoi","Tolstoj, Lev Nikolaevič"],"he":["לב טולסטוי","לב ניקולאייביץ'' טולסטוי"],"it":["Lev Tolstoj","Lev Nikolàevič Tolstòj","Leone Tolstoi"],"ja":["レフ・トルストイ","レオ・トルストイ","トルストイ, レフ"],"ko":["레프 톨스토이","레프 니콜라예비치 톨스토이","레오 톨스토이","톨스토이"],"ku":["Lev Tolstoy"],"nl":["Lev Nikolajevitsj Tolstoj","Lev Tolstoj","Leo Tolstoi","Leo Tolstoy","Tolstoi","Tolstoj","Lev Nikolaevic Tolstoj"],"pl":["Lew Tołstoj","Lew Nikołajewicz Tołstoj"],"pt":["Liev Tolstói","Leão Tolstoi"],"ru":["Лев Николаевич Толстой","Толстой, Лев Николаевич","Лев Толстой","Толстой, Лев","Л. Н. Толстой"],"tr":["Lev Tolstoy"],"uk":["Толстой Лев Миколайович"],"zh":["列夫·托爾斯泰","列夫·托尔斯泰","列夫·尼古拉耶维奇·托尔斯泰","列夫·尼古拉耶維奇·托爾斯泰","托尔斯泰，Л.Н.","托爾斯泰","托尔斯泰，L.N.","托尔斯泰"]}'::jsonb
  where id = 10023 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Lev TOLSTÓI (Q7243)
update authors set variant_forms = '{"ar":["إميل آرماند"],"ca":["Émile Armand","Ernest-Lucien Juin"],"de":["Émile Armand","E. Armand"],"en":["E. Armand","Lucien Ernest Juin"],"eo":["Émile Armand"],"es":["E. Armand","Lucien Ernest Juin"],"fr":["E. Armand","Lucien Ernest Juin","Lucien Ernest"],"it":["Émile Armand"],"ja":["エミール・アルマン","エミール・アルマンド"],"nl":["Émile Armand"],"pl":["Émile Armand"],"pt":["Émile Armand"],"ru":["Эмиль Арман","Арман, Эмиль"],"tr":["Émile Armand"],"zh":["埃米尔·阿尔曼德","埃米尔·阿尔芒"]}'::jsonb
  where id = 10041 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Émile ARMAND (Q274891)
update authors set variant_forms = '{"ca":["Daniel Colson"],"de":["Daniel Colson"],"en":["Daniel Colson"],"eo":["Daniel Colson"],"es":["Daniel Colson"],"fr":["Daniel Colson"],"it":["Daniel Colson"],"nl":["Daniel Colson"],"pt":["Daniel Colson"],"tr":["Daniel Colson"]}'::jsonb
  where id = 10443 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Daniel COLSON (Q3013875)
update authors set variant_forms = '{"ca":["Alèssi Dell''Umbria"],"de":["Alèssi Dell''Umbria"],"en":["Alèssi Dell''Umbria"],"es":["Alèssi Dell''Umbria"],"fr":["Alèssi Dell''Umbria"],"it":["Alèssi Dell''Umbria"],"nl":["Alèssi Dell''Umbria"],"pt":["Alèssi Dell''Umbria"]}'::jsonb
  where id = 10495 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Alèssi DELL'UMBRIA (Q16170957)
update authors set variant_forms = '{"ar":["عبد الله أوجلان","عبدالله اوجلان","عبد الله اوگلان","عبدالله أوجلان","عبد الله اوجلان"],"ca":["Abdullah Öcalan","Apo","Serok"],"de":["Abdullah Öcalan"],"el":["Αμπντουλάχ Οτζαλάν","Αμπντουλάχ Οτσαλάν","Οτζαλάν"],"en":["Abdullah Öcalan","Apo","Öcalan"],"eo":["Abdullah Öcalan"],"es":["Abdullah Öcalan","Abdulá Öcalan"],"fa":["عبدالله اوجالان","اوجالان","عبدالله اوجلان","عبداله اوجالان"],"fr":["Abdullah Öcalan","Öcalan"],"he":["עבדוללה אג''לאן","עבדאללה אוצ''אלאן"],"it":["Abdullah Öcalan","Ocalan"],"ja":["アブドゥッラー・オジャラン","オジャラン","アポ"],"ko":["압둘라 외잘란"],"ku":["Abdullah Ocalan","Öcalan","Apo","Abdulah","Ebdulla Ocalan","Ebdila Ocelan","Ocelan","Evdille Ocalan","Abdullah","Abdulah Öcalan"],"nl":["Abdullah Öcalan","Abdulah Ocalan"],"pl":["Abdullah Öcalan"],"pt":["Abdullah Öcalan","Ocalan"],"ru":["Абдулла Оджалан","Оджалан, Абдулла","Оджалан, Абдуллах","Оджалан","Оджалан А.","Оджалан Абдулла","Абдуллах Оджалан","Оджалан Абдуллах"],"tr":["Abdullah Öcalan","Apo","Öcalan"],"uk":["Абдулла Оджалан"],"zh":["阿卜杜拉·奥贾兰","阿卜杜拉·厄贾兰"]}'::jsonb
  where id = 10973 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Abdullah ÖCALAN (Q191530)
update authors set variant_forms = '{"ar":["أنطوني بانيكوك","انطوني بانيكوك"],"ca":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"de":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"el":["Άντον Πάνεκουκ"],"en":["Anton Pannekoek","Antonie Pannekoek","Pannekoek","A. Pannekoek"],"eo":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"es":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"fa":["آنتون پانه‌کک","آنتون پانه کک","انتون پانهٔ کک","انتون پانه کک","آنتون پانهٔ کک","انتون پانه‌کک"],"fr":["Anton Pannekoek","Pannekoek","Antonie Pannekoek"],"he":["אנטון פנקוק"],"it":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"ja":["アントン・パンネクーク"],"ko":["안톤 판네쿡","안톤 파네쾨크"],"nl":["Anton Pannekoek","Antonie Pannekoek","Pannekoek","A. Pannekoek"],"pl":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"pt":["Anton Pannekoek","Antonie Pannekoek","Pannekoek"],"ru":["Антон Паннекук","Паннекук","Паннекук А.","Паннекук Антон","Паннекук, Антон"],"tr":["Antonie Pannekoek","Anton Pannekoek","Pannekoek"],"uk":["Антон Паннекук","Паннекук Антон","Антоні Паннекук"],"zh":["安東尼·潘涅庫克"]}'::jsonb
  where id = 11001 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Anton PANNEKOEK (Q347930)
update authors set variant_forms = '{"ca":["Antônio de Almeida Prado"],"de":["Antônio de Almeida Prado","PRADO, Antonio de Almeida"],"en":["Antônio de Almeida Prado","PRADO, Antonio de Almeida"],"es":["Antônio de Almeida Prado"],"fr":["Antônio de Almeida Prado"],"it":["Antônio de Almeida Prado"],"nl":["Antônio de Almeida Prado"],"pl":["Antônio de Almeida Prado"],"pt":["Antônio de Almeida Prado","PRADO, Antonio de Almeida"],"tr":["Antônio de Almeida Prado"]}'::jsonb
  where id = 11058 and (variant_forms is null or variant_forms in ('null'::jsonb,'[]'::jsonb,'{}'::jsonb)); -- Antônio de Almeida PRADO (Q9623207)
