-- =====================================================================
-- AnarBib — G19 lot 1 : correspondance entre bibliothèques — les données
-- Date    : 2026-10-08
-- Ref     : backlog v34 G19 ; REGISTRE CORR-1 à CORR-6 (lot 0, décisions de
--           Xavier du 08/10/2026).
--
-- Ce que c'est. Une coordination écrit à une autre bibliothèque dans un FIL
-- de l'app ; chaque message garde son texte et sa langue. Rien de tel
-- n'existait : l'entraide est un aller-retour, les échanges sont une
-- demande suivie d'une réponse, le PEB et les assemblées sont des gestes
-- structurés. Ce lot pose les données, les règles d'écriture et de lecture,
-- rien à l'écran (lot 2), aucune notification (lot 3).
--
-- Les règles, décidées au lot 0 :
--   CORR-1  les coordinations seules lisent et écrivent, au nom de LEUR
--           bibliothèque ; ni les bibliothécaires, ni les lectrices ;
--   CORR-2  (lot 3) le courriel va à l'adresse collective de la bibliothèque ;
--   CORR-3  (lot 5) traduction automatique avec consentement — les colonnes
--           lang / body_i18n / i18n_status sont posées ici, vides ;
--   CORR-4  pas de réponse par courriel au début ;
--   CORR-5  l'onglet s'appelle « Correspondance » ;
--   CORR-6  l'administration du réseau NE LIT PAS la correspondance des
--           bibliothèques (sauf comme coordination d'une bibliothèque du
--           fil) : ce sont des lettres entre collectifs, pas un journal de
--           la plateforme. Réversible par une décision au REGISTRE, pas par
--           un correctif.
--
-- Les tables (schéma public ; toutes au flux COURT de la sauvegarde #BG2,
-- comme reader_library_messages : du texte écrit par des personnes).
--   library_conversations              un fil : sujet, qui l'a ouvert, dernier message
--   library_conversation_participants  une bibliothèque par ligne, archivage propre à
--                                      chacune (un fil archivé chez A reste vivant chez B ;
--                                      un message nouveau le rend à toutes)
--   library_messages                   un message : bibliothèque expéditrice, auteur·ice,
--                                      corps (1 à 4 000), langue (dix locales), traduction
--   library_conversation_reads         ce que chaque personne a lu (dernier message lu)
--
-- Écritures : par les RPC DEFINER du schéma api SEULEMENT (ouvrir, envoyer,
-- archiver, marquer lu) — aucun droit d'écriture pour authenticated sur les
-- tables ; lecture par une politique, une permissive par (rôle, commande)
-- (B10). Jamais de suppression : un fil s'archive. Limite d'envoi : 30
-- messages par personne et par 24 h (le modèle de send_message_to_reader).
-- Pas de table temporaire (cache PostgREST). Droits : chaque fonction neuve
-- REVOKE … FROM PUBLIC, anon, authenticated puis GRANT nommé (api et public
-- n'ont pas les mêmes privilèges par défaut ; gardes T10/T12).
-- Suite : tests/sql/correspondance_lot1_tests.sql.
-- =====================================================================

-- ─────────────────────────────────────────────────────────────────────
-- 1. Les tables
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.library_conversations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject          text NOT NULL CONSTRAINT library_conversations_subject_check
                     CHECK (btrim(subject) <> '' AND char_length(subject) <= 200),
  created_by       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  last_message_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.library_conversations IS
  'G19 lot 1 (08/10/2026) : un fil de correspondance entre bibliothèques (CORR-1). Lecture : les coordinations des '
  'bibliothèques participantes seulement, par politique ; écriture : api.fn_correspondance_* (DEFINER). Jamais supprimé, '
  'archivé par bibliothèque (participants). Sauvegarde #BG2 : flux court (texte écrit par des personnes).';
CREATE INDEX IF NOT EXISTS library_conversations_created_by_idx ON public.library_conversations (created_by);
CREATE INDEX IF NOT EXISTS library_conversations_dernier_idx ON public.library_conversations (last_message_at DESC);

CREATE TABLE IF NOT EXISTS public.library_conversation_participants (
  conversation_id  bigint NOT NULL REFERENCES public.library_conversations(id) ON DELETE CASCADE,
  library_id       uuid   NOT NULL REFERENCES public.libraries(id) ON DELETE CASCADE,
  joined_at        timestamptz NOT NULL DEFAULT now(),
  archived_at      timestamptz,
  PRIMARY KEY (conversation_id, library_id)
);
COMMENT ON TABLE public.library_conversation_participants IS
  'G19 lot 1 : les bibliothèques d''un fil, une par ligne — l''archivage est propre à chacune ; un message nouveau le lève '
  'pour toutes. Une table de participantes (et non deux colonnes A/B) : elle ouvre la porte aux fils de cercle.';
CREATE INDEX IF NOT EXISTS library_conversation_participants_library_idx
  ON public.library_conversation_participants (library_id, archived_at);

CREATE TABLE IF NOT EXISTS public.library_messages (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  bigint NOT NULL REFERENCES public.library_conversations(id) ON DELETE CASCADE,
  library_id       uuid   NOT NULL REFERENCES public.libraries(id) ON DELETE CASCADE,   -- l'expéditrice
  author_id        uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  body             text NOT NULL CONSTRAINT library_messages_body_check
                     CHECK (char_length(btrim(body)) >= 1 AND char_length(body) <= 4000),
  lang             text NOT NULL CONSTRAINT library_messages_lang_check
                     CHECK (lang = ANY (ARRAY['pt-BR','fr','es','en','it','de','el','ca','eo','nl'])),
  body_i18n        jsonb,                                   -- lot 5 : { "<locale>": "<texte>" }, marquée automatique
  i18n_status      text NOT NULL DEFAULT 'none' CONSTRAINT library_messages_i18n_status_check
                     CHECK (i18n_status IN ('none', 'pending', 'done', 'error')),
  created_at       timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.library_messages IS
  'G19 lot 1 : un message d''un fil, au nom d''une bibliothèque participante, écrit par une de ses coordinations. '
  'Le texte reste tel qu''écrit, dans sa langue (lang, dix locales) ; body_i18n / i18n_status attendent le lot 5 '
  '(traduction avec consentement, CORR-3). Sauvegarde #BG2 : flux court.';
CREATE INDEX IF NOT EXISTS library_messages_conversation_idx ON public.library_messages (conversation_id, id);
CREATE INDEX IF NOT EXISTS library_messages_library_idx ON public.library_messages (library_id);
CREATE INDEX IF NOT EXISTS library_messages_author_idx ON public.library_messages (author_id, created_at);

CREATE TABLE IF NOT EXISTS public.library_conversation_reads (
  conversation_id       bigint NOT NULL REFERENCES public.library_conversations(id) ON DELETE CASCADE,
  user_id               uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  last_read_message_id  bigint NOT NULL DEFAULT 0,
  read_at               timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, user_id)
);
COMMENT ON TABLE public.library_conversation_reads IS
  'G19 lot 1 : ce que chaque personne a lu d''un fil (dernier message lu) — propre à la personne, pas à la bibliothèque.';
CREATE INDEX IF NOT EXISTS library_conversation_reads_user_idx ON public.library_conversation_reads (user_id);

DROP TRIGGER IF EXISTS trg_library_conversations_touch ON public.library_conversations;
CREATE TRIGGER trg_library_conversations_touch BEFORE UPDATE ON public.library_conversations
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────
-- 2. Qui coordonne, qui lit — deux aides
-- ─────────────────────────────────────────────────────────────────────
-- Une coordination ACTIVE de la bibliothèque, et elle seule (CORR-1, CORR-6) :
-- pas fn_team_caller_is_coordenador, qui ouvre à l'administration du réseau.
CREATE OR REPLACE FUNCTION public.fn_correspondance_coordonne(p_library_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_library_memberships m
     WHERE m.user_id = (SELECT auth.uid())
       AND m.library_id = p_library_id
       AND m.role = 'coordenador'
       AND m.status = 'active');
$$;
REVOKE EXECUTE ON FUNCTION public.fn_correspondance_coordonne(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_correspondance_coordonne(uuid) TO service_role;

-- Lire un fil : être coordination d'une de ses bibliothèques. DEFINER : la
-- politique de chaque table l'appelle, et une politique qui relirait la table
-- des participantes sous sa propre politique tournerait en rond.
CREATE OR REPLACE FUNCTION public.fn_correspondance_lit(p_conversation_id bigint)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.library_conversation_participants p
     WHERE p.conversation_id = p_conversation_id
       AND public.fn_correspondance_coordonne(p.library_id));
$$;
REVOKE EXECUTE ON FUNCTION public.fn_correspondance_lit(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_correspondance_lit(bigint) TO authenticated, service_role;

-- ─────────────────────────────────────────────────────────────────────
-- 3. Droits et politiques : lecture par les coordinations, écriture par les RPC
-- ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.library_conversations              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_conversation_participants  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_messages                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_conversation_reads         ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.library_conversations FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.library_conversations TO authenticated;
GRANT ALL ON public.library_conversations TO service_role;
REVOKE ALL ON public.library_conversation_participants FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.library_conversation_participants TO authenticated;
GRANT ALL ON public.library_conversation_participants TO service_role;
REVOKE ALL ON public.library_messages FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.library_messages TO authenticated;
GRANT ALL ON public.library_messages TO service_role;
REVOKE ALL ON public.library_conversation_reads FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.library_conversation_reads TO authenticated;
GRANT ALL ON public.library_conversation_reads TO service_role;

DROP POLICY IF EXISTS library_conversations_select_authenticated ON public.library_conversations;
CREATE POLICY library_conversations_select_authenticated ON public.library_conversations
  FOR SELECT TO authenticated USING (public.fn_correspondance_lit(id));
DROP POLICY IF EXISTS library_conversation_participants_select_authenticated ON public.library_conversation_participants;
CREATE POLICY library_conversation_participants_select_authenticated ON public.library_conversation_participants
  FOR SELECT TO authenticated USING (public.fn_correspondance_lit(conversation_id));
DROP POLICY IF EXISTS library_messages_select_authenticated ON public.library_messages;
CREATE POLICY library_messages_select_authenticated ON public.library_messages
  FOR SELECT TO authenticated USING (public.fn_correspondance_lit(conversation_id));
DROP POLICY IF EXISTS library_conversation_reads_select_authenticated ON public.library_conversation_reads;
CREATE POLICY library_conversation_reads_select_authenticated ON public.library_conversation_reads
  FOR SELECT TO authenticated USING (user_id = (SELECT auth.uid()));

-- ─────────────────────────────────────────────────────────────────────
-- 4. Les gestes (api, DEFINER) : ouvrir, envoyer, archiver, marquer lu
-- ─────────────────────────────────────────────────────────────────────
-- La langue d'un message : celle donnée, sinon celle du profil, sinon celle
-- de la bibliothèque, sinon pt-BR ; toujours l'une des dix.
CREATE OR REPLACE FUNCTION public.fn_correspondance_langue(p_lang text, p_library_id uuid)
RETURNS text
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE v text;
BEGIN
  v := nullif(btrim(coalesce(p_lang, '')), '');
  IF v IS NULL THEN
    SELECT pr.preferred_language INTO v FROM public.profiles pr WHERE pr.id = (SELECT auth.uid());
  END IF;
  IF v IS NULL OR v = '' THEN
    SELECT l.default_locale INTO v FROM public.libraries l WHERE l.id = p_library_id;
  END IF;
  v := coalesce(nullif(v, ''), 'pt-BR');
  IF v <> ALL (ARRAY['pt-BR','fr','es','en','it','de','el','ca','eo','nl']) THEN
    RAISE EXCEPTION 'lang_invalid: %', v USING errcode = '22023', hint = 'error.correspondance.lang_invalid';
  END IF;
  RETURN v;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.fn_correspondance_langue(text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_correspondance_langue(text, uuid) TO service_role;

-- Poser un message : les contrôles communs à « ouvrir » et « envoyer ».
-- Appelée par les deux RPC, jamais par l'API.
CREATE OR REPLACE FUNCTION public.fn_correspondance_poser_message(p_conversation_id bigint, p_library_id uuid, p_corps text, p_lang text)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE v_body text := btrim(coalesce(p_corps, '')); v_recent int; v_id bigint; v_lang text;
BEGIN
  IF char_length(v_body) < 1 THEN
    RAISE EXCEPTION 'empty_body' USING errcode = '22023', hint = 'error.correspondance.empty_body';
  END IF;
  IF char_length(v_body) > 4000 THEN
    RAISE EXCEPTION 'body_too_long' USING errcode = '22023', hint = 'error.correspondance.body_too_long';
  END IF;
  v_lang := public.fn_correspondance_langue(p_lang, p_library_id);
  -- Garde-fou large anti-boucle, le modèle de send_message_to_reader : une
  -- coordination est de confiance, trente messages par jour suffisent.
  SELECT count(*) INTO v_recent FROM public.library_messages m
   WHERE m.author_id = (SELECT auth.uid()) AND m.created_at > now() - interval '24 hours';
  IF v_recent >= 30 THEN
    RAISE EXCEPTION 'rate_limited' USING errcode = '53400', hint = 'error.correspondance.rate_limited';
  END IF;
  INSERT INTO public.library_messages (conversation_id, library_id, author_id, body, lang)
  VALUES (p_conversation_id, p_library_id, (SELECT auth.uid()), v_body, v_lang)
  RETURNING id INTO v_id;
  -- Un message nouveau rend le fil à toutes ses bibliothèques (archivage levé).
  UPDATE public.library_conversation_participants SET archived_at = NULL
   WHERE conversation_id = p_conversation_id AND archived_at IS NOT NULL;
  UPDATE public.library_conversations SET last_message_at = now() WHERE id = p_conversation_id;
  RETURN v_id;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.fn_correspondance_poser_message(bigint, uuid, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_correspondance_poser_message(bigint, uuid, text, text) TO service_role;

-- Ouvrir un fil : de MA bibliothèque (je la coordonne) vers une autre,
-- active ; le sujet et le premier message. Plusieurs fils sont possibles
-- entre deux mêmes bibliothèques, un par sujet, comme des lettres.
CREATE OR REPLACE FUNCTION api.fn_correspondance_ouvrir(p_library_id uuid, p_destinataire_id uuid, p_sujet text, p_corps text, p_lang text DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE v_sujet text := btrim(coalesce(p_sujet, '')); v_id bigint;
BEGIN
  IF NOT public.fn_correspondance_coordonne(p_library_id) THEN
    RAISE EXCEPTION 'not_coordinator' USING errcode = '42501', hint = 'error.correspondance.not_coordinator';
  END IF;
  IF p_destinataire_id IS NULL OR p_destinataire_id = p_library_id THEN
    RAISE EXCEPTION 'same_library' USING errcode = '22023', hint = 'error.correspondance.same_library';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.libraries l WHERE l.id = p_destinataire_id AND l.is_active = true) THEN
    RAISE EXCEPTION 'library_not_found' USING errcode = 'P0002', hint = 'error.correspondance.library_not_found';
  END IF;
  IF char_length(v_sujet) < 1 OR char_length(v_sujet) > 200 THEN
    RAISE EXCEPTION 'subject_required' USING errcode = '22023', hint = 'error.correspondance.subject_required';
  END IF;
  INSERT INTO public.library_conversations (subject, created_by) VALUES (v_sujet, (SELECT auth.uid()))
  RETURNING id INTO v_id;
  INSERT INTO public.library_conversation_participants (conversation_id, library_id)
  VALUES (v_id, p_library_id), (v_id, p_destinataire_id);
  PERFORM public.fn_correspondance_poser_message(v_id, p_library_id, p_corps, p_lang);
  PERFORM api.fn_correspondance_lue(v_id);
  RETURN v_id;
END;
$$;

-- Envoyer dans un fil, au nom d'une bibliothèque participante que je coordonne.
CREATE OR REPLACE FUNCTION api.fn_correspondance_envoyer(p_conversation_id bigint, p_library_id uuid, p_corps text, p_lang text DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE v_id bigint;
BEGIN
  IF NOT public.fn_correspondance_coordonne(p_library_id) THEN
    RAISE EXCEPTION 'not_coordinator' USING errcode = '42501', hint = 'error.correspondance.not_coordinator';
  END IF;
  -- « introuvable » et « pas dans ce fil » ne se distinguent pas : rien ne renseigne sur le fil d'autrui.
  IF NOT EXISTS (SELECT 1 FROM public.library_conversation_participants p
                  WHERE p.conversation_id = p_conversation_id AND p.library_id = p_library_id) THEN
    RAISE EXCEPTION 'not_participant' USING errcode = '42501', hint = 'error.correspondance.not_participant';
  END IF;
  v_id := public.fn_correspondance_poser_message(p_conversation_id, p_library_id, p_corps, p_lang);
  PERFORM api.fn_correspondance_lue(p_conversation_id);
  RETURN v_id;
END;
$$;

-- Archiver (ou rouvrir) un fil pour MA bibliothèque ; les autres ne le voient pas.
CREATE OR REPLACE FUNCTION api.fn_correspondance_archiver(p_conversation_id bigint, p_library_id uuid, p_archiver boolean DEFAULT true)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
BEGIN
  IF NOT public.fn_correspondance_coordonne(p_library_id) THEN
    RAISE EXCEPTION 'not_coordinator' USING errcode = '42501', hint = 'error.correspondance.not_coordinator';
  END IF;
  UPDATE public.library_conversation_participants
     SET archived_at = CASE WHEN p_archiver THEN now() ELSE NULL END
   WHERE conversation_id = p_conversation_id AND library_id = p_library_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'not_participant' USING errcode = '42501', hint = 'error.correspondance.not_participant';
  END IF;
END;
$$;

-- Marquer lu : jusqu'au dernier message du fil, pour MOI (coordination d'une
-- bibliothèque du fil). Rend l'identifiant du dernier message lu.
CREATE OR REPLACE FUNCTION api.fn_correspondance_lue(p_conversation_id bigint)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE v_dernier bigint;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR NOT public.fn_correspondance_lit(p_conversation_id) THEN
    RAISE EXCEPTION 'not_participant' USING errcode = '42501', hint = 'error.correspondance.not_participant';
  END IF;
  SELECT coalesce(max(m.id), 0) INTO v_dernier FROM public.library_messages m WHERE m.conversation_id = p_conversation_id;
  INSERT INTO public.library_conversation_reads (conversation_id, user_id, last_read_message_id, read_at)
  VALUES (p_conversation_id, (SELECT auth.uid()), v_dernier, now())
  ON CONFLICT (conversation_id, user_id) DO UPDATE
    SET last_read_message_id = GREATEST(public.library_conversation_reads.last_read_message_id, EXCLUDED.last_read_message_id),
        read_at = now();
  RETURN v_dernier;
END;
$$;

DO $g19_droits$
DECLARE f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'api.fn_correspondance_ouvrir(uuid, uuid, text, text, text)',
    'api.fn_correspondance_envoyer(bigint, uuid, text, text)',
    'api.fn_correspondance_archiver(bigint, uuid, boolean)',
    'api.fn_correspondance_lue(bigint)'] LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, anon, authenticated', f);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated, service_role', f);
  END LOOP;
END
$g19_droits$;

-- ─────────────────────────────────────────────────────────────────────
-- 5. Vérifications
-- ─────────────────────────────────────────────────────────────────────
DO $g19_verif$
DECLARE v_e text := ''; t text; f text;
BEGIN
  FOREACH t IN ARRAY ARRAY['library_conversations', 'library_conversation_participants', 'library_messages', 'library_conversation_reads'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE n.nspname = 'public' AND c.relname = t AND c.relrowsecurity AND NOT c.relforcerowsecurity) THEN
      v_e := v_e || ' rls(' || t || ')';
    END IF;
    IF has_table_privilege('anon', 'public.' || t, 'SELECT')
       OR has_table_privilege('authenticated', 'public.' || t, 'INSERT')
       OR has_table_privilege('authenticated', 'public.' || t, 'UPDATE')
       OR has_table_privilege('authenticated', 'public.' || t, 'DELETE')
       OR NOT has_table_privilege('authenticated', 'public.' || t, 'SELECT') THEN
      v_e := v_e || ' droits-table(' || t || ')';
    END IF;
    IF (SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = t) <> 1 THEN
      v_e := v_e || ' politiques(' || t || ')';
    END IF;
  END LOOP;
  FOREACH f IN ARRAY ARRAY[
    'api.fn_correspondance_ouvrir(uuid, uuid, text, text, text)', 'api.fn_correspondance_envoyer(bigint, uuid, text, text)',
    'api.fn_correspondance_archiver(bigint, uuid, boolean)', 'api.fn_correspondance_lue(bigint)',
    'public.fn_correspondance_lit(bigint)'] LOOP
    IF NOT has_function_privilege('authenticated', f, 'EXECUTE') OR has_function_privilege('anon', f, 'EXECUTE')
       OR NOT has_function_privilege('service_role', f, 'EXECUTE')
       OR EXISTS (SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid = f::regprocedure AND a.grantee = 0) THEN
      v_e := v_e || ' droits-portes(' || f || ')';
    END IF;
  END LOOP;
  FOREACH f IN ARRAY ARRAY[
    'public.fn_correspondance_coordonne(uuid)', 'public.fn_correspondance_langue(text, uuid)',
    'public.fn_correspondance_poser_message(bigint, uuid, text, text)'] LOOP
    IF has_function_privilege('authenticated', f, 'EXECUTE') OR has_function_privilege('anon', f, 'EXECUTE')
       OR EXISTS (SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid = f::regprocedure AND a.grantee = 0) THEN
      v_e := v_e || ' droits-internes(' || f || ')';
    END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
              WHERE p.proname LIKE 'fn_correspondance_%' AND n.nspname IN ('api', 'public')
                AND (NOT p.prosecdef OR coalesce(p.proconfig::text, '') NOT LIKE '%search_path%')) THEN
    v_e := v_e || ' definer';
  END IF;
  IF v_e <> '' THEN
    RAISE EXCEPTION 'G19 lot 1 : vérification en échec :%', v_e;
  END IF;
  RAISE NOTICE 'G19 lot 1 : vérifications OK — quatre tables, cinq portes, trois aides fermées';
END
$g19_verif$;

NOTIFY pgrst, 'reload schema';
