-- =========================================================================
-- Paquet revision-des-lots-importes — un lot ne d'un import ne se publie
-- qu'apres une revision de l'administration du reseau, sur rapport
-- =========================================================================
-- Date     : 2026-09-05
-- Chantier : importations — qui peut faire entrer quoi dans le catalogue
-- Auteur   : coordination AnarBib (decision Xavier du 05/09/2026)
--
-- POURQUOI
--   Les paquets du 04/09 (20260904121500, 20260904133000) ont pose la doctrine
--   « la provenance decide » : un fonds tiers n'entre que par l'administration.
--   Mais l'entree d'un lot dans la FILE n'est pas son entree au CATALOGUE : la
--   publication reste un geste de coordination, et c'est elle qui fait le
--   catalogue — bien ou mal ecrit. Xavier : « le but etant d'eviter un
--   catalogue foutoir mal ecrit ». D'ou ce circuit, pour TOUT lot ne d'un
--   import (catalogue propre compris) :
--
--     coordination : revise ses brouillons, lit le RAPPORT, corrige, demande
--                    la revision ;
--     admin reseau : lit le rapport a jour, tranche (approuve / retouches) ;
--     coordination : publie — la garde de publication ne s'ouvre qu'apres
--                    approbation.
--
--   Le rapport est produit par la base, pas redige : conventions (titre,
--   auteurs, dates, langue, matieres…), doublons (contre le catalogue, a
--   l'interieur du lot, et le rapprochement de l'import), autorites (auteurs
--   non lies, homonymes probables). Il est LISIBLE PAR LA COORDINATION AVANT
--   la demande : elle corrige d'abord ce qu'elle peut. Meme patron que le
--   circuit collegial (demande, notification, verdict motive, notification).
--
-- CE QUE FAIT LE PAQUET
--   1. public.catalog_batch_reviews : une ligne par TOUR de revision d'un lot
--      (requested -> approved | changes_requested). Un lot peut connaitre
--      plusieurs tours ; seul le dernier compte.
--   2. fn_batch_is_imported(lot) : ne d'un import = au moins un brouillon
--      relie a une ligne d'import (ingest.partner_catalog_row_to_draft) ou
--      portant une provenance d'import (import_method / partner_source).
--   3. fn_batch_review_report(lot) : le rapport (jsonb), ouvert au staff.
--   4. fn_batch_review_request(lot, message) : coordination ; fige un
--      instantane du rapport dans le tour.
--   5. fn_batch_review_verdict(tour, verdict, notes) : admin reseau ; le
--      rapport est regenere au moment du verdict.
--   6. fn_batch_reviews_list() : ce que voient l'onglet Lots (coordination)
--      et l'onglet Revisions de la page Reseau (admin).
--   7. publish_book_draft : GARDE — un brouillon d'un lot importe ne se
--      publie que si le dernier tour est approuve
--      (HINT error.publish.review_required). publish_catalog_batch appelle
--      publish_book_draft pour chaque brouillon : la garde le couvre.
--   8. Cloche : demande -> les admins reseau ; verdict -> la personne qui a
--      demande (trigger, cles i18n, comme le circuit collegial).
--
-- CE QUE LE PAQUET NE FAIT PAS
--   - Il ne touche pas au vocabulaire de statut du lot (open/closed/…) : la
--     revision vit a cote, dans sa table. Les CHECK qui derivent ont coute
--     assez cher.
--   - Il ne bloque pas les lots NON importes (catalogage a la main).
--   - Il ne requalifie aucun lot existant : les lots importes deja en file
--     (Solidaires, CIRA) passeront par la revision avant publication — c'est
--     le but.
--
-- CHECKLIST DOCTRINE
--   [x] Table neuve : RLS + REVOKE/GRANT explicites + index sur la FK
--       (gardes fk_sans_index / grants_herites) ; ajoutee a
--       deploy/bg2-known-tables.txt
--   [x] Fonctions DEFINER : search_path pose ; REVOKE FROM PUBLIC, anon ;
--       trigger sans aucun grant
--   [x] publish_book_draft : substitution VERIFIEE sur pg_get_functiondef,
--       pas de recopie (patron 20260901091431)
--   [x] DO block de verification STRUCTUREL ; le fonctionnel vit dans
--       tests/sql/revision_lots_importes_tests.sql
-- =========================================================================

begin;

-- ── 1. La table des tours de revision ──────────────────────────────────
create table if not exists public.catalog_batch_reviews (
  id                  bigint generated by default as identity primary key,
  batch_id            bigint not null references public.catalog_batches(id) on delete cascade,
  round               integer not null default 1,
  status              text not null default 'requested'
                      constraint catalog_batch_reviews_status_check
                      check (status in ('requested', 'approved', 'changes_requested')),
  requested_by        uuid,
  requested_at        timestamptz not null default now(),
  coord_message       text,
  reviewed_by         uuid,
  reviewed_at         timestamptz,
  admin_notes         text,
  report              jsonb,
  report_generated_at timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint catalog_batch_reviews_batch_round_key unique (batch_id, round)
);

comment on table public.catalog_batch_reviews is
  'Tours de revision d''un lot de catalogage ne d''un import (05/09/2026). '
  'requested -> approved | changes_requested. Seul le dernier tour compte pour '
  'la garde de publication (fn_batch_review_status). Le rapport est un '
  'instantane jsonb de fn_batch_review_report, fige a la demande puis au verdict.';

create index if not exists catalog_batch_reviews_batch_id_idx
  on public.catalog_batch_reviews (batch_id);

alter table public.catalog_batch_reviews enable row level security;

revoke all on public.catalog_batch_reviews from public, anon, authenticated;
grant select on public.catalog_batch_reviews to authenticated;
grant all    on public.catalog_batch_reviews to service_role;

-- Lecture : le staff de catalogage (les lots sont deja visibles de tout le
-- staff) et l'admin reseau. Aucune ecriture directe : tout passe par les RPC.
drop policy if exists catalog_batch_reviews_read_staff on public.catalog_batch_reviews;
create policy catalog_batch_reviews_read_staff on public.catalog_batch_reviews
  for select to authenticated
  using (
    public.fn_caller_is_network_admin()
    or exists (
      select 1 from public.user_library_memberships m
       where m.user_id = auth.uid()
         and m.status = 'active'
         and m.role in ('librarian', 'coordenador')
    )
  );

-- ── 2. Un lot est-il ne d'un import ? ───────────────────────────────────
create or replace function public.fn_batch_is_imported(p_batch_id bigint)
returns boolean
language sql
stable
security definer
set search_path to 'public', 'ingest'
as $function$
  select exists (
           select 1 from ingest.partner_catalog_row_to_draft m
            where m.batch_id = p_batch_id
         )
      or exists (
           select 1 from public.book_drafts d
            where d.batch_id = p_batch_id
              and (d.import_method is not null or d.partner_source is not null)
         );
$function$;

revoke execute on function public.fn_batch_is_imported(bigint) from public, anon, authenticated;
grant  execute on function public.fn_batch_is_imported(bigint) to service_role;

comment on function public.fn_batch_is_imported(bigint) is
  'Vrai si le lot est ne d''un import : brouillon relie a une ligne d''import '
  'ou portant une provenance d''import. Interne (publish_book_draft, RPC).';

-- Statut du DERNIER tour (null si jamais demande).
create or replace function public.fn_batch_review_status(p_batch_id bigint)
returns text
language sql
stable
security definer
set search_path to 'public'
as $function$
  select r.status
    from public.catalog_batch_reviews r
   where r.batch_id = p_batch_id
   order by r.round desc
   limit 1;
$function$;

revoke execute on function public.fn_batch_review_status(bigint) from public, anon, authenticated;
grant  execute on function public.fn_batch_review_status(bigint) to service_role;

-- ── 3. Le rapport ───────────────────────────────────────────────────────
-- Tout est calcule sur les brouillons VIVANTS du lot (draft/ready). Chaque
-- rubrique rend un compte total et un echantillon borne (40 lignes) : le
-- rapport doit rester lisible et tenir dans une ligne jsonb.
-- VOLATILE (pas STABLE) : la fonction remplit une table temporaire, ce qu'une
-- fonction non volatile n'a pas le droit de faire. Elle n'ecrit rien d'autre.
create or replace function public.fn_batch_review_report(p_batch_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'ingest', 'extensions'
as $function$
declare
  v_batch      public.catalog_batches%rowtype;
  v_conv       jsonb := '[]'::jsonb;
  v_rule       record;
  v_items      jsonb;
  v_count      int;
  v_issues     int := 0;
  v_dup_isbn   jsonb;
  v_dup_meta   jsonb;
  v_dup_intra  jsonb;
  v_matching   jsonb;
  v_unlinked   jsonb;
  v_unlinked_n int;
  v_linkable_n int;
begin
  if not (public.fn_caller_is_network_admin()
          or exists (select 1 from public.user_library_memberships m
                      where m.user_id = auth.uid() and m.status = 'active'
                        and m.role in ('librarian', 'coordenador'))) then
    raise exception 'Acesso restrito ao staff de catalogacao.' using hint = 'error.catalog.staff_only';
  end if;

  select * into v_batch from public.catalog_batches where id = p_batch_id;
  if not found then
    raise exception 'Lote % introuvable', p_batch_id using hint = 'error.review.batch_not_found';
  end if;

  -- Les brouillons vivants du lot, une fois pour toutes.
  create temp table if not exists _rev_drafts on commit drop as
    select d.id, d.titulo, d.autor, d.ano, d.editora, d.idioma, d.isbn, d.bib_ref,
           d.tipo_material, d.subjects, d.approximate_date, d.published_book_id
      from public.book_drafts d
     where d.batch_id = p_batch_id and d.status in ('draft', 'ready');
  -- (temp table nommee : on la vide si un appel precedent de la meme
  --  transaction l'a laissee — un rapport par appel, jamais deux melanges)
  delete from _rev_drafts;
  insert into _rev_drafts
    select d.id, d.titulo, d.autor, d.ano, d.editora, d.idioma, d.isbn, d.bib_ref,
           d.tipo_material, d.subjects, d.approximate_date, d.published_book_id
      from public.book_drafts d
     where d.batch_id = p_batch_id and d.status in ('draft', 'ready');

  -- ── Conventions : une regle = un SELECT (draft_id, titulo, valeur) ──
  for v_rule in
    select * from (values
      ('titulo_missing',   $q$ select id, titulo, null::text from _rev_drafts where titulo is null or btrim(titulo) = '' $q$),
      ('titulo_caps',      $q$ select id, titulo, titulo from _rev_drafts where titulo = upper(titulo) and titulo ~ '[A-ZÀ-Þ]{4,}' $q$),
      ('titulo_article_end', $q$ select id, titulo, titulo from _rev_drafts where titulo ~ ', (O|A|Os|As|Um|Uma|Le|La|Les|El|Los|Las|The)$' $q$),
      ('autor_missing',    $q$ select d.id, d.titulo, null::text from _rev_drafts d
                                where (d.autor is null or btrim(d.autor) = '')
                                  and not exists (select 1 from public.book_draft_contributors c where c.draft_id = d.id) $q$),
      ('autor_unstructured', $q$ select d.id, d.titulo, d.autor from _rev_drafts d
                                where d.autor is not null and btrim(d.autor) <> ''
                                  and not exists (select 1 from public.book_draft_contributors c where c.draft_id = d.id) $q$),
      ('contrib_caps',     $q$ select d.id, d.titulo, c.name from _rev_drafts d
                                join public.book_draft_contributors c on c.draft_id = d.id
                               where c.name ~ '\m[A-ZÀ-Þ]{2,}\M' and c.name !~ '[A-ZÀ-Þ]\.' $q$),
      ('contrib_direct_form', $q$ select d.id, d.titulo, c.name from _rev_drafts d
                                join public.book_draft_contributors c on c.draft_id = d.id
                               where c.name !~ ',' and btrim(c.name) ~ '\s' $q$),
      ('ano_invalid',      $q$ select id, titulo, ano from _rev_drafts
                                where approximate_date is null and (ano is null or ano !~ '^\d{4}$') $q$),
      ('editora_missing',  $q$ select id, titulo, null::text from _rev_drafts where editora is null or btrim(editora) = '' $q$),
      ('idioma_missing',   $q$ select id, titulo, null::text from _rev_drafts where idioma is null or btrim(idioma) = '' $q$),
      ('tipo_material_invalid', $q$ select id, titulo, tipo_material from _rev_drafts
                                where tipo_material is null or lower(tipo_material) <> all (array['livro','periodico','tract','cartaz','audio','audiovisual','recurso_digital','dossie','tese','artigo','relatorio','zine']) $q$),
      ('isbn_invalid',     $q$ select id, titulo, isbn from _rev_drafts
                                where isbn is not null and btrim(isbn) <> ''
                                  and length(regexp_replace(upper(isbn), '[^0-9X]', '', 'g')) not in (10, 13) $q$),
      ('bib_ref_missing',  $q$ select id, titulo, null::text from _rev_drafts where bib_ref is null or btrim(bib_ref) = '' $q$),
      ('subjects_missing', $q$ select d.id, d.titulo, null::text from _rev_drafts d
                                where (d.subjects is null or btrim(d.subjects) = '')
                                  and not exists (select 1 from public.book_draft_subjects s where s.book_draft_id = d.id) $q$)
    ) as r(rule, sql)
  loop
    execute format('select count(*), coalesce(jsonb_agg(jsonb_build_object(''draft_id'', t.id, ''titulo'', t.titulo, ''value'', t.v)), ''[]''::jsonb)
                      from (select q.id, q.titulo, q.v from (%s) as q(id, titulo, v) order by q.id limit 40) t', v_rule.sql)
       into v_count, v_items;
    -- count(*) porte sur l'echantillon ; le total vient d'une seconde passe
    execute format('select count(*) from (%s) as q(id, titulo, v)', v_rule.sql) into v_count;
    if v_count > 0 then
      v_conv := v_conv || jsonb_build_object('rule', v_rule.rule, 'count', v_count, 'items', v_items);
      v_issues := v_issues + v_count;
    end if;
  end loop;

  -- ── Doublons contre le catalogue : ISBN, puis titre + auteur + annee ──
  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_dup_isbn from (
    select jsonb_build_object('draft_id', d.id, 'titulo', d.titulo, 'book_id', b.id, 'reason', 'isbn') as x
      from _rev_drafts d
      join public.books b
        on regexp_replace(upper(coalesce(b.isbn, '')), '[^0-9X]', '', 'g')
         = regexp_replace(upper(coalesce(d.isbn, '')), '[^0-9X]', '', 'g')
     where coalesce(d.isbn, '') <> ''
       and (d.published_book_id is null or b.id <> d.published_book_id)
     order by d.id limit 40) s;

  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_dup_meta from (
    select jsonb_build_object('draft_id', d.id, 'titulo', d.titulo, 'book_id', b.id, 'reason', 'titulo_autor_ano') as x
      from _rev_drafts d
      join public.books b
        on lower(extensions.unaccent(btrim(coalesce(b.titulo, '')))) = lower(extensions.unaccent(btrim(coalesce(d.titulo, ''))))
       and coalesce(b.ano, '') = coalesce(d.ano, '')
       and lower(extensions.unaccent(btrim(coalesce(b.autor, '')))) = lower(extensions.unaccent(btrim(coalesce(d.autor, ''))))
     where coalesce(d.titulo, '') <> ''
       and (d.published_book_id is null or b.id <> d.published_book_id)
       and not (coalesce(d.isbn, '') <> '' and
                regexp_replace(upper(coalesce(b.isbn, '')), '[^0-9X]', '', 'g')
              = regexp_replace(upper(coalesce(d.isbn, '')), '[^0-9X]', '', 'g'))
     order by d.id limit 40) s;

  -- ── Doublons a l'interieur du lot ──
  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_dup_intra from (
    select jsonb_build_object('titulo', min(d.titulo), 'draft_ids', jsonb_agg(d.id order by d.id)) as x
      from _rev_drafts d
     where coalesce(d.titulo, '') <> ''
     group by lower(extensions.unaccent(btrim(d.titulo))),
              lower(extensions.unaccent(btrim(coalesce(d.autor, '')))),
              coalesce(d.ano, '')
    having count(*) > 1
     order by min(d.id) limit 40) s;

  -- ── Le rapprochement fait a l'import (ce que l'appariement a dit) ──
  select coalesce(jsonb_object_agg(match_status, n), '{}'::jsonb) into v_matching from (
    select sr.match_status, count(*) as n
      from ingest.partner_catalog_row_to_draft m
      join ingest.partner_catalog_staging_rows sr on sr.id = m.staging_row_id
     where m.batch_id = p_batch_id
     group by sr.match_status) s;

  -- ── Autorites : contributeurs non lies, et ceux qu'une fiche attend ──
  select count(*),
         count(*) filter (where public.fn_conv_autorite_homonyme(c.name) is not null)
    into v_unlinked_n, v_linkable_n
    from _rev_drafts d
    join public.book_draft_contributors c on c.draft_id = d.id
   where c.author_id is null;

  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_unlinked from (
    select jsonb_build_object('draft_id', d.id, 'titulo', d.titulo, 'name', c.name,
                              'suggested_author_id', a.id, 'suggested_sort_name', a.sort_name) as x
      from _rev_drafts d
      join public.book_draft_contributors c on c.draft_id = d.id
      left join public.authors a on a.id = public.fn_conv_autorite_homonyme(c.name)
     where c.author_id is null
     order by (a.id is null), d.id limit 40) s;

  return jsonb_build_object(
    'batch', jsonb_build_object(
      'id', v_batch.id, 'name', v_batch.name, 'status', v_batch.status,
      'imported', public.fn_batch_is_imported(p_batch_id),
      'drafts_active', (select count(*) from _rev_drafts),
      'drafts_published', (select count(*) from public.book_drafts where batch_id = p_batch_id and status = 'published'),
      'drafts_cancelled', (select count(*) from public.book_drafts where batch_id = p_batch_id and status = 'cancelled')),
    'generated_at', now(),
    'conventions', v_conv,
    'duplicates', jsonb_build_object(
      'catalog_isbn', v_dup_isbn,
      'catalog_meta', v_dup_meta,
      'intra_lot', v_dup_intra,
      'import_matching', v_matching),
    'authorities', jsonb_build_object(
      'unlinked_count', v_unlinked_n,
      'linkable_count', v_linkable_n,
      'unlinked', v_unlinked),
    'totals', jsonb_build_object(
      'convention_issues', v_issues,
      'duplicates', jsonb_array_length(v_dup_isbn) + jsonb_array_length(v_dup_meta) + jsonb_array_length(v_dup_intra),
      'unlinked_authorities', v_unlinked_n)
  );
end;
$function$;

revoke execute on function public.fn_batch_review_report(bigint) from public, anon;
grant  execute on function public.fn_batch_review_report(bigint) to authenticated, service_role;

comment on function public.fn_batch_review_report(bigint) is
  'Rapport de revision d''un lot (jsonb) : conventions, doublons, autorites, '
  'calcules sur les brouillons vivants. Ouvert au staff de catalogage AVANT la '
  'demande — la coordination corrige d''abord ce qu''elle peut (05/09/2026).';

-- ── 4. Demander la revision (coordination) ───────────────────────────────
create or replace function public.fn_batch_review_request(p_batch_id bigint, p_message text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'ingest'
as $function$
declare
  v_batch  public.catalog_batches%rowtype;
  v_last   text;
  v_round  int;
  v_id     bigint;
begin
  if not (public.fn_caller_is_network_admin()
          or exists (select 1 from public.user_library_memberships m
                      where m.user_id = auth.uid() and m.status = 'active'
                        and m.role = 'coordenador')) then
    raise exception 'Acesso restrito ao coordenador da biblioteca.' using hint = 'error.review.coordenador_only';
  end if;

  select * into v_batch from public.catalog_batches where id = p_batch_id;
  if not found then
    raise exception 'Lote % introuvable', p_batch_id using hint = 'error.review.batch_not_found';
  end if;
  if v_batch.status <> 'open' then
    raise exception 'Lote % nao esta aberto', p_batch_id using hint = 'error.review.batch_not_open';
  end if;
  if not public.fn_batch_is_imported(p_batch_id) then
    raise exception 'Lote % nao vem de uma importacao', p_batch_id using hint = 'error.review.not_imported';
  end if;

  v_last := public.fn_batch_review_status(p_batch_id);
  if v_last = 'requested' then
    raise exception 'Revisao ja pedida para o lote %', p_batch_id using hint = 'error.review.already_requested';
  end if;
  if v_last = 'approved' then
    raise exception 'Lote % ja aprovado', p_batch_id using hint = 'error.review.already_approved';
  end if;

  select coalesce(max(round), 0) + 1 into v_round
    from public.catalog_batch_reviews where batch_id = p_batch_id;

  insert into public.catalog_batch_reviews
    (batch_id, round, status, requested_by, coord_message, report, report_generated_at)
  values
    (p_batch_id, v_round, 'requested', auth.uid(), nullif(btrim(p_message), ''),
     public.fn_batch_review_report(p_batch_id), now())
  returning id into v_id;

  return jsonb_build_object('ok', true, 'review_id', v_id, 'round', v_round);
end;
$function$;

revoke execute on function public.fn_batch_review_request(bigint, text) from public, anon;
grant  execute on function public.fn_batch_review_request(bigint, text) to authenticated, service_role;

-- ── 5. Trancher (admin reseau) ──────────────────────────────────────────
create or replace function public.fn_batch_review_verdict(p_review_id bigint, p_verdict text, p_notes text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'ingest'
as $function$
declare
  v_rev public.catalog_batch_reviews%rowtype;
begin
  if not public.fn_caller_is_network_admin() then
    raise exception 'Revisao reservada a administracao da rede.' using hint = 'error.review.admin_only';
  end if;
  if p_verdict not in ('approved', 'changes_requested') then
    raise exception 'Veredito invalido: %', p_verdict using hint = 'error.review.bad_verdict';
  end if;

  select * into v_rev from public.catalog_batch_reviews where id = p_review_id for update;
  if not found then
    raise exception 'Revisao % introuvable', p_review_id using hint = 'error.review.not_found';
  end if;
  if v_rev.status <> 'requested' then
    raise exception 'Revisao % ja tratada', p_review_id using hint = 'error.review.already_decided';
  end if;
  -- Des retouches sans un mot ne disent rien a la coordination.
  if p_verdict = 'changes_requested' and nullif(btrim(p_notes), '') is null then
    raise exception 'Notas obrigatorias para pedir retoques.' using hint = 'error.review.notes_required';
  end if;

  update public.catalog_batch_reviews
     set status = p_verdict,
         reviewed_by = auth.uid(),
         reviewed_at = now(),
         admin_notes = nullif(btrim(p_notes), ''),
         report = public.fn_batch_review_report(v_rev.batch_id),
         report_generated_at = now(),
         updated_at = now()
   where id = p_review_id;

  return jsonb_build_object('ok', true, 'review_id', p_review_id, 'status', p_verdict);
end;
$function$;

revoke execute on function public.fn_batch_review_verdict(bigint, text, text) from public, anon;
grant  execute on function public.fn_batch_review_verdict(bigint, text, text) to authenticated, service_role;

-- ── 6. La liste, pour les deux ecrans ────────────────────────────────────
create or replace function public.fn_batch_reviews_list()
returns table (
  batch_id        bigint,
  batch_name      text,
  batch_status    text,
  imported        boolean,
  review_id       bigint,
  round           integer,
  status          text,
  requested_by    uuid,
  requester_name  text,
  requested_at    timestamptz,
  coord_message   text,
  reviewed_by     uuid,
  reviewer_name   text,
  reviewed_at     timestamptz,
  admin_notes     text,
  report          jsonb,
  report_generated_at timestamptz,
  drafts_active   bigint
)
language sql
stable
security definer
set search_path to 'public', 'ingest'
as $function$
  select b.id, b.name, b.status,
         public.fn_batch_is_imported(b.id),
         r.id, r.round, r.status,
         r.requested_by,
         nullif(btrim(concat_ws(' ', pq.first_name, pq.last_name)), ''),
         r.requested_at, r.coord_message,
         r.reviewed_by,
         nullif(btrim(concat_ws(' ', pv.first_name, pv.last_name)), ''),
         r.reviewed_at, r.admin_notes,
         r.report, r.report_generated_at,
         (select count(*) from public.book_drafts d where d.batch_id = b.id and d.status in ('draft', 'ready'))
    from public.catalog_batches b
    left join lateral (
      select * from public.catalog_batch_reviews x
       where x.batch_id = b.id order by x.round desc limit 1
    ) r on true
    left join public.profiles pq on pq.id = r.requested_by
    left join public.profiles pv on pv.id = r.reviewed_by
   where b.status <> 'archived'
     and (public.fn_caller_is_network_admin()
          or exists (select 1 from public.user_library_memberships m
                      where m.user_id = auth.uid() and m.status = 'active'
                        and m.role in ('librarian', 'coordenador')))
   order by (r.status = 'requested') desc nulls last, r.requested_at desc nulls last, b.created_at desc;
$function$;

revoke execute on function public.fn_batch_reviews_list() from public, anon;
grant  execute on function public.fn_batch_reviews_list() to authenticated, service_role;

comment on function public.fn_batch_reviews_list() is
  'Un enregistrement par lot non archive avec son DERNIER tour de revision '
  '(null si jamais demande) ; staff de catalogage et admin reseau.';

-- ── 7. La garde de publication ───────────────────────────────────────────
do $$
declare
  v_def text;
  v_new text;
  v_old text;
  v_rep text;
begin
  select pg_get_functiondef(p.oid) into v_def
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'publish_book_draft'
     and pg_get_function_identity_arguments(p.oid) = 'p_draft_id bigint';
  if v_def is null then
    raise exception 'publish_book_draft(bigint) introuvable';
  end if;
  if position('error.publish.review_required' in v_def) > 0 then
    raise notice 'publish_book_draft porte deja la garde de revision — rien a faire';
    return;
  end if;

  v_old := E'  if v_draft.status = \'cancelled\' then\n'
        || E'    raise exception \'rascunho_descartado\' using hint = \'error.publish.draft_cancelled\';\n'
        || E'  end if;\n';
  v_rep := v_old
        || E'\n'
        || E'  -- 05/09/2026 : un lot ne d''un import ne se publie qu''apres une revision\n'
        || E'  -- approuvee par l''administration du reseau (catalog_batch_reviews).\n'
        || E'  -- publish_catalog_batch passe ici pour chaque brouillon : la garde le couvre.\n'
        || E'  if v_draft.batch_id is not null\n'
        || E'     and public.fn_batch_is_imported(v_draft.batch_id)\n'
        || E'     and public.fn_batch_review_status(v_draft.batch_id) is distinct from \'approved\' then\n'
        || E'    raise exception \'lote_importado_sem_revisao\' using hint = \'error.publish.review_required\';\n'
        || E'  end if;\n';
  if position(v_old in v_def) = 0 then
    raise exception 'publish_book_draft : l''ancre « rascunho_descartado » est absente — relire la definition avant de substituer';
  end if;
  v_new := replace(v_def, v_old, v_rep);
  if v_new = v_def then
    raise exception 'publish_book_draft : substitution non appliquee';
  end if;
  execute v_new;
end
$$;

-- ── 8. La cloche ─────────────────────────────────────────────────────────
create or replace function public.fn_catalog_batch_reviews_notify()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  -- Demande deposee : les admins reseau actifs, sauf la personne qui demande
  -- (une admin qui demande pour son propre lot n'a pas a etre prevenue).
  if tg_op = 'INSERT' and new.status = 'requested' then
    insert into public.user_notifications
      (user_id, library_id, category, title, body, link_type, link_id, is_read)
    select na.user_id, null, 'catalog',
           'notif.review.requested.title',
           'notif.review.requested.body',
           'batch_review_verdict', new.batch_id::text, false
      from public.network_administrators na
     where na.status = 'active'
       and na.user_id is distinct from new.requested_by;
    return new;
  end if;

  -- Verdict rendu : la personne qui a demande, elle seule.
  if tg_op = 'UPDATE' and new.status in ('approved', 'changes_requested')
     and old.status is distinct from new.status and new.requested_by is not null then
    insert into public.user_notifications
      (user_id, library_id, category, title, body, link_type, link_id, is_read)
    values (new.requested_by, null, 'catalog',
            case when new.status = 'approved' then 'notif.review.approved.title' else 'notif.review.changes.title' end,
            case when new.status = 'approved' then 'notif.review.approved.body'  else 'notif.review.changes.body'  end,
            'batch_review_result', new.batch_id::text, false);
    return new;
  end if;

  return new;
end;
$function$;

revoke execute on function public.fn_catalog_batch_reviews_notify() from public, anon, authenticated;

drop trigger if exists catalog_batch_reviews_notify on public.catalog_batch_reviews;
create trigger catalog_batch_reviews_notify
  after insert or update on public.catalog_batch_reviews
  for each row execute function public.fn_catalog_batch_reviews_notify();

-- ── 9. Verification structurelle (aucune dependance aux donnees) ─────────
do $verif$
declare
  v_def text;
  v_n int;
begin
  if to_regclass('public.catalog_batch_reviews') is null then
    raise exception 'catalog_batch_reviews introuvable';
  end if;
  select count(*) into v_n from pg_indexes
   where schemaname = 'public' and tablename = 'catalog_batch_reviews'
     and indexdef like '%(batch_id)%';
  if v_n = 0 then raise exception 'index sur catalog_batch_reviews.batch_id absent'; end if;

  select pg_get_functiondef(p.oid) into v_def
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'publish_book_draft';
  if position('error.publish.review_required' in v_def) = 0 then
    raise exception 'publish_book_draft ne porte pas la garde de revision';
  end if;

  select count(*) into v_n from information_schema.routine_privileges
   where routine_schema = 'public'
     and routine_name in ('fn_batch_is_imported', 'fn_batch_review_status', 'fn_batch_review_report',
                          'fn_batch_review_request', 'fn_batch_review_verdict', 'fn_batch_reviews_list',
                          'fn_catalog_batch_reviews_notify')
     and grantee in ('anon', 'PUBLIC');
  if v_n <> 0 then raise exception '% droit(s) anon/PUBLIC de trop sur les fonctions de revision', v_n; end if;

  select count(*) into v_n from information_schema.table_privileges
   where table_schema = 'public' and table_name = 'catalog_batch_reviews'
     and grantee in ('anon', 'PUBLIC');
  if v_n <> 0 then raise exception 'catalog_batch_reviews ouverte a anon/PUBLIC'; end if;

  if not exists (select 1 from pg_trigger where tgname = 'catalog_batch_reviews_notify') then
    raise exception 'trigger catalog_batch_reviews_notify absent';
  end if;

  raise notice 'Paquet revision-des-lots-importes : verifications OK';
end
$verif$;

commit;
