-- =========================================================================
-- Paquet DOUBLONS P8 — signaler un doublon d'autorité
-- =========================================================================
-- Date     : 2026-08-21
-- Chantier : catalogage / dédoublonnage
-- Auteur   : Xavier (+ Claude)
-- Session  : Dédoublonnage & arbitrage
--
-- POURQUOI. Le paquet P4 a réservé `merge_author` à la coordination, et rendu au
-- poste de catalogage un geste utile en échange : signaler. Mais ce geste
-- n'existait que pour les DOCUMENTS. Sur les autorités, le staff voyait la liste
-- des doublons probables et… rien. Pas de bouton, pas de file, pas de moyen de
-- transmettre. On lui retirait un pouvoir sans rien lui rendre — exactement ce
-- que `DEDUP-1` prétend éviter (« on lui retire le pouvoir de détruire, pas sa
-- connaissance du terrain »). Cette asymétrie était un manque, pas un choix.
--
-- La table reprend la forme de `catalog_duplicate_reports`, avec ses propres clés
-- étrangères vers `authors`. Une table générique portant un `entity_type` aurait
-- semblé plus économe, mais elle aurait perdu l'intégrité référentielle : on ne
-- peut pas déclarer une clé étrangère vers deux tables à la fois, donc plus de
-- `ON DELETE CASCADE`, donc des signalements fantômes survivant à l'autorité
-- qu'ils désignent. Deux tables, deux FK réelles.
--
-- PAS D'AUTO-CLÔTURE À ÉCRIRE. `merge_author` supprime l'autorité doublon ; la
-- cascade emporte le signalement. Contrairement aux documents, il n'y a pas
-- d'équivalent de « pas un doublon » côté autorités — d'où l'absence de clôture
-- automatique à poser ici.
--
-- LIMITE CONNUE, ASSUMÉE. Clore un signalement l'acquitte, mais la paire
-- continuera d'apparaître dans `suggest_author_duplicates` : il n'existe pas de
-- table d'arbitrage `author_not_duplicate` équivalente à celle des documents. La
-- coordination peut donc revoir passer une paire déjà jugée. C'est le même
-- défaut que les documents avaient avant le paquet P3, et il se réglera de la
-- même façon le jour où on le décidera — ce paquet ne fait pas semblant de le
-- couvrir.
--
-- CHECKLIST DOCTRINE :
--   [x] Table dans public : GRANT explicites, RLS, policy, GRANT ALL service_role
--   [x] Fonctions SECURITY DEFINER : search_path, REVOKE PUBLIC/anon, GRANT
--   [x] Gardes internes (staff pour signaler et lire, arbitre pour clore)
--   [x] DO block de vérification
-- =========================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.authority_duplicate_reports (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id_a bigint NOT NULL REFERENCES public.authors(id) ON DELETE CASCADE,
  author_id_b bigint NOT NULL REFERENCES public.authors(id) ON DELETE CASCADE,
  note        text,
  reported_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  status      text NOT NULL DEFAULT 'open',
  closed_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  closed_at   timestamptz,
  CONSTRAINT authority_duplicate_reports_ordered CHECK (author_id_a < author_id_b),
  CONSTRAINT authority_duplicate_reports_status  CHECK (status IN ('open', 'closed'))
);

-- Un seul signalement OUVERT par paire : cinq personnes tombant sur la même
-- coquille d'auteur ne doivent pas noyer la file.
CREATE UNIQUE INDEX IF NOT EXISTS authority_duplicate_reports_open_uniq
  ON public.authority_duplicate_reports (author_id_a, author_id_b)
  WHERE status = 'open';

CREATE INDEX IF NOT EXISTS authority_duplicate_reports_status_idx
  ON public.authority_duplicate_reports (status, created_at DESC);

REVOKE ALL ON public.authority_duplicate_reports FROM anon, authenticated;
GRANT ALL ON public.authority_duplicate_reports TO service_role;

ALTER TABLE public.authority_duplicate_reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname = 'public' AND tablename = 'authority_duplicate_reports'
                    AND policyname = 'authority_duplicate_reports_staff_select') THEN
    CREATE POLICY authority_duplicate_reports_staff_select
      ON public.authority_duplicate_reports
      FOR SELECT TO authenticated
      USING (EXISTS (SELECT 1 FROM public.user_library_memberships m
                      WHERE m.user_id = auth.uid()
                        AND m.role = ANY (ARRAY['librarian','coordenador'])
                        AND m.status = 'active'));
  END IF;
END $$;

COMMENT ON TABLE public.authority_duplicate_reports IS
  'Doublons d''autorité signalés par le staff de catalogage à la coordination. Pendant '
  'de catalog_duplicate_reports pour les autorités, avec ses propres clés étrangères. '
  'Un seul signalement ouvert par paire. Paquet DOUBLONS P8 du 21/08/2026.';

-- -------------------------------------------------------------------------
-- Signaler — ouvert à tout le staff de catalogage
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.report_authority_pair(
  p_a    bigint,
  p_b    bigint,
  p_note text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $function$
DECLARE
  v_lo bigint;
  v_hi bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.user_library_memberships m
                 WHERE m.user_id = auth.uid()
                   AND m.role = ANY (ARRAY['librarian','coordenador'])
                   AND m.status = 'active') THEN
    RAISE EXCEPTION 'Acesso restrito ao staff de catalogacao.'
      USING ERRCODE = '42501', HINT = 'error.catalog.discard.forbidden';
  END IF;

  IF p_a IS NULL OR p_b IS NULL OR p_a = p_b THEN
    RAISE EXCEPTION 'Par de autoridades inválido.'
      USING ERRCODE = 'P0001', HINT = 'error.catalog.notDuplicate.invalidPair';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.authors WHERE id = p_a)
     OR NOT EXISTS (SELECT 1 FROM public.authors WHERE id = p_b) THEN
    RAISE EXCEPTION 'Autoridade inexistente.'
      USING ERRCODE = 'P0002', HINT = 'error.catalog.notDuplicate.invalidPair';
  END IF;

  v_lo := least(p_a, p_b);
  v_hi := greatest(p_a, p_b);

  INSERT INTO public.authority_duplicate_reports (author_id_a, author_id_b, note, reported_by)
  SELECT v_lo, v_hi, nullif(btrim(coalesce(p_note, '')), ''), auth.uid()
  WHERE NOT EXISTS (
    SELECT 1 FROM public.authority_duplicate_reports r
     WHERE r.author_id_a = v_lo AND r.author_id_b = v_hi AND r.status = 'open'
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.report_authority_pair(bigint, bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.report_authority_pair(bigint, bigint, text) TO authenticated;

COMMENT ON FUNCTION public.report_authority_pair(bigint, bigint, text) IS
  'Signale une paire d''autorités à la coordination, sans rien modifier au catalogue. '
  'Ouvert à tout le staff. Idempotent tant qu''un signalement reste ouvert.';

-- -------------------------------------------------------------------------
-- Lire — niveau staff (vérifier que son signalement est parti)
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.list_authority_reports(p_max integer DEFAULT 200)
RETURNS TABLE (
  author_id_a      bigint,
  nom_a            text,
  tri_a            text,
  oeuvres_a        integer,
  author_id_b      bigint,
  nom_b            text,
  tri_b            text,
  oeuvres_b        integer,
  note             text,
  created_at       timestamptz,
  reported_by_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $function$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.user_library_memberships m
                 WHERE m.user_id = auth.uid()
                   AND m.role = ANY (ARRAY['librarian','coordenador'])
                   AND m.status = 'active') THEN
    RAISE EXCEPTION 'Acesso restrito ao staff de catalogacao.'
      USING ERRCODE = '42501', HINT = 'error.catalog.discard.forbidden';
  END IF;

  RETURN QUERY
  SELECT
    aa.id, aa.preferred_name, aa.sort_name,
    (SELECT count(*)::integer FROM public.book_authors ba WHERE ba.author_id = aa.id),
    ab.id, ab.preferred_name, ab.sort_name,
    (SELECT count(*)::integer FROM public.book_authors bb WHERE bb.author_id = ab.id),
    r.note,
    r.created_at,
    nullif(btrim(coalesce(p.first_name, '') || ' ' || coalesce(p.last_name, '')), '')
  FROM public.authority_duplicate_reports r
  JOIN public.authors aa ON aa.id = r.author_id_a
  JOIN public.authors ab ON ab.id = r.author_id_b
  LEFT JOIN public.profiles p ON p.id = r.reported_by
  WHERE r.status = 'open'
  ORDER BY r.created_at ASC   -- le plus ancien d'abord : rien ne doit pourrir en file
  LIMIT greatest(1, coalesce(p_max, 200));
END;
$function$;

REVOKE ALL ON FUNCTION public.list_authority_reports(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_authority_reports(integer) TO authenticated;

COMMENT ON FUNCTION public.list_authority_reports(integer) IS
  'Signalements de doublons d''autorité encore ouverts, le plus ancien d''abord, avec les '
  'deux noms, le nombre d''œuvres rattachées de chaque côté et la personne ayant signalé. '
  'Staff de catalogage. Paquet DOUBLONS P8 du 21/08/2026.';

-- -------------------------------------------------------------------------
-- Clore — coordination
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.close_authority_report(p_a bigint, p_b bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $function$
BEGIN
  IF NOT public.fn_is_dedup_arbiter() THEN
    RAISE EXCEPTION 'Arbitragem reservada à coordenação.'
      USING ERRCODE = '42501', HINT = 'error.catalog.arbiter_only';
  END IF;

  UPDATE public.authority_duplicate_reports
     SET status = 'closed', closed_by = auth.uid(), closed_at = now()
   WHERE author_id_a = least(p_a, p_b)
     AND author_id_b = greatest(p_a, p_b)
     AND status = 'open';
END;
$function$;

REVOKE ALL ON FUNCTION public.close_authority_report(bigint, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.close_authority_report(bigint, bigint) TO authenticated;

COMMENT ON FUNCTION public.close_authority_report(bigint, bigint) IS
  'Clôt le signalement ouvert d''une paire d''autorités. Coordination uniquement. '
  'Rappel : clore acquitte, mais la paire réapparaîtra dans suggest_author_duplicates — '
  'il n''existe pas d''arbitrage « pas un doublon » côté autorités. Paquet DOUBLONS P8.';

-- -------------------------------------------------------------------------
-- Vérification (rollback automatique en cas d'échec)
-- -------------------------------------------------------------------------
DO $$
DECLARE
  v_n int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_tables
                  WHERE schemaname = 'public' AND tablename = 'authority_duplicate_reports'
                    AND rowsecurity) THEN
    RAISE EXCEPTION 'RLS absente sur authority_duplicate_reports. Rollback.';
  END IF;

  IF has_table_privilege('authenticated', 'public.authority_duplicate_reports', 'INSERT') THEN
    RAISE EXCEPTION 'authority_duplicate_reports insérable en direct. Rollback.';
  END IF;

  SELECT count(*) INTO v_n
  FROM pg_proc pr JOIN pg_namespace ns ON ns.oid = pr.pronamespace
  WHERE ns.nspname = 'public'
    AND pr.proname IN ('report_authority_pair', 'list_authority_reports', 'close_authority_report')
    AND has_function_privilege('anon', pr.oid, 'EXECUTE');
  IF v_n > 0 THEN
    RAISE EXCEPTION 'Paquet DOUBLONS P8 : % fonction(s) exécutables par anon. Rollback.', v_n;
  END IF;

  -- La cascade est ce qui remplace l'auto-clôture : sans elle, un signalement
  -- survivrait à l'autorité fusionnée.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.authority_duplicate_reports'::regclass
       AND contype = 'f' AND confdeltype = 'c'
  ) THEN
    RAISE EXCEPTION 'Les clés étrangères ne cascadent pas à la suppression. Rollback.';
  END IF;

  RAISE NOTICE 'Paquet DOUBLONS P8 : vérifications OK.';
END $$;

COMMIT;

-- =========================================================================
-- Rollback ciblé :
--   BEGIN;
--     DROP FUNCTION IF EXISTS public.close_authority_report(bigint, bigint);
--     DROP FUNCTION IF EXISTS public.list_authority_reports(integer);
--     DROP FUNCTION IF EXISTS public.report_authority_pair(bigint, bigint, text);
--     DROP TABLE IF EXISTS public.authority_duplicate_reports;
--   COMMIT;
-- =========================================================================
