-- =========================================================================
-- Adaptateur d'import — axe « Perfil » : profils nommés (mapping + valeurs par défaut).
--
-- 3e axe orthogonal après Estrutura (format) et Vocabulário (standard) : un PRESET
-- nommé et réutilisable de règles d'import, par biblioteca :
--   - column_mappings : surcharge explicite « colonne → champ » (prioritaire sur les
--     alias auto du parseur CSV) — ex. {"externalKey":"cote","subjects":"matiere"}.
--   - default_values  : constantes appliquées quand un champ est vide (tous formats) —
--     ex. {"language":"fr","itemType":"livro"}.
-- Le profil choisi est référencé via run.adapter_overrides.profile_id ; le parseur le
-- charge et l'applique. CRUD via RPC gardées coordenador (accès table = RPC only + RLS).
-- =========================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS ingest.import_profiles (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  library_id      uuid NOT NULL,
  name            text NOT NULL,
  column_mappings jsonb NOT NULL DEFAULT '{}'::jsonb,
  default_values  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by      uuid DEFAULT auth.uid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT import_profiles_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT import_profiles_mappings_obj CHECK (jsonb_typeof(column_mappings) = 'object'),
  CONSTRAINT import_profiles_defaults_obj CHECK (jsonb_typeof(default_values) = 'object'),
  CONSTRAINT import_profiles_unique_name UNIQUE (library_id, name)
);

ALTER TABLE ingest.import_profiles ENABLE ROW LEVEL SECURITY;
-- Aucune policy : accès uniquement via les RPC SECURITY DEFINER gardées ci-dessous
-- (owner postgres → bypass RLS) ; service_role (parseur) bypasse aussi la RLS.
GRANT SELECT ON TABLE ingest.import_profiles TO service_role;

COMMENT ON TABLE ingest.import_profiles IS
  'Profils d''import (axe Perfil de l''adaptateur). Preset nommé par biblio : column_mappings '
  '(colonne→champ, prioritaire sur les alias CSV auto) + default_values (constantes si champ vide). '
  'Référencé par run.adapter_overrides.profile_id. Accès via fn_import_profile_*.';

-- ─── Liste des profils d'une biblio ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_import_profiles_list(p_library_id uuid)
RETURNS TABLE (id bigint, name text, column_mappings jsonb, default_values jsonb, created_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, ingest, auth, pg_catalog
AS $$
BEGIN
  IF p_library_id IS NULL THEN RAISE EXCEPTION 'library_id obrigatorio.'; END IF;
  IF NOT (
    EXISTS (SELECT 1 FROM public.user_library_memberships m
             WHERE m.user_id = auth.uid() AND m.library_id = p_library_id
               AND m.status = 'active' AND m.role = 'coordenador')
    OR public.fn_caller_is_network_admin()
  ) THEN RAISE EXCEPTION 'Acesso restrito ao coordenador da biblioteca.'; END IF;
  RETURN QUERY
    SELECT p.id, p.name, p.column_mappings, p.default_values, p.created_at
      FROM ingest.import_profiles p WHERE p.library_id = p_library_id ORDER BY p.name;
END; $$;
REVOKE EXECUTE ON FUNCTION public.fn_import_profiles_list(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.fn_import_profiles_list(uuid) TO authenticated;

-- ─── Création d'un profil ───────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_import_profile_create(
  p_library_id uuid, p_name text,
  p_column_mappings jsonb DEFAULT '{}'::jsonb, p_default_values jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, ingest, auth, pg_catalog
AS $$
DECLARE v_id bigint; v_map jsonb; v_def jsonb;
BEGIN
  IF p_library_id IS NULL OR nullif(btrim(coalesce(p_name,'')), '') IS NULL THEN
    RAISE EXCEPTION 'library_id et name obligatoires.';
  END IF;
  IF NOT (
    EXISTS (SELECT 1 FROM public.user_library_memberships m
             WHERE m.user_id = auth.uid() AND m.library_id = p_library_id
               AND m.status = 'active' AND m.role = 'coordenador')
    OR public.fn_caller_is_network_admin()
  ) THEN RAISE EXCEPTION 'Acesso restrito ao coordenador da biblioteca.'; END IF;
  v_map := coalesce(p_column_mappings, '{}'::jsonb);
  v_def := coalesce(p_default_values, '{}'::jsonb);
  IF jsonb_typeof(v_map) <> 'object' OR jsonb_typeof(v_def) <> 'object' THEN
    RAISE EXCEPTION 'column_mappings et default_values doivent être des objets JSON.';
  END IF;
  INSERT INTO ingest.import_profiles (library_id, name, column_mappings, default_values)
  VALUES (p_library_id, btrim(p_name), v_map, v_def)
  RETURNING id INTO v_id;
  RETURN jsonb_build_object('ok', true, 'id', v_id, 'name', btrim(p_name));
END; $$;
REVOKE EXECUTE ON FUNCTION public.fn_import_profile_create(uuid, text, jsonb, jsonb) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.fn_import_profile_create(uuid, text, jsonb, jsonb) TO authenticated;

-- ─── Suppression d'un profil ────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_import_profile_delete(p_profile_id bigint)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, ingest, auth, pg_catalog
AS $$
DECLARE v_lib uuid;
BEGIN
  IF p_profile_id IS NULL THEN RAISE EXCEPTION 'profile_id obrigatorio.'; END IF;
  SELECT library_id INTO v_lib FROM ingest.import_profiles WHERE id = p_profile_id;
  IF v_lib IS NULL THEN RETURN jsonb_build_object('ok', true, 'deleted', false, 'reason', 'already_gone'); END IF;
  IF NOT (
    EXISTS (SELECT 1 FROM public.user_library_memberships m
             WHERE m.user_id = auth.uid() AND m.library_id = v_lib
               AND m.status = 'active' AND m.role = 'coordenador')
    OR public.fn_caller_is_network_admin()
  ) THEN RAISE EXCEPTION 'Acesso restrito ao coordenador da biblioteca.'; END IF;
  DELETE FROM ingest.import_profiles WHERE id = p_profile_id;
  RETURN jsonb_build_object('ok', true, 'deleted', true);
END; $$;
REVOKE EXECUTE ON FUNCTION public.fn_import_profile_delete(bigint) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.fn_import_profile_delete(bigint) TO authenticated;

-- ─── Associer un profil à un run (avant dispatch) ───────────────────────────
CREATE OR REPLACE FUNCTION public.fn_import_set_profile(p_run_id bigint, p_profile_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, ingest, auth, pg_catalog
AS $$
DECLARE v_run ingest.partner_catalog_import_runs%rowtype; v_ov jsonb;
BEGIN
  IF p_run_id IS NULL THEN RAISE EXCEPTION 'run_id obrigatorio.'; END IF;
  SELECT * INTO v_run FROM ingest.partner_catalog_import_runs WHERE id = p_run_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Run % introuvável.', p_run_id; END IF;
  IF NOT (
    EXISTS (SELECT 1 FROM public.user_library_memberships m
             WHERE m.user_id = auth.uid() AND m.library_id = v_run.library_id
               AND m.status = 'active' AND m.role = 'coordenador')
    OR public.fn_caller_is_network_admin()
  ) THEN RAISE EXCEPTION 'Acesso restrito ao coordenador da biblioteca.'; END IF;
  -- Le profil doit appartenir à la biblio du run (sinon refus).
  IF p_profile_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM ingest.import_profiles p WHERE p.id = p_profile_id AND p.library_id = v_run.library_id
  ) THEN RAISE EXCEPTION 'Profil % introuvable pour cette biblioteca.', p_profile_id; END IF;
  v_ov := coalesce(v_run.adapter_overrides, '{}'::jsonb);
  IF p_profile_id IS NULL THEN
    v_ov := v_ov - 'profile_id';
  ELSE
    v_ov := v_ov || jsonb_build_object('profile_id', p_profile_id);
  END IF;
  UPDATE ingest.partner_catalog_import_runs SET adapter_overrides = v_ov WHERE id = p_run_id;
  RETURN jsonb_build_object('ok', true, 'run_id', p_run_id, 'profile_id', p_profile_id);
END; $$;
REVOKE EXECUTE ON FUNCTION public.fn_import_set_profile(bigint, bigint) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.fn_import_set_profile(bigint, bigint) TO authenticated;

COMMENT ON FUNCTION public.fn_import_set_profile(bigint, bigint) IS
  'Adaptateur (axe Perfil). Pose/retire run.adapter_overrides.profile_id (NULL = retirer), entre '
  'fn_import_create et fn_import_dispatch. Le profil doit appartenir à la biblio du run. Gardée coordenador.';

-- ─── Vérification ───────────────────────────────────────────────────────────
DO $verify$
DECLARE v_fns int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                  WHERE table_schema='ingest' AND table_name='import_profiles') THEN
    RAISE EXCEPTION 'verify: table import_profiles manquante'; END IF;
  SELECT count(*) INTO v_fns FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public' AND p.proname IN
      ('fn_import_profiles_list','fn_import_profile_create','fn_import_profile_delete','fn_import_set_profile');
  IF v_fns <> 4 THEN RAISE EXCEPTION 'verify: attendu 4 RPC profil, trouvé %', v_fns; END IF;
  IF has_function_privilege('anon','public.fn_import_profile_create(uuid,text,jsonb,jsonb)','EXECUTE') THEN
    RAISE EXCEPTION 'verify: create ne doit pas être exécutable par anon'; END IF;
  RAISE NOTICE 'profils d''import OK : table + 4 RPC.';
END; $verify$;

COMMIT;

-- =========================================================================
-- Rollback ciblé :
--   DROP FUNCTION IF EXISTS public.fn_import_set_profile(bigint, bigint);
--   DROP FUNCTION IF EXISTS public.fn_import_profile_delete(bigint);
--   DROP FUNCTION IF EXISTS public.fn_import_profile_create(uuid, text, jsonb, jsonb);
--   DROP FUNCTION IF EXISTS public.fn_import_profiles_list(uuid);
--   DROP TABLE IF EXISTS ingest.import_profiles;
-- =========================================================================
